import { useEffect, useMemo, useState } from "react";
import { fetchManualRecurring, fetchTransactions, fetchTreasuryAlert, saveManualRecurring } from "../../api/client";
import { Category, ManualRecurring, Transaction, TreasuryAlert } from "../../types";
import { addCalendarMonths, buildForecast, detectRecurring, Frequency, monthlyEquivalent, removeManualDuplicates, scenarioAmount } from "./recurringModel";

const CATEGORIES: Category[] = ["hosting", "software", "salary", "travel", "restaurant", "food", "taxes", "equipment", "subscription", "rent", "legal", "insurance", "misc"];
const CATEGORY_LABELS: Record<Category, string> = { hosting: "Hébergement", software: "Logiciels", salary: "Salaires", travel: "Déplacements", restaurant: "Restaurant", food: "Alimentation", taxes: "Impôts et taxes", equipment: "Équipement", subscription: "Abonnements", rent: "Loyer", legal: "Honoraires", insurance: "Assurance", misc: "Divers" };
const FREQUENCY_LABELS: Record<Frequency, string> = { mensuel: "Mensuel", trimestriel: "Trimestriel", annuel: "Annuel" };
const DECISION_LABELS = { keep: "Conserver", reduce: "Réduire", cancel: "Supprimer", planned: "Projet" } as const;
const today = () => new Date().toISOString().slice(0, 10);
const euros = (value: number) => new Intl.NumberFormat("fr-FR", { style: "currency", currency: "EUR", maximumFractionDigits: 0 }).format(value);

export function RecurringView() {
  const [transactions, setTransactions] = useState<Transaction[]>([]); const [manual, setManual] = useState<ManualRecurring[]>([]);
  const [alert, setAlert] = useState<TreasuryAlert>({ threshold: 5000, enabled: false }); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  const [horizon, setHorizon] = useState<3 | 6 | 12>(6); const [view, setView] = useState<"pilot" | "calendar">("pilot");
  const [editingId, setEditingId] = useState<string | null>(null); const [form, setForm] = useState<Partial<ManualRecurring>>({});
  const [ignored, setIgnored] = useState<Set<string>>(() => new Set(JSON.parse(localStorage.getItem("compta_dismissed_patterns") ?? "[]") as string[]));

  useEffect(() => { Promise.all([fetchTransactions(), fetchManualRecurring(), fetchTreasuryAlert()]).then(([entries, stored, treasuryAlert]) => { setTransactions(entries); setManual(stored); setAlert(treasuryAlert); }).finally(() => setLoading(false)); }, []);
  const detectedAll = useMemo(() => removeManualDuplicates(detectRecurring(transactions), manual), [transactions, manual]);
  const detected = useMemo(() => detectedAll.filter((item) => !ignored.has(item.key)), [detectedAll, ignored]);
  const currentBalance = useMemo(() => transactions.filter((entry) => entry.status !== "rejected").reduce((sum, entry) => sum + entry.amount_ttc, 0), [transactions]);
  const baseMonthly = useMemo(() => manual.filter((item) => item.active && item.decision !== "planned").reduce((sum, item) => sum + monthlyEquivalent(item.amount, item.frequency), 0) + detected.reduce((sum, item) => sum + monthlyEquivalent(item.amount, item.frequency), 0), [manual, detected]);
  const scenarioMonthly = useMemo(() => manual.reduce((sum, item) => sum + monthlyEquivalent(scenarioAmount(item), item.frequency), 0) + detected.reduce((sum, item) => sum + monthlyEquivalent(item.amount, item.frequency), 0), [manual, detected]);
  const savingsMonthly = baseMonthly - scenarioMonthly;
  const scenarioItems = useMemo(() => [...manual.map((item) => ({ id: item.id, label: item.label, amount: scenarioAmount(item), frequency: item.frequency, nextPayment: item.nextPayment, active: item.active && scenarioAmount(item) > 0 })), ...detected.map((item) => ({ id: `auto-${item.key}`, label: item.label, amount: item.amount, frequency: item.frequency, nextPayment: item.nextPayment, active: true }))], [manual, detected]);
  const forecast = useMemo(() => buildForecast(scenarioItems, transactions, horizon, currentBalance), [scenarioItems, transactions, horizon, currentBalance]);
  const next30 = useMemo(() => { const limit = new Date(); limit.setDate(limit.getDate() + 30); const end = limit.toISOString().slice(0, 10); return scenarioItems.filter((item) => item.active && item.nextPayment >= today() && item.nextPayment <= end).reduce((sum, item) => sum + item.amount, 0); }, [scenarioItems]);
  const runway = scenarioMonthly > 0 ? currentBalance / scenarioMonthly : Infinity;
  const warnings = useMemo(() => {
    const messages: string[] = [];
    const overdue = manual.filter((item) => item.active && item.nextPayment < today()).length; if (overdue) messages.push(`${overdue} échéance(s) manuelle(s) sont dépassées : confirme le paiement ou décale la prochaine date.`);
    const increases = detected.filter((item) => item.trendPercent >= 10); if (increases.length) messages.push(`${increases.length} frais détecté(s) ont augmenté d'au moins 10 %.`);
    const thresholdMonth = alert.enabled ? forecast.find((month) => month.balance < alert.threshold) : undefined; if (thresholdMonth) messages.push(`Le solde passerait sous ${euros(alert.threshold)} en ${thresholdMonth.month}.`);
    if (detected.length) messages.push(`${detected.length} récurrence(s) bancaire(s) attendent confirmation.`);
    return messages;
  }, [manual, detected, forecast, alert]);

  async function persist(entries: ManualRecurring[]) { setSaving(true); setManual(entries); try { await saveManualRecurring(entries); } finally { setSaving(false); } }
  function startNew() { setEditingId("new"); setForm({ label: "", amount: 0, category: "misc", frequency: "mensuel", nextPayment: today(), active: true, decision: "keep" }); }
  function startEdit(item: ManualRecurring) { setEditingId(item.id); setForm(item); }
  async function saveForm() { if (!form.label?.trim() || !form.amount || form.amount <= 0 || !form.nextPayment) return; const item = { id: editingId === "new" ? `manual_${Date.now()}` : editingId!, label: form.label.trim(), amount: Number(form.amount), category: form.category ?? "misc", frequency: form.frequency ?? "mensuel", nextPayment: form.nextPayment, active: form.active ?? true, decision: form.decision ?? "keep", simulatedAmount: form.simulatedAmount, notes: form.notes } satisfies ManualRecurring; await persist(editingId === "new" ? [...manual, item] : manual.map((entry) => entry.id === editingId ? item : entry)); setEditingId(null); setForm({}); }
  async function patchManual(id: string, changes: Partial<ManualRecurring>) { await persist(manual.map((item) => item.id === id ? { ...item, ...changes } : item)); }
  async function confirmDetected(key: string) { const item = detected.find((entry) => entry.key === key); if (!item) return; await persist([...manual, { id: `manual_${Date.now()}`, label: item.label, amount: item.amount, category: item.category, frequency: item.frequency, nextPayment: item.nextPayment, active: true, decision: "keep" }]); }
  function ignoreDetected(key: string) { const next = new Set(ignored).add(key); setIgnored(next); localStorage.setItem("compta_dismissed_patterns", JSON.stringify([...next])); }
  async function advancePayment(item: ManualRecurring) { await patchManual(item.id, { nextPayment: addCalendarMonths(item.nextPayment, item.frequency === "mensuel" ? 1 : item.frequency === "trimestriel" ? 3 : 12) }); }

  if (loading) return <div className="p-6 text-sm text-vscode-muted">Analyse des frais en cours…</div>;
  return <div className="h-full overflow-auto p-6 flex flex-col gap-5 max-w-6xl mx-auto">
    <header className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-lg font-semibold text-vscode-text">Pilotage des frais récurrents</h1><p className="text-xs text-vscode-muted mt-1">Visualise le coût structurel, prépare les décisions et mesure leur effet sur la trésorerie.</p></div><button onClick={startNew} disabled={editingId !== null} className="px-3 py-2 bg-vscode-accent text-white text-xs rounded disabled:opacity-40">＋ Ajouter un frais</button></header>

    <section className="grid grid-cols-2 lg:grid-cols-5 gap-3">{[
      ["Coût mensuel", euros(baseMonthly), "text-red-400"], ["Coût annuel réel", euros(baseMonthly * 12), "text-vscode-text"], ["À payer sous 30 j", euros(next30), "text-amber-400"], [savingsMonthly >= 0 ? "Économie simulée" : "Surcoût simulé", euros(Math.abs(savingsMonthly) * 12) + "/an", savingsMonthly >= 0 ? "text-green-400" : "text-red-400"], ["Autonomie sur frais fixes", Number.isFinite(runway) ? `${runway.toFixed(1)} mois` : "∞", runway < 3 ? "text-red-400" : "text-vscode-text"],
    ].map(([label, value, color]) => <div key={label} className="bg-vscode-panel border border-vscode-border rounded-lg p-4"><p className="text-[10px] uppercase tracking-wide text-vscode-muted">{label}</p><p className={`text-xl font-semibold mt-1 ${color}`}>{value}</p></div>)}</section>

    {warnings.length > 0 && <section className="border border-amber-700/60 bg-amber-900/10 rounded-lg p-3"><h2 className="text-xs font-semibold text-amber-300 mb-1">Points d'attention</h2><ul className="text-xs text-amber-200/90 space-y-1">{warnings.map((message) => <li key={message}>• {message}</li>)}</ul></section>}
    <nav className="flex gap-1 border-b border-vscode-border"><button onClick={() => setView("pilot")} className={`px-3 py-2 text-xs ${view === "pilot" ? "text-vscode-text border-b-2 border-vscode-accent" : "text-vscode-muted"}`}>Liste et décisions</button><button onClick={() => setView("calendar")} className={`px-3 py-2 text-xs ${view === "calendar" ? "text-vscode-text border-b-2 border-vscode-accent" : "text-vscode-muted"}`}>Calendrier prévisionnel</button></nav>

    {view === "pilot" && <>
      {editingId && <section className="border border-vscode-accent rounded-lg p-4 bg-blue-900/10 grid sm:grid-cols-2 lg:grid-cols-6 gap-2 items-end"><label className="lg:col-span-2 text-[10px] text-vscode-muted">Libellé<input value={form.label ?? ""} onChange={(event) => setForm({ ...form, label: event.target.value })} className="block w-full mt-1 bg-vscode-bg border border-vscode-border rounded px-2 py-1.5 text-xs text-vscode-text"/></label><label className="text-[10px] text-vscode-muted">Montant TTC<input type="number" min="0" step="0.01" value={form.amount ?? ""} onChange={(event) => setForm({ ...form, amount: Number(event.target.value) })} className="block w-full mt-1 bg-vscode-bg border border-vscode-border rounded px-2 py-1.5 text-xs text-vscode-text"/></label><label className="text-[10px] text-vscode-muted">Fréquence<select value={form.frequency ?? "mensuel"} onChange={(event) => setForm({ ...form, frequency: event.target.value as Frequency })} className="block w-full mt-1 bg-vscode-bg border border-vscode-border rounded px-2 py-1.5 text-xs text-vscode-text"><option value="mensuel">Mensuel</option><option value="trimestriel">Trimestriel</option><option value="annuel">Annuel</option></select></label><label className="text-[10px] text-vscode-muted">Prochaine échéance<input type="date" value={form.nextPayment ?? ""} onChange={(event) => setForm({ ...form, nextPayment: event.target.value })} className="block w-full mt-1 bg-vscode-bg border border-vscode-border rounded px-2 py-1.5 text-xs text-vscode-text"/></label><div className="flex gap-1"><button onClick={() => void saveForm()} disabled={!form.label || !form.amount || saving} className="px-3 py-1.5 bg-vscode-accent text-white text-xs rounded">Enregistrer</button><button onClick={() => setEditingId(null)} className="px-2 py-1.5 border border-vscode-border text-xs rounded">Annuler</button></div><label className="text-[10px] text-vscode-muted">Catégorie<select value={form.category ?? "misc"} onChange={(event) => setForm({ ...form, category: event.target.value as Category })} className="block w-full mt-1 bg-vscode-bg border border-vscode-border rounded px-2 py-1.5 text-xs text-vscode-text">{CATEGORIES.map((category) => <option key={category} value={category}>{CATEGORY_LABELS[category]}</option>)}</select></label><label className="lg:col-span-5 text-[10px] text-vscode-muted">Note de décision<input value={form.notes ?? ""} onChange={(event) => setForm({ ...form, notes: event.target.value })} placeholder="Engagement, préavis, alternative…" className="block w-full mt-1 bg-vscode-bg border border-vscode-border rounded px-2 py-1.5 text-xs text-vscode-text"/></label></section>}
      <section><div className="flex justify-between items-baseline mb-2"><h2 className="text-xs font-semibold uppercase tracking-wide text-vscode-muted">Frais confirmés ({manual.length})</h2><span className="text-[10px] text-vscode-muted">Le scénario est enregistré avec chaque frais.</span></div><div className="border border-vscode-border rounded-lg overflow-auto"><table className="w-full text-xs"><thead className="bg-vscode-panel text-vscode-muted"><tr>{["Frais", "Coût", "Échéance", "Décision", "Impact mensuel", "Actions"].map((title) => <th key={title} className="text-left font-normal px-3 py-2">{title}</th>)}</tr></thead><tbody>{manual.map((item) => { const scenario = scenarioAmount(item); return <tr key={item.id} className={`border-t border-vscode-border ${item.active ? "" : "opacity-40"}`}><td className="px-3 py-2"><p className="text-vscode-text font-medium">{item.label}</p><p className="text-[10px] text-vscode-muted">{CATEGORY_LABELS[item.category]} · {FREQUENCY_LABELS[item.frequency]}{item.notes ? ` · ${item.notes}` : ""}</p></td><td className="px-3 py-2"><p>{euros(item.amount)}</p><p className="text-[10px] text-vscode-muted">{euros(monthlyEquivalent(item.amount, item.frequency))}/mois</p></td><td className={`px-3 py-2 ${item.nextPayment < today() ? "text-amber-400" : ""}`}>{item.nextPayment}<button onClick={() => void advancePayment(item)} className="block text-[10px] text-vscode-accent mt-0.5">Paiement effectué →</button></td><td className="px-3 py-2"><select value={item.decision ?? "keep"} onChange={(event) => void patchManual(item.id, { decision: event.target.value as ManualRecurring["decision"] })} className="bg-vscode-bg border border-vscode-border rounded px-2 py-1">{Object.entries(DECISION_LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select>{item.decision === "reduce" && <input type="number" min="0" value={item.simulatedAmount ?? item.amount} onChange={(event) => void patchManual(item.id, { simulatedAmount: Number(event.target.value) })} className="block w-24 mt-1 bg-vscode-bg border border-vscode-border rounded px-2 py-1"/>}</td><td className={scenario < item.amount ? "px-3 py-2 text-green-400" : "px-3 py-2 text-vscode-muted"}>{scenario < item.amount ? `−${euros(monthlyEquivalent(item.amount - scenario, item.frequency))}/mois` : "—"}</td><td className="px-3 py-2 whitespace-nowrap"><button onClick={() => startEdit(item)} className="mr-2 text-vscode-accent">Modifier</button><button onClick={() => void persist(manual.filter((entry) => entry.id !== item.id))} className="text-red-400">Supprimer</button></td></tr>; })}{manual.length === 0 && <tr><td colSpan={6} className="text-center text-vscode-muted py-6">Aucun frais confirmé.</td></tr>}</tbody></table></div></section>
      <section><div className="flex justify-between items-baseline mb-2"><h2 className="text-xs font-semibold uppercase tracking-wide text-vscode-muted">Détectés dans la banque ({detected.length})</h2>{ignored.size > 0 && <button onClick={() => { setIgnored(new Set()); localStorage.removeItem("compta_dismissed_patterns"); }} className="text-[10px] text-vscode-accent">Restaurer les éléments ignorés</button>}</div><div className="grid md:grid-cols-2 gap-2">{detected.map((item) => <article key={item.key} className="border border-vscode-border rounded-lg p-3 flex justify-between gap-3"><div className="min-w-0"><p className="text-xs text-vscode-text truncate">{item.label}</p><p className="text-[10px] text-vscode-muted mt-1">{euros(item.amount)} · {FREQUENCY_LABELS[item.frequency]} · {item.occurrences} occurrences · confiance {item.confidence}</p>{item.trendPercent >= 10 && <p className="text-[10px] text-amber-400 mt-1">Hausse observée : +{item.trendPercent} %</p>}</div><div className="flex flex-col gap-1 shrink-0"><button onClick={() => void confirmDetected(item.key)} className="px-2 py-1 bg-vscode-accent text-white rounded text-[10px]">Confirmer</button><button onClick={() => ignoreDetected(item.key)} className="px-2 py-1 border border-vscode-border rounded text-[10px] text-vscode-muted">Ignorer</button></div></article>)}{detected.length === 0 && <p className="text-xs text-vscode-muted italic">Aucune nouvelle récurrence à confirmer.</p>}</div></section>
    </>}

    {view === "calendar" && <section><div className="flex items-center justify-between mb-3"><div><h2 className="text-xs font-semibold uppercase tracking-wide text-vscode-muted">Projection avec le scénario courant</h2><p className="text-[10px] text-vscode-muted mt-1">Recettes : moyenne observée sur les trois derniers mois. Dépenses : échéances récurrentes confirmées et détectées.</p></div><div className="flex gap-1">{([3, 6, 12] as const).map((months) => <button key={months} onClick={() => setHorizon(months)} className={`px-2 py-1 text-[10px] rounded ${horizon === months ? "bg-vscode-accent text-white" : "border border-vscode-border text-vscode-muted"}`}>{months} mois</button>)}</div></div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3">{forecast.map((month) => <article key={month.month} className={`border rounded-lg p-3 ${alert.enabled && month.balance < alert.threshold ? "border-red-700 bg-red-900/10" : "border-vscode-border bg-vscode-panel"}`}><div className="flex justify-between"><strong className="text-sm text-vscode-text">{month.month}</strong><span className={month.balance >= 0 ? "text-green-400 text-sm" : "text-red-400 text-sm"}>{euros(month.balance)}</span></div><div className="grid grid-cols-2 gap-2 my-2 text-[10px]"><span className="text-green-400">Recettes moy. +{euros(month.revenue)}</span><span className="text-red-400 text-right">Frais −{euros(month.expenses)}</span></div><ul className="border-t border-vscode-border pt-2 space-y-1">{month.items.map((item) => <li key={item.key} className="flex justify-between text-[10px] text-vscode-muted"><span className="truncate">{item.label}</span><span className="ml-2 shrink-0">{euros(item.amount)}</span></li>)}{month.items.length === 0 && <li className="text-[10px] text-vscode-muted italic">Aucune échéance</li>}</ul></article>)}</div><div className={`mt-4 border rounded-lg p-4 ${savingsMonthly >= 0 ? "border-green-800 bg-green-900/10" : "border-red-800 bg-red-900/10"}`}><p className="text-xs text-vscode-muted">Effet du scénario sur 12 mois</p><p className={`text-xl font-semibold mt-1 ${savingsMonthly >= 0 ? "text-green-400" : "text-red-400"}`}>{euros(Math.abs(savingsMonthly) * 12)} {savingsMonthly >= 0 ? "économisés" : "de surcoût"}</p><p className="text-[10px] text-vscode-muted mt-1">Coût structurel simulé : {euros(scenarioMonthly)}/mois contre {euros(baseMonthly)}/mois actuellement.</p></div></section>}
  </div>;
}
