import { randomUUID } from "node:crypto";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { atomicWriteFileSync } from "./atomicFile.js";
import { getCompaniesRoot, loadCompanies, resolveCompanyPath } from "./companiesService.js";
import { loadFinanceTransactions, type AllocatedTransaction, type FinanceScope } from "./financeAllocationService.js";
import { actorHasGlobalAccess, getScopeAccess, getVisiblePlatformState, type PlatformState } from "./platformService.js";
import type { RequestActor } from "./requestActor.js";
import type { ManualRecurring } from "./manualRecurringService.js";
import type { OutgoingInvoice } from "../types/index.js";

export type TransferTreatment = "internal_transfer" | "capital_contribution" | "shareholder_current_account" | "intercompany_loan" | "dividend" | "reimbursement";
export type ForecastScenario = "prudent" | "probable" | "optimistic";
export type CommitmentKind = "supplier_invoice" | "tax" | "loan_payment" | "investment" | "other";
export interface AccountingLine { scopeId: string; accountCode: string; label: string; debit: number; credit: number }
export interface PortfolioTransfer { id: string; kind: "confirmed" | "planned"; sourceScopeId: string; destinationScopeId: string; amount: number; fee?: number; date: string; label: string; treatment: TransferTreatment; sourceTransactionKey?: string; destinationTransactionKey?: string; frequency?: "once" | "monthly"; endDate?: string; accountingLines: AccountingLine[]; createdAt: string }
export type PortfolioTransferInput = Omit<PortfolioTransfer, "id" | "createdAt" | "accountingLines" | "treatment"> & { treatment?: TransferTreatment };
export interface PortfolioCommitment { id: string; scopeId: string; kind: CommitmentKind; label: string; amount: number; dueDate: string; frequency: "once" | "monthly" | "quarterly" | "annual"; endDate?: string; createdAt: string }
export interface ScenarioAssumption { revenueMultiplier: number; expenseMultiplier: number; safetyBuffer: number }
export interface PortfolioAssumptions { prudent: ScenarioAssumption; probable: ScenarioAssumption; optimistic: ScenarioAssumption }
interface PortfolioStore { schemaVersion: 2; transfers: PortfolioTransfer[]; commitments: PortfolioCommitment[]; assumptions: PortfolioAssumptions }
export interface ForecastItem { scopeId: string; kind: string; label: string; amount: number; date: string }
export interface ConsolidatedForecastMonth { month: string; openingBalance: number; income: number; expenses: number; transfersIn: number; transfersOut: number; closingBalance: number; items: ForecastItem[] }
export interface PortfolioPosition { scopeId: string; name: string; balance: number; vatReserve: number; commitments90Days: number; available: number }
export interface OwnershipPosition { scopeId: string; name: string; ownershipPercent: number; minorityPercent: number; balance: number; groupShare: number; minorityShare: number }
export interface ConsolidationSummary { grossBalance: number; groupShareBalance: number; minorityShareBalance: number; eliminatedTransfers: number; eliminatedAmount: number; reciprocalAccounts: Array<{ from: string; to: string; treatment: TransferTreatment; amount: number }> }
export interface PortfolioSnapshot { rootScopeId: string; scopes: FinanceScope[]; suggestedScopeIds: string[]; selectedScopeIds: string[]; balance: number; averageIncome: number; averageExpenses: number; transfers: PortfolioTransfer[]; commitments: PortfolioCommitment[]; assumptions: PortfolioAssumptions; transferCandidates: AllocatedTransaction[]; forecasts: Record<ForecastScenario, ConsolidatedForecastMonth[]>; forecast: ConsolidatedForecastMonth[]; positions: PortfolioPosition[]; timeline: ForecastItem[]; ownership: OwnershipPosition[]; consolidation: ConsolidationSummary }

const storeFile = () => join(getCompaniesRoot(), "_portfolio.json");
const legacyFile = () => join(getCompaniesRoot(), "_portfolio_transfers.json");
const defaults: PortfolioAssumptions = { prudent: { revenueMultiplier: .7, expenseMultiplier: 1.1, safetyBuffer: 0 }, probable: { revenueMultiplier: 1, expenseMultiplier: 1, safetyBuffer: 0 }, optimistic: { revenueMultiplier: 1.2, expenseMultiplier: .95, safetyBuffer: 0 } };
const round2 = (value: number) => Math.round(value * 100) / 100;
const scopes = (state: PlatformState): FinanceScope[] => [...state.people, ...state.households, ...state.entities].map(({ id, name, kind }) => ({ id, name, kind }));
const monthShift = (month: string, offset: number) => { const [y, m] = month.split("-").map(Number); return new Date(Date.UTC(y, m - 1 + offset, 1)).toISOString().slice(0, 7); };
const monthAt = (offset: number) => monthShift(new Date().toISOString().slice(0, 7), offset);
function json<T>(path: string, fallback: T): T { try { return existsSync(path) ? JSON.parse(readFileSync(path, "utf-8")) as T : fallback; } catch { return fallback; } }
function lines(t: Pick<PortfolioTransfer, "sourceScopeId" | "destinationScopeId" | "amount" | "fee" | "label" | "treatment">): AccountingLine[] { const codes: Record<TransferTreatment, [string, string]> = { internal_transfer: ["580000", "580000"], capital_contribution: ["261000", "101000"], shareholder_current_account: ["455100", "455100"], intercompany_loan: ["267000", "168000"], dividend: ["457000", "761000"], reimbursement: ["467000", "467000"] }; const [a, b] = codes[t.treatment ?? "internal_transfer"]; const result = [{ scopeId: t.sourceScopeId, accountCode: a, label: t.label, debit: t.amount, credit: 0 }, { scopeId: t.destinationScopeId, accountCode: b, label: t.label, debit: 0, credit: t.amount }]; if ((t.fee ?? 0) > 0) result.push({ scopeId: t.sourceScopeId, accountCode: "627000", label: `Frais - ${t.label}`, debit: t.fee ?? 0, credit: 0 }); return result; }
function readStore(): PortfolioStore { const current = json<Partial<PortfolioStore>>(storeFile(), {}), legacy = json<{ transfers?: PortfolioTransfer[] }>(legacyFile(), {}); const transfers = current.transfers ?? legacy.transfers ?? []; return { schemaVersion: 2, transfers: transfers.map((t) => ({ ...t, treatment: t.treatment ?? "internal_transfer", fee: t.fee ?? 0, accountingLines: t.accountingLines ?? lines(t) })), commitments: current.commitments ?? [], assumptions: { ...defaults, ...(current.assumptions ?? {}) } }; }
function writeStore(store: PortfolioStore) { atomicWriteFileSync(storeFile(), JSON.stringify(store, null, 2)); }
function assertManage(actor: RequestActor, ids: string[]) { if (!actorHasGlobalAccess(actor) && ids.some((id) => !["owner", "manager"].includes(getScopeAccess(actor, id) ?? ""))) throw Object.assign(new Error("Droits de gestion requis."), { code: "FORBIDDEN" }); }
function suggested(state: PlatformState, root: string) { const accepted = new Set(["family", "spouse", "parent", "child", "member", "owner", "shareholder", "subsidiary", "management"]), known = new Set(scopes(state).map((s) => s.id)), result = new Set([root]), queue = [root]; while (queue.length) { const id = queue.shift()!; for (const r of state.relations) { if (!accepted.has(r.type)) continue; const next = r.fromId === id ? r.toId : r.toId === id ? r.fromId : undefined; if (next && known.has(next) && !result.has(next)) { result.add(next); queue.push(next); } } } return [...result]; }
function companyFor(state: PlatformState, id: string) { const entity = state.entities.find((e) => e.id === id); return loadCompanies().find((c) => c.id === entity?.workspaceId || c.scopeId === id); }
function recurring(state: PlatformState, selected: Set<string>) { const result: Array<{ scopeId: string; item: ManualRecurring }> = []; for (const company of loadCompanies()) { const scopeId = company.scopeId ?? state.entities.find((e) => e.workspaceId === company.id)?.id; if (!scopeId || !selected.has(scopeId)) continue; for (const item of json<ManualRecurring[]>(join(resolveCompanyPath(company), "settings", "manual_recurring.json"), [])) if (item.active && item.decision !== "cancel") result.push({ scopeId, item }); } return result; }
function occurs(date: string, frequency: string | undefined, end: string | undefined, month: string) { const start = date.slice(0, 7); if (month < start || (end && month > end.slice(0, 7))) return false; const [sy, sm] = start.split("-").map(Number), [ty, tm] = month.split("-").map(Number), diff = (ty - sy) * 12 + tm - sm; const interval = frequency === "monthly" || frequency === "mensuel" ? 1 : frequency === "quarterly" || frequency === "trimestriel" ? 3 : frequency === "annual" || frequency === "annuel" ? 12 : 0; return interval ? diff % interval === 0 : month === start; }
function balances(state: PlatformState, selected: Set<string>) { const result = new Map<string, number>(); for (const account of state.accounts) { const related = state.relations.filter((r) => ["holder", "uses"].includes(r.type) && [r.fromId, r.toId].includes(account.id)).map((r) => r.fromId === account.id ? r.toId : r.fromId).find((id) => selected.has(id)); const entity = state.entities.find((e) => e.workspaceId === account.sourceWorkspaceId); const id = related ?? (entity && selected.has(entity.id) ? entity.id : undefined); if (id) result.set(id, round2((result.get(id) ?? 0) + (account.balance ?? 0))); } return result; }
function ownership(state: PlatformState, root: string, selected: Set<string>) { const result = new Map([[root, 100]]), queue = [root]; while (queue.length) { const from = queue.shift()!, base = result.get(from) ?? 0; for (const r of state.relations.filter((x) => x.fromId === from && ["owner", "shareholder", "subsidiary"].includes(x.type) && selected.has(x.toId))) { const next = Math.min(100, base * (r.ownershipPercent ?? 100) / 100); if (next > (result.get(r.toId) ?? 0)) { result.set(r.toId, next); queue.push(r.toId); } } } return result; }
function automaticItems(state: PlatformState, selected: Set<string>, month: string): ForecastItem[] { const items: ForecastItem[] = []; for (const scopeId of selected) { const company = companyFor(state, scopeId); if (!company) continue; const root = resolveCompanyPath(company); for (const inv of json<OutgoingInvoice[]>(join(root, "settings", "invoices.json"), [])) if (["sent", "overdue"].includes(inv.status) && inv.dueDate.slice(0, 7) === month) items.push({ scopeId, kind: "customer_invoice", label: `Facture ${inv.number} - ${inv.client}`, amount: Math.abs(inv.amount_ttc), date: inv.dueDate }); const hr = json<{ employees?: Array<{ firstName: string; lastName: string; startDate: string; endDate?: string; employerCostMonthly: number; includeInForecast: boolean; active: boolean }>; variables?: Array<{ month: string; label: string; amount: number }> }>(join(root, "hr", "data.json"), {}); for (const employee of hr.employees ?? []) if (employee.active && employee.includeInForecast && employee.startDate.slice(0, 7) <= month && (!employee.endDate || employee.endDate.slice(0, 7) >= month)) items.push({ scopeId, kind: "payroll", label: `Paie et charges - ${employee.firstName} ${employee.lastName}`, amount: -Math.abs(employee.employerCostMonthly), date: `${month}-28` }); for (const v of hr.variables ?? []) if (v.month === month) items.push({ scopeId, kind: "payroll_variable", label: v.label, amount: -Math.abs(v.amount), date: `${month}-28` }); const profile = json<{ vatRegime?: string; vatOpeningBalance?: number; vatReferenceAmount?: number }>(join(root, "settings", "company_profile.json"), {}); if (profile.vatRegime && profile.vatRegime !== "franchise") { const opening = Math.max(0, Number(profile.vatOpeningBalance) || 0), reference = Number(profile.vatReferenceAmount) || opening; if (profile.vatRegime === "monthly_ca3" && opening > 0) items.push({ scopeId, kind: "vat", label: "TVA future estimée", amount: -opening, date: `${month}-20` }); if (profile.vatRegime === "simplified_ca12" && (month.endsWith("-07") || month.endsWith("-12")) && reference > 0) items.push({ scopeId, kind: "vat", label: "Acompte de TVA", amount: -round2(reference * (month.endsWith("-07") ? .55 : .4)), date: `${month}-20` }); } } return items; }

export async function getPortfolioSnapshot(actor: RequestActor, rootScopeId: string, horizon: number, selectedInput?: string[], candidateMonth = monthAt(0)): Promise<PortfolioSnapshot> {
  const state = getVisiblePlatformState(actor), all = scopes(state), available = new Set(all.map((s) => s.id)); if (!available.has(rootScopeId)) throw Object.assign(new Error("Périmètre inaccessible."), { code: "NOT_FOUND" }); const suggestedScopeIds = suggested(state, rootScopeId), selectedScopeIds = (selectedInput?.length ? selectedInput : suggestedScopeIds).filter((id, i, list) => available.has(id) && list.indexOf(id) === i); if (!selectedScopeIds.includes(rootScopeId)) selectedScopeIds.unshift(rootScopeId); const selected = new Set(selectedScopeIds), store = readStore(), visible = store.transfers.filter((t) => available.has(t.sourceScopeId) && available.has(t.destinationScopeId)), byScope = balances(state, selected), balance = round2([...byScope.values()].reduce((a, b) => a + b, 0)); const confirmed = new Set(visible.filter((t) => t.kind === "confirmed" && selected.has(t.sourceScopeId) && selected.has(t.destinationScopeId)).flatMap((t) => [t.sourceTransactionKey, t.destinationTransactionKey].filter(Boolean) as string[])); let incomeTotal = 0, expenseTotal = 0;
  for (const offset of [-3, -2, -1]) for (const transaction of (await loadFinanceTransactions(actor, monthAt(offset))).transactions) { if (confirmed.has(transaction.key)) continue; const amount = transaction.allocations.filter((a) => selected.has(a.scopeId)).reduce((s, a) => s + a.amount, 0); amount > 0 ? incomeTotal += amount : expenseTotal += Math.abs(amount); }
  const averageIncome = round2(incomeTotal / 3), averageExpenses = round2(expenseTotal / 3), recurrings = recurring(state, selected), months = Array.from({ length: Math.min(60, Math.max(1, horizon)) }, (_, i) => monthAt(i)), forecasts = {} as Record<ForecastScenario, ConsolidatedForecastMonth[]>;
  for (const scenario of ["prudent", "probable", "optimistic"] as ForecastScenario[]) { const assumption = store.assumptions[scenario]; let running = round2(balance - assumption.safetyBuffer); forecasts[scenario] = months.map((month) => { const items = automaticItems(state, selected, month); for (const entry of recurrings) if (occurs(entry.item.nextPayment, entry.item.frequency, entry.item.endPayment, month)) items.push({ scopeId: entry.scopeId, kind: "recurring", label: entry.item.label, amount: -Math.abs(entry.item.decision === "reduce" && entry.item.simulatedAmount !== undefined ? entry.item.simulatedAmount : entry.item.amount), date: `${month}-01` }); for (const c of store.commitments.filter((x) => selected.has(x.scopeId) && occurs(x.dueDate, x.frequency, x.endDate, month))) items.push({ scopeId: c.scopeId, kind: c.kind, label: c.label, amount: -c.amount, date: c.dueDate.slice(0, 7) === month ? c.dueDate : `${month}-${c.dueDate.slice(8, 10)}` }); let transfersIn = 0, transfersOut = 0; for (const t of visible.filter((x) => x.kind === "planned" && occurs(x.date, x.frequency, x.endDate, month))) { const source = selected.has(t.sourceScopeId), destination = selected.has(t.destinationScopeId); if (source && !destination) transfersOut += t.amount + (t.fee ?? 0); if (destination && !source) transfersIn += t.amount; if (source && destination && (t.fee ?? 0) > 0) items.push({ scopeId: t.sourceScopeId, kind: "bank_fee", label: `Frais - ${t.label}`, amount: -(t.fee ?? 0), date: t.date }); } const knownIncome = items.filter((i) => i.amount > 0).reduce((s, i) => s + i.amount, 0), expenses = Math.abs(items.filter((i) => i.amount < 0).reduce((s, i) => s + i.amount, 0)), income = round2(averageIncome * assumption.revenueMultiplier + knownIncome), adjustedExpenses = round2(expenses * assumption.expenseMultiplier), openingBalance = running; running = round2(running + income - adjustedExpenses + transfersIn - transfersOut); return { month, openingBalance, income, expenses: adjustedExpenses, transfersIn: round2(transfersIn), transfersOut: round2(transfersOut), closingBalance: running, items }; }); }
  const candidateMonths = [-1, 0, 1].map((i) => monthShift(candidateMonth, i)), transferCandidates = (await Promise.all(candidateMonths.map((m) => loadFinanceTransactions(actor, m)))).flatMap((x) => x.transactions).filter((t, i, list) => t.allocations.some((a) => selected.has(a.scopeId)) && list.findIndex((x) => x.key === t.key) === i); const ownershipMap = ownership(state, rootScopeId, selected), ownershipRows = selectedScopeIds.map((scopeId) => { const p = ownershipMap.get(scopeId) ?? 0, b = byScope.get(scopeId) ?? 0; return { scopeId, name: all.find((s) => s.id === scopeId)?.name ?? scopeId, ownershipPercent: round2(p), minorityPercent: round2(100 - p), balance: b, groupShare: round2(b * p / 100), minorityShare: round2(b * (100 - p) / 100) }; }), internal = visible.filter((t) => t.kind === "confirmed" && selected.has(t.sourceScopeId) && selected.has(t.destinationScopeId)), consolidation = { grossBalance: balance, groupShareBalance: round2(ownershipRows.reduce((s, x) => s + x.groupShare, 0)), minorityShareBalance: round2(ownershipRows.reduce((s, x) => s + x.minorityShare, 0)), eliminatedTransfers: internal.length, eliminatedAmount: round2(internal.reduce((s, t) => s + t.amount, 0)), reciprocalAccounts: internal.filter((t) => ["shareholder_current_account", "intercompany_loan"].includes(t.treatment)).map((t) => ({ from: t.sourceScopeId, to: t.destinationScopeId, treatment: t.treatment, amount: t.amount })) }; const limit = monthShift(monthAt(0), 3), positions = selectedScopeIds.map((scopeId) => { const reserve = Math.abs(automaticItems(state, new Set([scopeId]), monthAt(0)).filter((i) => i.kind === "vat").reduce((s, i) => s + i.amount, 0)), commitments = store.commitments.filter((c) => c.scopeId === scopeId && c.dueDate.slice(0, 7) <= limit).reduce((s, c) => s + c.amount, 0), b = byScope.get(scopeId) ?? 0; return { scopeId, name: all.find((s) => s.id === scopeId)?.name ?? scopeId, balance: b, vatReserve: round2(reserve), commitments90Days: round2(commitments), available: round2(b - reserve - commitments) }; });
  return { rootScopeId, scopes: all, suggestedScopeIds, selectedScopeIds, balance, averageIncome, averageExpenses, transfers: visible.filter((t) => selected.has(t.sourceScopeId) || selected.has(t.destinationScopeId)), commitments: store.commitments.filter((c) => selected.has(c.scopeId)), assumptions: store.assumptions, transferCandidates, forecasts, forecast: forecasts.probable, positions, timeline: forecasts.probable.flatMap((m) => m.items).sort((a, b) => a.date.localeCompare(b.date)), ownership: ownershipRows, consolidation };
}

export async function createPortfolioTransfer(actor: RequestActor, input: PortfolioTransferInput): Promise<PortfolioTransfer> { const state = getVisiblePlatformState(actor), available = new Set(scopes(state).map((s) => s.id)); if (!available.has(input.sourceScopeId) || !available.has(input.destinationScopeId) || input.sourceScopeId === input.destinationScopeId) throw new Error("Choisis deux périmètres différents."); if (!Number.isFinite(input.amount) || input.amount <= 0 || !/^\d{4}-\d{2}-\d{2}$/.test(input.date) || !input.label?.trim()) throw new Error("Montant, date et libellé valides requis."); assertManage(actor, [input.sourceScopeId, input.destinationScopeId]); const store = readStore(), fee = Math.max(0, Number(input.fee) || 0); if (input.kind === "confirmed") { if (!input.sourceTransactionKey || !input.destinationTransactionKey) throw new Error("Les deux mouvements bancaires sont requis."); const tx = (await Promise.all([-1, 0, 1].map((i) => loadFinanceTransactions(actor, monthShift(input.date.slice(0, 7), i))))).flatMap((x) => x.transactions), source = tx.find((x) => x.key === input.sourceTransactionKey), destination = tx.find((x) => x.key === input.destinationTransactionKey); if (!source || !destination || source.amount_ttc >= 0 || destination.amount_ttc <= 0) throw new Error("Mouvements débit/crédit introuvables dans la fenêtre de trois mois."); const usedSource = store.transfers.filter((t) => t.sourceTransactionKey === input.sourceTransactionKey).reduce((s, t) => s + t.amount + (t.fee ?? 0), 0), usedDestination = store.transfers.filter((t) => t.destinationTransactionKey === input.destinationTransactionKey).reduce((s, t) => s + t.amount, 0); if (usedSource + input.amount + fee > Math.abs(source.amount_ttc) + .01 || usedDestination + input.amount > destination.amount_ttc + .01) throw new Error("Le montant partiel dépasse le solde disponible."); if (!source.allocations.some((a) => a.scopeId === input.sourceScopeId) || !destination.allocations.some((a) => a.scopeId === input.destinationScopeId)) throw new Error("Mouvements incompatibles avec les périmètres."); }
  const base = { ...input, treatment: input.treatment ?? "internal_transfer", amount: round2(input.amount), fee: round2(fee), label: input.label.trim() }, transfer: PortfolioTransfer = { ...base, frequency: input.kind === "planned" ? input.frequency ?? "once" : undefined, accountingLines: lines(base), id: `transfer_${randomUUID()}`, createdAt: new Date().toISOString() }; store.transfers.push(transfer); writeStore(store); return transfer; }
export function deletePortfolioTransfer(actor: RequestActor, id: string) { const store = readStore(), item = store.transfers.find((x) => x.id === id); if (!item) throw Object.assign(new Error("Transfert introuvable."), { code: "NOT_FOUND" }); assertManage(actor, [item.sourceScopeId, item.destinationScopeId]); store.transfers = store.transfers.filter((x) => x.id !== id); writeStore(store); }
export function savePortfolioAssumptions(actor: RequestActor, input: PortfolioAssumptions) { if (!actorHasGlobalAccess(actor)) throw Object.assign(new Error("Droits de gestion requis."), { code: "FORBIDDEN" }); for (const value of Object.values(input)) if (![value.revenueMultiplier, value.expenseMultiplier, value.safetyBuffer].every(Number.isFinite)) throw new Error("Hypothèses invalides."); const store = readStore(); store.assumptions = input; writeStore(store); return input; }
export function createPortfolioCommitment(actor: RequestActor, input: Omit<PortfolioCommitment, "id" | "createdAt">) { const state = getVisiblePlatformState(actor); if (!scopes(state).some((s) => s.id === input.scopeId)) throw new Error("Périmètre inaccessible."); assertManage(actor, [input.scopeId]); if (!input.label?.trim() || !/^\d{4}-\d{2}-\d{2}$/.test(input.dueDate) || !Number.isFinite(input.amount) || input.amount <= 0) throw new Error("Engagement invalide."); const item = { ...input, amount: round2(input.amount), label: input.label.trim(), id: `commitment_${randomUUID()}`, createdAt: new Date().toISOString() }; const store = readStore(); store.commitments.push(item); writeStore(store); return item; }
export function deletePortfolioCommitment(actor: RequestActor, id: string) { const store = readStore(), item = store.commitments.find((x) => x.id === id); if (!item) throw Object.assign(new Error("Engagement introuvable."), { code: "NOT_FOUND" }); assertManage(actor, [item.scopeId]); store.commitments = store.commitments.filter((x) => x.id !== id); writeStore(store); }
