import { useCallback, useEffect, useState } from "react";
import { api, apiUrl } from "../../api/client";
import { useAppStore } from "../../stores/appStore";
import type { TabType } from "../../types";

interface ClosingRecord { month: string; status: "closed" | "reopened"; closedAt: string; closedBy: string; fingerprint: string; transactionCount: number; reopenedAt?: string; reopenReason?: string }
interface ClosingData { month: string; transactionCount: number; completed: number; total: number; ready: boolean; closing?: ClosingRecord; steps: Array<{ id: string; label: string; status: "done" | "warning" | "blocked"; detail: string; count?: number; action?: TabType; filter?: string }> }
const TITLES: Partial<Record<TabType, string>> = { banking: "Connexion bancaire", transactions: "Transactions", vat: "TVA", reconcile: "Rapprochement", export: "Export" };

export function ClosingView() {
  const [month, setMonth] = useState(new Date().toISOString().slice(0, 7));
  const [data, setData] = useState<ClosingData | null>(null);
  const [history, setHistory] = useState<ClosingRecord[]>([]);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const openTab = useAppStore((state) => state.openTab);
  const load = useCallback(async () => { setLoading(true); try { const [state, records] = await Promise.all([api.get<ClosingData>("/closing", { params: { month } }), api.get<ClosingRecord[]>("/closing/history")]); setData(state.data); setHistory(records.data); } finally { setLoading(false); } }, [month]);
  useEffect(() => { void load(); const refresh = () => { if (document.visibilityState === "visible") void load(); }; document.addEventListener("visibilitychange", refresh); return () => document.removeEventListener("visibilitychange", refresh); }, [load]);
  function correct(step: ClosingData["steps"][number]) { if (!step.action) return; const path = new URLSearchParams({ month, ...(step.filter ? { filter: step.filter } : {}) }).toString(); openTab({ id: `${step.action}-${month}-${step.id}`, type: step.action, title: `${TITLES[step.action] ?? step.label} · ${month}`, path }); }
  async function close() { setBusy(true); setError(""); try { await api.post("/closing/close", { month }); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Clôture impossible"); } finally { setBusy(false); } }
  async function reopen() { const reason = window.prompt("Motif obligatoire de réouverture du mois :"); if (!reason) return; setBusy(true); setError(""); try { await api.post("/closing/reopen", { month, reason }); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Réouverture impossible"); } finally { setBusy(false); } }
  return <div className="h-full overflow-auto p-5"><div className="mx-auto max-w-4xl space-y-5">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-lg font-semibold">Clôture mensuelle guidée</h1><p className="mt-1 text-xs text-vscode-muted">Contrôle, verrouillage et historique vérifiable de chaque mois.</p></div><div className="flex gap-2"><button onClick={() => void load()} className="rounded border border-vscode-border px-3 py-1.5 text-xs">Actualiser</button><input type="month" value={month} onChange={(event) => setMonth(event.target.value)} className="rounded border border-vscode-border bg-vscode-panel px-3 py-1.5 text-sm" /></div></div>
    {error && <p className="rounded border border-red-800 bg-red-950/20 p-3 text-xs text-red-300">{error}</p>}
    {loading || !data ? <p className="py-16 text-center text-sm text-vscode-muted">Calcul des contrôles…</p> : <>
      <section className={`rounded-lg border p-4 ${data.closing ? "border-blue-700 bg-blue-950/20" : data.ready ? "border-green-700 bg-green-950/20" : "border-vscode-border bg-vscode-panel"}`}><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-semibold">{data.closing ? `🔒 Mois clôturé le ${new Date(data.closing.closedAt).toLocaleString("fr-FR")}` : data.ready ? "✓ Mois prêt à clôturer" : `${data.completed}/${data.total} contrôles terminés`}</p><p className="mt-1 text-xs text-vscode-muted">{data.transactionCount} opération(s) · {data.closing ? `empreinte ${data.closing.fingerprint.slice(0, 12)}…` : "les écritures restent modifiables"}</p></div><div className="flex gap-2">{(data.ready || data.closing) && <a href={`${apiUrl("accounting/package-month")}?month=${month}`} className="rounded border border-green-700 px-3 py-2 text-xs text-green-300">Télécharger le dossier mensuel</a>}{data.closing ? <button disabled={busy} onClick={() => void reopen()} className="rounded bg-amber-700 px-3 py-2 text-xs text-white disabled:opacity-40">Réouvrir avec un motif</button> : <button disabled={!data.ready || busy} onClick={() => void close()} className="rounded bg-green-700 px-3 py-2 text-xs text-white disabled:opacity-40">Clôturer définitivement le mois</button>}</div></div><div className="mt-3 h-2 overflow-hidden rounded bg-vscode-bg"><div className={`h-full ${data.ready ? "bg-green-500" : "bg-vscode-accent"}`} style={{ width: `${Math.round(data.completed / data.total * 100)}%` }} /></div></section>
      <div className="space-y-2">{data.steps.map((step) => <article key={step.id} className={`flex items-center gap-3 rounded-lg border p-3 ${step.status === "done" ? "border-green-800 bg-green-950/15" : step.status === "warning" ? "border-yellow-800 bg-yellow-950/15" : "border-red-800 bg-red-950/15"}`}><span>{step.status === "done" ? "✓" : step.status === "warning" ? "⚠" : "⛔"}</span><div className="min-w-0 flex-1"><p className="text-sm font-medium">{step.label}</p><p className="text-xs text-vscode-muted">{step.detail}</p></div>{step.action && step.status !== "done" && !data.closing && <button onClick={() => correct(step)} className="rounded bg-vscode-accent px-3 py-1.5 text-xs text-white">Corriger ce mois →</button>}{step.action === "export" && step.status === "done" && <button onClick={() => correct(step)} className="rounded bg-green-700 px-3 py-1.5 text-xs text-white">Dossier →</button>}</article>)}</div>
      {history.length > 0 && <section><h2 className="mb-2 text-sm font-semibold">Historique</h2><div className="space-y-1">{history.slice(0, 12).map((item, index) => <div key={`${item.month}-${item.closedAt}-${index}`} className="rounded border border-vscode-border bg-vscode-panel px-3 py-2 text-xs"><strong>{item.month}</strong> · {item.status === "closed" ? "clôturé" : `réouvert : ${item.reopenReason}`} · {new Date(item.closedAt).toLocaleDateString("fr-FR")}</div>)}</div></section>}
    </>}
  </div></div>;
}
