import {test,expect} from "@playwright/test";
import type {Ecosystem} from "../frontend/src/types/ecosystem";
test("two partners use one persisted ecosystem from personal bank movement to company accounting",async({page,browser},testInfo)=>{
 const errors:string[]=[];page.on("pageerror",e=>errors.push(e.message));
 const setup=await page.request.post("/api/auth/setup",{data:{username:"alice",displayName:"Alice",password:"test-password-123"}});expect(setup.status()).toBe(201);
 await page.goto("/");await page.getByLabel("Nom de l’espace").fill("Notre espace");await page.getByRole("button",{name:"Créer l’écosystème"}).click();await expect(page.getByRole("heading",{name:"Structure financière"})).toBeVisible();
 await page.getByRole("button",{name:"+ Ajouter",exact:true}).click();await page.getByRole("button",{name:"◯ Personne",exact:true}).click();await page.getByRole("dialog").getByLabel("Nom",{exact:true}).fill("Alice");await page.getByRole("dialog").getByRole("button",{name:"Ajouter",exact:true}).click();await expect(page.getByRole("dialog")).toHaveCount(0);
 const list=await(await page.request.get("/api/ecosystems")).json();const endpoint="/api/ecosystems/"+list[0].id;let state:Ecosystem=await(await page.request.get(endpoint)).json();const alice=state.entities[0].id;
 async function command(data:Record<string,unknown>){state=await(await page.request.get(endpoint)).json();const r=await page.request.post(endpoint+"/commands",{data:{revision:state.revision,...data}});expect(r.status(),await r.text()).toBe(200);state=await r.json();}
 for(const entity of [{id:"bob",kind:"person",name:"Bob"},{id:"studio",kind:"company",name:"Studio Alice",accountingEnabled:true},{id:"atelier",kind:"company",name:"Atelier Bob",accountingEnabled:true},...Array.from({length:6},(_,i)=>({id:"bank"+i,kind:"account",name:["Personnel Alice","Pro Alice","Personnel Bob","Pro Bob","Commun Charges","Commun Quotidien"][i]}))])await command({action:"entity",entity});
 for(const from of [alice,"bob"])await command({action:"relation",relation:{from,to:"bank4",kind:"holder"}});
 const invitation=await(await page.request.post("/api/auth/invite",{data:{role:"member",workspaceId:state.id}})).json();const second=await browser.newContext({baseURL:"http://localhost:5176"});expect((await second.request.post("/api/auth/invite/"+invitation.token+"/accept",{data:{username:"bob",displayName:"Bob",password:"test-password-123"}})).status()).toBe(201);const bob=await second.newPage();await bob.goto("/");await expect(bob.getByRole("heading",{name:"Structure financière"})).toBeVisible();
 const date=new Date().toISOString().slice(0,10);
 await page.reload();await expect(page.getByRole("heading",{name:"Structure financière"})).toBeVisible();await page.getByLabel("Périmètre actif").selectOption("bank0");
 await page.getByRole("button",{name:"Ouvrir les mouvements ↗",exact:true}).click();
 await page.getByRole("button",{name:"Importer",exact:true}).click();await page.getByLabel("Fichier",{exact:true}).setInputFiles({name:"bank.csv",mimeType:"text/csv",buffer:Buffer.from(`Date;Label;Amount\n${date};Achat mixte;-100`)});
 await page.getByRole("combobox",{name:"Colonne date",exact:true}).selectOption("Date");await page.getByRole("combobox",{name:"Colonne libellé",exact:true}).selectOption("Label");await page.getByRole("combobox",{name:"Colonne montant signé",exact:true}).selectOption("Amount");await page.getByRole("button",{name:"Prévisualiser",exact:true}).click();await page.getByRole("button",{name:"Confirmer l’import",exact:true}).click();await expect(page.getByText("Import terminé.",{exact:true})).toBeVisible();state=await(await page.request.get(endpoint)).json();const movement=state.movements[0];await page.getByRole("tab",{name:"Mouvements · Personnel Alice",exact:true}).click();
 await page.getByRole("button",{name:"Achat mixte ↗",exact:true}).click();await page.getByRole("button",{name:"Modifier les affectations"}).click();
 const dialog=page.getByRole("dialog");await dialog.getByLabel("Destination").selectOption("studio");await dialog.getByLabel("Montant signé EUR",{exact:true}).nth(1).fill("-70");await dialog.getByRole("button",{name:"+ Affectation"}).click();await dialog.getByLabel("Destination").nth(1).selectOption(alice);await dialog.getByLabel("Catégorie",{exact:true}).nth(0).fill("Matériel");await dialog.getByLabel("Catégorie",{exact:true}).nth(1).fill("Personnel");await dialog.getByRole("button",{name:"Enregistrer",exact:true}).click();await expect(page.getByRole("dialog")).toHaveCount(0);
 await page.getByRole("button",{name:"Ajouter / consulter les justificatifs"}).click();await page.getByRole("button",{name:"+ Document"}).click();await page.getByRole("dialog").getByLabel("Fichier").setInputFiles({name:"achat.pdf",mimeType:"application/pdf",buffer:Buffer.from("%PDF-1.4\n%%EOF")});await page.getByRole("dialog").getByRole("button",{name:"Enregistrer le document"}).click();await expect(page.getByRole("dialog")).toHaveCount(0);await expect(page.getByRole("button",{name:"achat.pdf",exact:true})).toBeVisible();
 await page.getByRole("tab",{name:"Mouvement · Personnel Alice",exact:true}).click();await page.getByRole("button",{name:"Ouvrir le traitement · Studio Alice ↗"}).click();await page.getByLabel("Catégorie",{exact:true}).selectOption("equipment");await page.getByLabel("Compte de contrepartie").fill("455100");await page.getByLabel("Libellé de contrepartie").fill("Avance Alice");await page.getByLabel("Code du journal").fill("OD");await page.getByLabel("Libellé du journal").fill("Opérations diverses");await page.getByRole("button",{name:"Valider le traitement"}).click();await expect(page.getByText("Traitement validé.",{exact:true})).toBeVisible();
 state=await(await second.request.get(endpoint)).json();expect(state.movements).toHaveLength(1);expect(state.movements[0].cents).toBe(-10000);expect(state.treatments[0].transaction.amount_ttc).toBe(-70);expect(state.treatments[0].transaction.status).toBe("validated");expect(state.documents).toHaveLength(1);
 await page.getByRole("button",{name:"Journal de l’entreprise ↗"}).click();await expect(page.getByText("455100",{exact:true})).toBeVisible();await page.getByLabel("Périmètre actif").selectOption("atelier");await expect(page.getByRole("tab",{name:"Journal · Studio Alice",exact:true})).toBeVisible();await page.getByRole("tab",{name:"Journal · Studio Alice",exact:true}).click();await expect(page.getByLabel("Périmètre actif")).toHaveValue("studio");
 await page.getByRole("button",{name:"⇄ Tous les flux",exact:true}).click();await expect(page.getByRole("heading",{name:"Flux financiers · Vue d’ensemble"})).toBeVisible();await page.screenshot({path:testInfo.outputPath("ecosystem-real-flow.png"),fullPage:true});
 expect((await second.request.get(endpoint+"/documents/"+state.documents[0].id+"/file")).status()).toBe(200);
 // The second member cannot change a validated source allocation.
 const conflict=await second.request.post(endpoint+"/commands",{data:{revision:state.revision,action:"movement",id:movement.id,expectedRevision:state.movements[0].revision,movement:{notes:"changed"}}});expect(conflict.status()).toBe(409);

 // Shared and company spreadsheets keep separate storage and preserve formulas.
 await page.getByRole("button",{name:"Analyses & Export",exact:true}).click();await page.getByRole("button",{name:"🧮 Tableaux",exact:true}).click();
 await page.getByRole("button",{name:"+ Nouveau",exact:true}).click();await page.getByPlaceholder("Nom…",{exact:true}).fill("Budget partagé");await page.getByRole("button",{name:"✓",exact:true}).click();
 const sheetPanel=page.getByRole("tabpanel",{name:"Tableaux · Vue d’ensemble",exact:true});
 const firstCell=sheetPanel.locator("tbody tr").first().locator("td").nth(1);await firstCell.click();
 const formula=sheetPanel.getByPlaceholder("=SUM(A1:A10)  •  =REVENUS_2025  •  =IF(A1>0,…)");await formula.fill("=SUM(1,2)");await formula.press("Enter");await expect(firstCell).toHaveText("3");
 await expect.poll(async()=>{const docs=await(await page.request.get(endpoint+"/tableaux/root")).json();const saved=await(await page.request.get(endpoint+"/tableaux/root/"+docs[0].id)).json();return saved.sheets[0].cells.A1?.value;}).toBe("=SUM(1,2)");
 await page.getByLabel("Périmètre actif").selectOption("studio");await page.getByRole("button",{name:"Analyses & Export",exact:true}).click();await page.getByRole("button",{name:"🧮 Tableaux",exact:true}).click();await expect(page.getByText("Aucun tableau.",{exact:true})).toBeVisible();
 await page.getByRole("button",{name:"+ Nouveau",exact:true}).click();await page.getByPlaceholder("Nom…",{exact:true}).fill("Prévision Studio");await page.getByRole("button",{name:"✓",exact:true}).click();await expect(page.getByRole("button",{name:"📄 Prévision Studio",exact:true})).toBeVisible();
 const workspaceId=state.entities.find(e=>e.id==="studio")!.workspaceId;expect((await(await page.request.get("/api/workspaces/"+workspaceId+"/spreadsheets")).json())[0].name).toBe("Prévision Studio");
 await page.getByRole("tab",{name:"Tableaux · Vue d’ensemble",exact:true}).click();await expect(firstCell).toHaveText("3");
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:testInfo.outputPath("ecosystem-real-mobile.png"),fullPage:true});expect(errors).toEqual([]);await second.close();
});
