import { useMemo, useState } from "react";
import type { PendingReceipt, ReceiptOcrProposal } from "../../api/client";
import type { Category } from "../../types";
import { useCategoryCatalog } from "../../hooks/useCategoryCatalog";
import { LocalizedNumberInput } from "../Common/LocalizedNumberInput";

const round2 = (value: number) => Math.round(value * 100) / 100;

export function PendingReceiptEditor({ receipt, onSave, onClose }: { receipt: PendingReceipt; onSave: (proposal: ReceiptOcrProposal) => Promise<void>; onClose: () => void }) {
  const { categories } = useCategoryCatalog();
  const initial = receipt.ocr.proposal ?? { supplier: "", amountHt: 0, amountVat: 0, amountTtc: 0, category: "misc" as Category, confidence: "low" as const, vatSplits: [] };
  const [value, setValue] = useState<ReceiptOcrProposal>(structuredClone(initial)); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [showRaw, setShowRaw] = useState(false);
  const vatTotal = useMemo(() => round2(value.vatSplits.reduce((sum, row) => sum + (row.amountVat ?? row.amountTtc - row.amountTtc / (1 + row.rate / 100)), 0)), [value.vatSplits]);
  const splitTotal = useMemo(() => round2(value.vatSplits.reduce((sum, row) => sum + row.amountTtc, 0)), [value.vatSplits]);
  function patchSplit(index: number, patch: Partial<ReceiptOcrProposal["vatSplits"][number]>) { setValue((current) => ({ ...current, vatSplits: current.vatSplits.map((row, rowIndex) => rowIndex === index ? { ...row, ...patch } : row) })); }
  async function save() { setError(""); if (!value.supplier.trim()) return setError("Le fournisseur est obligatoire."); if (value.amountTtc <= 0) return setError("Le TTC doit être supérieur à zéro."); if (value.vatSplits.length && Math.abs(splitTotal - value.amountTtc) >= 0.02) return setError("La ventilation TVA doit être égale au TTC."); setSaving(true); try { await onSave({ ...value, amountVat: value.vatSplits.length ? vatTotal : round2(value.amountTtc - value.amountHt), confidence: "high" }); } catch (caught) { setError(caught instanceof Error ? caught.message : "Enregistrement impossible"); } finally { setSaving(false); } }
  return <div className="fixed inset-0 z-50 overflow-y-auto bg-black/75 p-3" role="dialog" aria-modal="true"><div className="mx-auto my-4 max-w-3xl rounded-lg border border-vscode-border bg-vscode-panel p-5 shadow-2xl"><div className="flex justify-between"><div><h2 className="font-semibold">Vérifier le justificatif</h2><p className="text-xs text-vscode-muted">La proposition automatique est conservée séparément de tes corrections.</p></div><button onClick={onClose}>×</button></div>
    <div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-xs">Fournisseur<input value={value.supplier} onChange={(event) => setValue({ ...value, supplier: event.target.value })} className="mt-1 w-full rounded border border-vscode-border bg-vscode-bg p-2" /></label><label className="text-xs">Référence<input value={value.invoiceRef ?? ""} onChange={(event) => setValue({ ...value, invoiceRef: event.target.value })} className="mt-1 w-full rounded border border-vscode-border bg-vscode-bg p-2" /></label><label className="text-xs">Date<input type="date" value={value.date ?? ""} onChange={(event) => setValue({ ...value, date: event.target.value })} className="mt-1 w-full rounded border border-vscode-border bg-vscode-bg p-2" /></label><label className="text-xs">Catégorie<select value={value.category} onChange={(event) => setValue({ ...value, category: event.target.value as Category })} className="mt-1 w-full rounded border border-vscode-border bg-vscode-bg p-2">{categories.map((category) => <option key={category.id} value={category.id}>{category.label}</option>)}</select></label><label className="text-xs">Total HT<LocalizedNumberInput value={value.amountHt} onValueChange={(amountHt) => setValue({ ...value, amountHt })} className="mt-1 w-full rounded border border-vscode-border bg-vscode-bg p-2" /></label><label className="text-xs">Total TTC<LocalizedNumberInput value={value.amountTtc} onValueChange={(amountTtc) => setValue({ ...value, amountTtc })} className="mt-1 w-full rounded border border-vscode-border bg-vscode-bg p-2" /></label></div>
    <div className="mt-4"><div className="flex justify-between"><h3 className="text-sm font-semibold">Ventilation TVA</h3><button onClick={() => setValue((current) => ({ ...current, vatSplits: [...current.vatSplits, { rate: 0, amountTtc: Math.max(0, round2(current.amountTtc - splitTotal)) }] }))} className="text-xs text-vscode-accent">＋ Ajouter un taux</button></div>{value.vatSplits.map((row, index) => <div key={index} className="mt-2 flex items-center gap-2"><select value={row.rate} onChange={(event) => patchSplit(index, { rate: Number(event.target.value) })} className="rounded border border-vscode-border bg-vscode-bg p-2 text-xs">{[0, 2.1, 5.5, 10, 20].map((rate) => <option key={rate} value={rate}>{rate} %</option>)}</select><LocalizedNumberInput aria-label={`TTC TVA ${index + 1}`} value={row.amountTtc} onValueChange={(amountTtc) => patchSplit(index, { amountTtc })} className="w-32 rounded border border-vscode-border bg-vscode-bg p-2 text-xs" /><span className="text-xs text-vscode-muted">TVA {round2(row.amountTtc - row.amountTtc / (1 + row.rate / 100)).toFixed(2)} €</span><button onClick={() => setValue((current) => ({ ...current, vatSplits: current.vatSplits.filter((_, i) => i !== index) }))}>×</button></div>)}<p className={`mt-2 text-xs ${!value.vatSplits.length || Math.abs(splitTotal - value.amountTtc) < 0.02 ? "text-green-400" : "text-amber-400"}`}>{value.vatSplits.length ? `Ventilation ${splitTotal.toFixed(2)} € · TVA ${vatTotal.toFixed(2)} €` : "Aucune ventilation — saisie libre HT/TTC"}</p></div>
    {receipt.ocr.rawText && <div className="mt-4"><button onClick={() => setShowRaw(!showRaw)} className="text-xs text-vscode-accent">{showRaw ? "Masquer" : "Afficher"} le texte OCR brut</button>{showRaw && <pre className="mt-2 max-h-48 overflow-auto whitespace-pre-wrap rounded bg-vscode-bg p-3 text-[10px]">{receipt.ocr.rawText}</pre>}</div>}{receipt.ocr.automaticProposal && receipt.ocr.validatedAt && <p className="mt-3 text-xs text-blue-300">Correction humaine enregistrée ; la proposition OCR initiale reste conservée.</p>}{error && <p className="mt-3 text-xs text-red-400">{error}</p>}<div className="mt-5 flex justify-end gap-2"><button onClick={onClose} className="rounded border border-vscode-border px-3 py-2 text-xs">Annuler</button><button disabled={saving} onClick={() => void save()} className="rounded bg-vscode-accent px-3 py-2 text-xs text-white disabled:opacity-40">Enregistrer la vérification</button></div>
  </div></div>;
}
