import { useState } from "react";
import type { ReceiptOcrProposal } from "../../api/client";
import type { Category, Transaction } from "../../types";

const CATEGORIES: Category[] = ["hosting", "software", "salary", "travel", "restaurant", "food", "taxes", "equipment", "subscription", "rent", "legal", "insurance", "misc"];
const VAT_RATES = [0, 2.1, 5.5, 10, 20];
interface Props { transaction: Transaction; proposal: ReceiptOcrProposal; onApply: (values: { category: Category; invoiceRef?: string; vatSplits: Array<{ rate: number; amountTtc: number }> }) => Promise<void>; onClose: () => void }

export function ReceiptOcrDialog({ transaction, proposal, onApply, onClose }: Props) {
  const bankTotal = Math.abs(transaction.amount_ttc); const initial = proposal.vatSplits.length ? proposal.vatSplits : [{ rate: 0, amountTtc: bankTotal }];
  const [category, setCategory] = useState<Category>(proposal.category); const [invoiceRef, setInvoiceRef] = useState(proposal.invoiceRef ?? "");
  const [splits, setSplits] = useState(initial); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const splitTotal = Math.round(splits.reduce((sum, split) => sum + split.amountTtc, 0) * 100) / 100;
  const balanced = Math.abs(splitTotal - bankTotal) < 0.01; const receiptMatches = !proposal.amountTtc || Math.abs(proposal.amountTtc - bankTotal) < 0.02;
  const estimatedVat = splits.reduce((sum, split) => sum + split.amountTtc - split.amountTtc / (1 + split.rate / 100), 0);
  function patch(index: number, changes: Partial<(typeof splits)[number]>) { setSplits((current) => current.map((split, row) => row === index ? { ...split, ...changes } : split)); }
  async function apply() { if (!balanced) return; setSaving(true); setError(""); try { await onApply({ category, invoiceRef: invoiceRef.trim() || undefined, vatSplits: splits }); } catch (caught) { setError(caught instanceof Error ? caught.message : "Application impossible"); setSaving(false); } }
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4" role="dialog" aria-modal="true" aria-label="Résultat OCR du justificatif"><div className="w-full max-w-xl rounded-lg border border-vscode-border bg-vscode-panel p-5 shadow-2xl">
    <div className="flex justify-between gap-3"><div><h2 className="text-sm font-semibold text-vscode-text">Justificatif analysé — vérification requise</h2><p className="text-xs text-vscode-muted mt-1">{proposal.supplier || "Fournisseur inconnu"}{proposal.date ? ` · ${proposal.date}` : ""} · confiance {proposal.confidence}</p></div><button onClick={onClose} aria-label="Fermer" className="text-vscode-muted">×</button></div>
    {!receiptMatches && <p className="mt-3 rounded border border-amber-700 bg-amber-900/20 px-3 py-2 text-xs text-amber-300">Le ticket indique {proposal.amountTtc.toFixed(2)} €, mais la banque indique {bankTotal.toFixed(2)} €. Vérifie qu’il s’agit du bon justificatif.</p>}
    <div className="grid grid-cols-2 gap-3 mt-4"><label className="text-[10px] text-vscode-muted">Catégorie<select value={category} onChange={(event) => setCategory(event.target.value as Category)} className="block w-full mt-1 rounded border border-vscode-border bg-vscode-bg px-2 py-1.5 text-xs text-vscode-text">{CATEGORIES.map((value) => <option key={value}>{value}</option>)}</select></label><label className="text-[10px] text-vscode-muted">Référence de la note<input value={invoiceRef} onChange={(event) => setInvoiceRef(event.target.value)} className="block w-full mt-1 rounded border border-vscode-border bg-vscode-bg px-2 py-1.5 text-xs text-vscode-text"/></label></div>
    <div className="mt-4"><div className="flex justify-between"><h3 className="text-xs font-semibold text-vscode-text">TVA proposée</h3><span className="text-xs text-vscode-muted">TVA estimée {estimatedVat.toFixed(2)} €</span></div><div className="space-y-2 mt-2">{splits.map((split, index) => <div key={index} className="flex items-center gap-2"><select aria-label={`Taux TVA OCR ${index + 1}`} value={split.rate} onChange={(event) => patch(index, { rate: Number(event.target.value) })} className="rounded border border-vscode-border bg-vscode-bg px-2 py-1 text-xs text-vscode-text">{VAT_RATES.map((rate) => <option key={rate} value={rate}>{rate} %</option>)}</select><label className="flex items-center gap-1 text-xs text-vscode-muted">TTC<input aria-label={`Montant TTC OCR ${index + 1}`} type="number" min="0" step="0.01" value={split.amountTtc} onChange={(event) => patch(index, { amountTtc: Number(event.target.value) || 0 })} className="w-28 rounded border border-vscode-border bg-vscode-bg px-2 py-1 text-right text-vscode-text"/>€</label><button onClick={() => setSplits((current) => current.filter((_, row) => row !== index))} disabled={splits.length === 1} className="text-vscode-muted hover:text-red-400 disabled:opacity-30">×</button></div>)}</div><div className="flex items-center gap-3 mt-2"><button onClick={() => setSplits((current) => [...current, { rate: 20, amountTtc: Math.max(0, Math.round((bankTotal - splitTotal) * 100) / 100) }])} className="text-xs text-vscode-accent">＋ Ajouter un taux</button><span className={`text-xs ${balanced ? "text-green-400" : "text-amber-400"}`}>{balanced ? "Total conforme à la banque" : `Total ${splitTotal.toFixed(2)} € au lieu de ${bankTotal.toFixed(2)} €`}</span></div></div>
    {error && <p role="alert" className="mt-3 text-xs text-red-400">{error}</p>}<div className="flex justify-between items-center mt-5"><button onClick={onClose} className="text-xs text-vscode-muted hover:text-vscode-text">Fermer et saisir manuellement</button><button onClick={() => void apply()} disabled={!balanced || saving} className="rounded bg-vscode-accent px-4 py-2 text-xs text-white disabled:opacity-40">{saving ? "Application…" : "Appliquer la TVA proposée"}</button></div>
  </div></div>;
}
