import {useState} from "react";
import {useLive,errorText} from "./liveStore";
import {prototypeId,scopeName,type ScopeTab} from "./model";
import {resolveVariables,type FinancialVariable} from "../../../../backend/src/domain/ecosystemVariables";
export function LiveVariables({spec}:{spec:ScopeTab}){
 const {data:s,command}=useLive();const [edit,setEdit]=useState<FinancialVariable|null>(null),[error,setError]=useState("");
 const rows=resolveVariables(s!,s!.variables??[]);
 return <div className="eco-work"><h1>Variables financières</h1><p>Valeurs en EUR. Les références utilisent des identifiants stables ; renommer une personne ou une variable ne change pas les formules. La période est propre à la variable.</p><button onClick={()=>setEdit({id:prototypeId(),name:"",scope:spec.scope,metric:"expenses",period:"current-month"})}>+ Variable</button>
 <table><thead><tr><th>Nom / source</th><th>Référence tableur</th><th>Période</th><th>Valeur</th><th>Actions</th></tr></thead><tbody>{rows.map(v=><tr key={v.id}><td>{v.name}<small> · {scopeName(v.scope)}</small></td><td><code>{v.symbol}</code></td><td>{v.period||"Toutes les dates"}</td><td>{v.error?<span role="alert">{v.error}</span>:v.value?.toLocaleString("fr-FR",{style:"currency",currency:"EUR"})}<small> · Calcul : {v.calculatedAt}</small></td><td><button onClick={()=>setEdit({...s!.variables!.find(x=>x.id===v.id)!})}>Modifier</button><button onClick={()=>void command({action:"delete-variable",id:v.id}).catch(e=>setError(errorText(e)))}>Supprimer</button></td></tr>)}</tbody></table>
 {edit&&<form className="eco-settings-form" onSubmit={async e=>{e.preventDefault();try{await command({action:"variable",variable:edit});setEdit(null);setError("");}catch(e){setError(errorText(e));}}}><h2>Définition</h2><label>Nom<input required value={edit.name} onChange={e=>setEdit({...edit,name:e.target.value})}/></label><label>Source<select aria-label="Source" value={edit.scope} onChange={e=>setEdit({...edit,scope:e.target.value})}><option value="root">Vue d’ensemble</option><option value="common">Vie commune</option><option value="unassigned">Non affecté</option>{s!.entities.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><label>Indicateur<select aria-label="Indicateur" value={edit.metric} onChange={e=>setEdit({...edit,metric:e.target.value as FinancialVariable["metric"]})}><option value="income">Revenus affectés TTC</option><option value="expenses">Dépenses nettes affectées TTC</option><option value="net">Net des affectations TTC</option><option value="balance">Solde bancaire de trésorerie</option><option value="bank_debits">Débits bancaires (virements inclus)</option><option value="bank_credits">Crédits bancaires (virements inclus)</option><option value="accounting_revenue_ht">Revenus comptables HT validés</option><option value="accounting_expenses_ht">Charges comptables HT validées</option><option value="vat">TVA nette des traitements validés</option><option value="forecast_expenses">Échéances futures de référence TTC</option></select></label><label>Période<input placeholder="2026, 2026-09, current-month, current-year ou vide" value={edit.period} onChange={e=>setEdit({...edit,period:e.target.value})}/></label><label>Catégorie (facultative)<input value={edit.category??""} onChange={e=>setEdit({...edit,category:e.target.value||undefined})}/></label><label>Formule calculée (facultative)<input value={edit.formula??""} onChange={e=>setEdit({...edit,formula:e.target.value})}/></label><p>Opérateurs : + − * / et parenthèses. Cliquez une variable pour insérer sa référence.</p>{rows.filter(v=>v.id!==edit.id).map(v=><button type="button" key={v.id} onClick={()=>setEdit({...edit,formula:(edit.formula??"")+"{"+v.id+"}"})}>{v.name}</button>)}<button>Enregistrer</button><button type="button" onClick={()=>setEdit(null)}>Annuler</button></form>}{error&&<p role="alert">{error}</p>}</div>;
}
