import {useTabState} from "./tabContext";
import {useEffect,useMemo,useState,useRef} from "react";
import {useLive,liveRequest,errorText,liveUrl} from "./liveStore";
import {Dialog} from "./Structure";
import {money,openScope,scopeName,prototypeId,ROOT,type ScopeTab} from "./model";
import type {Ecosystem,Movement,Allocation} from "../../types/ecosystem";
import {createWorkspaceApi} from "../../api/client";
import type {CategoryDefinition} from "../../types";
export const today=()=>new Date().toISOString().slice(0,10);
export function scopedMovements(s:Ecosystem,scope:string){
 const entity=s.entities.find(e=>e.id===scope),accounts=new Set(s.relations.filter(r=>r.kind==="holder"&&r.from===scope||r.kind==="usage"&&r.to===scope).map(r=>r.kind==="holder"?r.to:r.from));
 return s.movements.filter(m=>!m.deleted&&(scope===ROOT||m.accountId===scope||m.allocations.some(a=>a.target===scope)||accounts.has(m.accountId)||entity?.kind==="person"&&s.relations.some(r=>r.kind==="activity"&&r.from===scope&&m.allocations.some(a=>a.target===r.to))));
}
export function scopedAllocations(s:Ecosystem,m:Movement,scope:string){return scope===ROOT||s.entities.some(e=>e.id===scope&&e.kind==="account")?m.allocations:m.allocations.filter(a=>a.target===scope);}
export function AllocationFields({lines,setLines,total}:{lines:Allocation[];setLines:(a:Allocation[])=>void;total:number}){
 const s=useLive(x=>x.data)!;const options=[{id:"unassigned",name:"Non affecté"},{id:"common",name:"Vie commune"},...s.entities.filter(e=>e.kind!=="account"&&!e.archived)];
 return <fieldset><legend>Affectations · {money(lines.reduce((n,a)=>n+a.cents,0))} / {money(total)}</legend>{lines.map((a,i)=><div className="eco-toolbar" key={a.id}>
 <label>Destination<select value={a.target} onChange={e=>setLines(lines.map((x,j)=>j===i?{...x,target:e.target.value}:x))}>{options.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label>
 <label>Catégorie<input required value={a.category} onChange={e=>setLines(lines.map((x,j)=>j===i?{...x,category:e.target.value}:x))}/></label>
 <label>Montant signé EUR<input type="number" step=".01" required value={a.cents/100} onChange={e=>setLines(lines.map((x,j)=>j===i?{...x,cents:Math.round(Number(e.target.value)*100)}:x))}/></label><button type="button" disabled={lines.length===1} onClick={()=>setLines(lines.filter((_,j)=>j!==i))}>Retirer</button>
 </div>)}<button type="button" onClick={()=>setLines([...lines,{id:prototypeId(),target:"unassigned",category:"À classer",cents:total-lines.reduce((n,a)=>n+a.cents,0)}])}>+ Affectation</button></fieldset>;
}
export function MovementForm({movement,scope,onClose}:{movement?:Movement;scope:string;onClose:()=>void}){
 const {data:s,command,busy}=useLive();const accounts=s!.entities.filter(e=>e.kind==="account"&&!e.archived);
 const account=accounts.find(a=>a.id===scope)??accounts[0];
 const [v,setV]=useState<Partial<Movement>>(movement?structuredClone(movement):{accountId:account?.id??"",date:today(),label:"",cents:0,nature:"expense",notes:"",reviewed:false,allocations:[{id:prototypeId(),target:account?.defaultTarget??"unassigned",category:"À classer",cents:0}]});const [error,setError]=useState("");
 return <Dialog title={movement?"Modifier le mouvement":"Ajouter un mouvement"} onClose={onClose}><form onSubmit={async e=>{e.preventDefault();try{await command({action:"movement",id:movement?.id,expectedRevision:movement?.revision,movement:v});onClose();}catch(e){setError(errorText(e));}}}>
 <label>Compte<select required disabled={!!movement?.source} value={v.accountId} onChange={e=>setV({...v,accountId:e.target.value})}>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>
 <label>Date<input type="date" required disabled={!!movement?.source} value={v.date} onChange={e=>setV({...v,date:e.target.value})}/></label>
 <label>Libellé<input required value={v.label} onChange={e=>setV({...v,label:e.target.value})}/></label>
 <label>Montant signé EUR<input type="number" step=".01" required disabled={!!movement?.source} value={v.cents!/100} onChange={e=>{const cents=Math.round(Number(e.target.value)*100);setV({...v,cents,allocations:v.allocations!.length===1?[{...v.allocations![0],cents}]:v.allocations});}}/></label>
 <label>Nature<select value={v.nature} onChange={e=>setV({...v,nature:e.target.value as Movement["nature"]})}><option value="expense">Dépense</option><option value="income">Revenu</option><option value="refund">Remboursement de dépense</option></select></label>
 <AllocationFields lines={v.allocations!} total={v.cents!} setLines={allocations=>setV({...v,allocations})}/>
 <label>Étiquettes (séparées par une virgule)<input value={(v.tags??[]).join(", ")} onChange={e=>setV({...v,tags:e.target.value.split(",").map(t=>t.trim()).filter(Boolean)})}/></label>
 <label>Notes<textarea value={v.notes} onChange={e=>setV({...v,notes:e.target.value})}/></label>
 <label className="eco-inline"><input type="checkbox" checked={v.reviewed} onChange={e=>setV({...v,reviewed:e.target.checked})}/> Vérifié</label>
 {error&&<p role="alert">{error}</p>}<footer><button type="button" onClick={onClose}>Annuler</button><button disabled={busy||!accounts.length} className="eco-primary">Enregistrer</button></footer></form></Dialog>;
}
export function LiveMovements({spec}:{spec:ScopeTab}){
 const {data:s,command}=useLive();const [period,setPeriod]=useTabState("period",spec.period??today().slice(0,7)),[search,setSearch]=useTabState("search",""),[review,setReview]=useTabState("review",false),[adding,setAdding]=useState(false),[selected,setSelected]=useState<string[]>([]),[bulk,setBulk]=useState(false),[bulkTarget,setBulkTarget]=useState("unassigned"),[bulkCategory,setBulkCategory]=useState(""),[bulkError,setBulkError]=useState("");
 const selectedRevisions=useRef(new Map<string,number>());
 const [accountFilter,setAccountFilter]=useTabState("accountFilter",""),[targetFilter,setTargetFilter]=useTabState("targetFilter",""),[categoryFilter,setCategoryFilter]=useTabState("categoryFilter",""),[tagFilter,setTagFilter]=useTabState("tagFilter",""),[natureFilter,setNatureFilter]=useTabState("natureFilter",""),[min,setMin]=useTabState("min",""),[max,setMax]=useTabState("max","");
 const rows=scopedMovements(s!,spec.scope).filter(m=>(!period||m.date.startsWith(period))&&(!spec.record||m.id===spec.record)&&(m.label+" "+m.notes).toLowerCase().includes(search.toLowerCase())&&(!accountFilter||m.accountId===accountFilter)&&(!targetFilter||m.allocations.some(a=>a.target===targetFilter))&&(!categoryFilter||m.allocations.some(a=>a.category===categoryFilter))&&(!tagFilter||m.tags?.includes(tagFilter))&&(!natureFilter||m.nature===natureFilter)&&(min===""||m.cents>=Math.round(Number(min)*100))&&(max===""||m.cents<=Math.round(Number(max)*100))&&(!review||!m.reviewed||m.sourceChange));
 return <div className="eco-work"><div className="eco-heading"><h1>Mouvements · {scopeName(spec.scope)}</h1><button onClick={()=>setAdding(true)}>+ Mouvement</button></div>
 <div className="eco-toolbar"><label>Période<input type="month" value={period} onChange={e=>setPeriod(e.target.value)}/></label><button onClick={()=>setPeriod("")}>Toutes les dates</button><label>Rechercher<input value={search} onChange={e=>setSearch(e.target.value)}/></label><label className="eco-inline"><input type="checkbox" checked={review} onChange={e=>setReview(e.target.checked)}/> À vérifier</label><button onClick={()=>openScope({view:"placeholder",scope:spec.scope,label:"Importer un relevé"})}>Importer</button><button onClick={()=>openScope({view:"placeholder",scope:spec.scope,label:"Virements"})}>Virements</button></div>
 <details><summary>Filtres avancés</summary><div className="eco-toolbar"><label>Compte<select value={accountFilter} onChange={e=>setAccountFilter(e.target.value)}><option value="">Tous</option>{s!.entities.filter(e=>e.kind==="account").map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><label>Affectation<select value={targetFilter} onChange={e=>setTargetFilter(e.target.value)}><option value="">Toutes</option><option value="common">Vie commune</option><option value="unassigned">Non affecté</option>{s!.entities.filter(e=>e.kind!=="account").map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><label>Catégorie financière<select value={categoryFilter} onChange={e=>setCategoryFilter(e.target.value)}><option value="">Toutes</option>{[...new Set(s!.movements.flatMap(m=>m.allocations.map(a=>a.category)))].sort().map(c=><option key={c}>{c}</option>)}</select></label><label>Étiquette<select value={tagFilter} onChange={e=>setTagFilter(e.target.value)}><option value="">Toutes</option>{[...new Set(s!.movements.flatMap(m=>m.tags??[]))].sort().map(t=><option key={t}>{t}</option>)}</select></label><label>Nature<select value={natureFilter} onChange={e=>setNatureFilter(e.target.value)}><option value="">Toutes</option><option value="income">Revenu</option><option value="expense">Dépense</option><option value="refund">Remboursement</option></select></label><label>Minimum signé EUR<input type="number" step=".01" value={min} onChange={e=>setMin(e.target.value)}/></label><label>Maximum signé EUR<input type="number" step=".01" value={max} onChange={e=>setMax(e.target.value)}/></label></div></details>
 {selected.length>0&&<div className="eco-toolbar"><button onClick={()=>void command({action:"bulk-movement",items:selected.map(id=>({id,revision:selectedRevisions.current.get(id)})),reviewed:true}).then(()=>setSelected([])).catch(()=>undefined)}>Marquer la sélection vérifiée ({selected.length})</button><button onClick={()=>setBulk(true)}>Affecter la sélection</button></div>}
 {bulk&&<Dialog title="Affecter la sélection" onClose={()=>setBulk(false)}><form onSubmit={async e=>{e.preventDefault();try{await command({action:"bulk-movement",items:selected.map(id=>({id,revision:selectedRevisions.current.get(id)})),target:bulkTarget,category:bulkCategory});setBulk(false);setSelected([]);}catch(e){setBulkError(errorText(e));}}}><p>Remplacer les affectations de {selected.length} mouvements par une affectation complète. Les virements et traitements validés doivent être retirés de la sélection.</p><label>Destination<select value={bulkTarget} onChange={e=>setBulkTarget(e.target.value)}><option value="unassigned">Non affecté</option><option value="common">Vie commune</option>{s!.entities.filter(e=>e.kind!=="account"&&!e.archived).map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><label>Catégorie<input required value={bulkCategory} onChange={e=>setBulkCategory(e.target.value)}/></label>{bulkError&&<p role="alert">{bulkError}</p>}<button>Confirmer l’affectation</button></form></Dialog>}
 <div className="eco-table-wrap"><table><thead><tr><th>Sélection</th><th>Date</th><th>Mouvement</th><th>Compte</th><th>Montant</th><th>État</th></tr></thead><tbody>{rows.map(m=><tr key={m.id}><td><input aria-label={"Sélectionner "+m.label} type="checkbox" checked={selected.includes(m.id)} onChange={e=>{if(e.target.checked)selectedRevisions.current.set(m.id,m.revision);else selectedRevisions.current.delete(m.id);setSelected(e.target.checked?[...selected,m.id]:selected.filter(id=>id!==m.id));}}/></td><td>{m.date}</td><td><button className="eco-text" onClick={()=>openScope({view:"movement",scope:m.accountId,record:m.id,period})}>{m.label} ↗</button></td><td>{scopeName(m.accountId)}</td><td>{money(m.cents)}</td><td>{m.duplicateCandidates?.length?"Doublon à confirmer":m.pending?"En attente bancaire":m.sourceChange?"Correction bancaire à vérifier":m.reviewed?"Vérifié":"À vérifier"}</td></tr>)}</tbody></table>{!rows.length&&<p className="eco-empty">Aucun mouvement pour ces filtres.</p>}</div>
 {adding&&<MovementForm scope={spec.scope} onClose={()=>setAdding(false)}/>}</div>;
}
export function LiveMovement({spec}:{spec:ScopeTab}){
 const {data:s,command}=useLive();const [edit,setEdit]=useState(false);const m=s!.movements.find(m=>m.id===spec.record);if(!m)return <p className="eco-empty">Mouvement introuvable.</p>;
 const treatments=s!.treatments.filter(t=>t.movementId===m.id),documents=s!.documents.filter(d=>d.movementIds.includes(m.id));
 return <div className="eco-work"><h1>{m.label}</h1><div className="eco-big-amount">{money(m.cents)}</div><p>{m.date} · {scopeName(m.accountId)}</p><p>{m.notes}</p>
 <div className="eco-actions"><button onClick={()=>setEdit(true)}>Modifier les affectations</button><button onClick={()=>openScope({view:"documents",scope:m.accountId,record:m.id})}>Ajouter / consulter les justificatifs</button><button onClick={()=>openScope({view:"transactions",scope:m.accountId,period:spec.period})}>Mouvements du compte ↗</button><button onClick={()=>openScope({view:"flows",scope:ROOT,period:spec.period})}>Vue d’ensemble ↗</button></div>
 {!!m.duplicateCandidates?.length&&<section><h2>Doublon possible — exclu des totaux jusqu’à confirmation</h2>{m.duplicateCandidates.map(id=>{const other=s!.movements.find(x=>x.id===id);return other&&<p key={id}>{other.date} · {other.label} · {money(other.cents)} <button onClick={()=>void command({action:"duplicate",id:m.id,expectedRevision:m.revision,keepId:id}).catch(()=>undefined)}>Rattacher à ce mouvement existant</button></p>;})}<button onClick={()=>void command({action:"duplicate",id:m.id,expectedRevision:m.revision}).catch(()=>undefined)}>Conserver comme opération distincte</button></section>}
 {m.sourceChange&&<section><h2>Correction signalée par la banque</h2><p>{m.sourceChange.date} · {m.sourceChange.label} · {money(m.sourceChange.cents)} {m.sourceChange.deleted?"(retiré par la banque)":""}</p><button onClick={()=>void command({action:"source-change",id:m.id,expectedRevision:m.revision}).catch(()=>undefined)}>Accepter la correction</button></section>}
 <h2>Affectations</h2>{m.allocations.map(a=><div key={a.id} className="eco-allocation"><span>{a.target===ROOT?"Vie commune":scopeName(a.target)} · {a.category}</span><strong>{money(a.cents)}</strong></div>)}
 <h2>Traitements professionnels</h2>{treatments.map(t=><p key={t.transaction.id}><button onClick={()=>openScope({view:"accounting",scope:t.companyId,record:t.transaction.id,period:spec.period})}>Ouvrir le traitement · {scopeName(t.companyId)} ↗</button> {t.transaction.status}</p>)}{!treatments.length&&<p>Les affectations à une entreprise configurée créent un traitement à vérifier.</p>}
 <h2>Justificatifs</h2>{documents.map(d=><p key={d.id}><a target="_blank" rel="noreferrer" href={liveUrl("documents/"+d.id+"/file")}>{d.name}</a></p>)}
 <button onClick={()=>{if(confirm("Retirer ce mouvement ? Son historique sera conservé."))void command({action:"movement",id:m.id,expectedRevision:m.revision,movement:{deleted:true}}).catch(()=>undefined);}}>Retirer le mouvement</button>
 {edit&&<MovementForm movement={m} scope={m.accountId} onClose={()=>setEdit(false)}/>}</div>;
}
export function LiveTreatment({spec}:{spec:ScopeTab}){
 const {data:s,load,command}=useLive();const treatment=s!.treatments.find(t=>t.transaction.id===spec.record);const company=s!.entities.find(e=>e.id===spec.scope);
 const client=useMemo(()=>createWorkspaceApi(company?.workspaceId??""),[company?.workspaceId]);const [categories,setCategories]=useState<CategoryDefinition[]>([]);const [error,setError]=useState("");
 const [v,setV]=useState(treatment?.transaction);useEffect(()=>{client.fetchCategories().then(setCategories).catch(e=>setError(errorText(e)));},[client]);
 if(!treatment||!v)return <p className="eco-empty">Traitement introuvable.</p>;
 const m=s!.movements.find(m=>m.id===treatment.movementId),locked=treatment.transaction.status==="validated";
 const settlement=v.settlement??{accountNumber:"",label:"",journalCode:"",journalLabel:"",payerId:m?.accountId};
 return <div className="eco-work"><h1>Traitement · {company?.name}</h1><h2>{v.label} · {money(Math.round(v.amount_ttc*100))}</h2>{m&&<p>Payé depuis {scopeName(m.accountId)} · <button onClick={()=>openScope({view:"movement",scope:m.accountId,record:m.id,period:spec.period})}>Mouvement bancaire ↗</button></p>}
 {locked?<><p>Traitement validé.</p><button onClick={()=>void command({action:"reopen",id:v.id}).then(()=>setV(useLive.getState().data!.treatments.find(t=>t.transaction.id===v.id)!.transaction)).catch(()=>undefined)}>Rouvrir le traitement</button></>:<form className="eco-settings-form" onSubmit={async e=>{e.preventDefault();try{await client.updateTransaction(v.id,{...v,status:"validated",reconciled:true,settlement});await load(s!.id);}catch(e){setError(errorText(e));}}}>
 <label>Catégorie<select aria-label="Catégorie" required disabled={!!v.transferId} value={v.category} onChange={e=>setV({...v,category:e.target.value})}>{categories.map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</select></label>
 <label>TVA %<input disabled={!company?.vatEnabled||!!v.transferId} type="number" min="0" max="100" step=".1" value={v.vat_rate??0} onChange={e=>setV({...v,vat_rate:Number(e.target.value),vat_splits:[]})}/></label>
 {company?.vatEnabled&&!v.transferId&&<fieldset><legend>Ventilation multi-taux (part professionnelle uniquement)</legend>{(v.vat_splits??[]).map((line,i)=><div key={i}><label>Taux %<input type="number" min="0" max="100" step=".1" value={line.rate} onChange={e=>setV({...v,vat_splits:v.vat_splits!.map((x,j)=>i===j?{...x,rate:Number(e.target.value)}:x)})}/></label><label>TTC signé EUR<input type="number" step=".01" value={line.amount_ttc} onChange={e=>setV({...v,vat_splits:v.vat_splits!.map((x,j)=>i===j?{...x,amount_ttc:Number(e.target.value)}:x)})}/></label><button type="button" onClick={()=>setV({...v,vat_splits:v.vat_splits!.filter((_,j)=>i!==j)})}>Retirer</button></div>)}<button type="button" onClick={()=>setV({...v,vat_splits:[...(v.vat_splits??[]),{rate:0,amount_ttc:Math.round((v.amount_ttc-(v.vat_splits??[]).reduce((n,x)=>n+x.amount_ttc,0))*100)/100}]})}>+ Taux de TVA</button><p>La somme doit correspondre aux {money(Math.round(v.amount_ttc*100))} affectés à cette entreprise.</p></fieldset>}
 <fieldset><legend>Règlement — contrepartie comptable à confirmer</legend><label>Compte de contrepartie<input required pattern="[0-9]{3,}" value={settlement.accountNumber} onChange={e=>setV({...v,settlement:{...settlement,accountNumber:e.target.value}})}/></label><label>Libellé de contrepartie<input required value={settlement.label} onChange={e=>setV({...v,settlement:{...settlement,label:e.target.value}})}/></label><label>Code du journal<input required value={settlement.journalCode} onChange={e=>setV({...v,settlement:{...settlement,journalCode:e.target.value}})}/></label><label>Libellé du journal<input required value={settlement.journalLabel} onChange={e=>setV({...v,settlement:{...settlement,journalLabel:e.target.value}})}/></label>{v.transferId&&<><label>Compte opposé du virement<input required pattern="[0-9]{3,}" value={settlement.transferAccount?.number??""} onChange={e=>setV({...v,settlement:{...settlement,transferAccount:{number:e.target.value,label:settlement.transferAccount?.label??""}}})}/></label><label>Libellé du compte opposé<input required value={settlement.transferAccount?.label??""} onChange={e=>setV({...v,settlement:{...settlement,transferAccount:{number:settlement.transferAccount?.number??"",label:e.target.value}}})}/></label></>}</fieldset>
 <label>Référence de pièce<input value={v.invoiceRef??""} onChange={e=>setV({...v,invoiceRef:e.target.value})}/></label><label>Notes<textarea value={v.notes??""} onChange={e=>setV({...v,notes:e.target.value})}/></label><button className="eco-primary">Valider le traitement</button></form>}{error&&<p role="alert">{error}</p>}
 <button onClick={()=>openScope({view:"placeholder",scope:spec.scope,label:"Journal"})}>Journal de l’entreprise ↗</button></div>;
}
interface Preview {rows:{index:number;date:string;label:string;cents:number;duplicate:string|null}[];invalid:number}
export function LiveImport({spec}:{spec:ScopeTab}){
 const {data:s,command}=useLive();const accounts=s!.entities.filter(e=>e.kind==="account"&&!e.archived);
 const [accountId,setAccount]=useState(accounts.find(a=>a.id===spec.scope)?.id??accounts[0]?.id??""),[format,setFormat]=useState("csv"),[content,setContent]=useState(""),[columns,setColumns]=useState<string[]>([]),[mapping,setMapping]=useState({date:"",label:"",amount:"",debit:"",credit:"",externalId:""}),[preview,setPreview]=useState<Preview|null>(null),[selected,setSelected]=useState<number[]>([]),[notice,setNotice]=useState(""),[error,setError]=useState("");
 const payload={accountId,format,content,mapping};
 return <div className="eco-work"><h1>Importer un relevé</h1><p>Les montants sont importés en EUR. Vérifiez la sélection avant confirmation.</p><form className="eco-settings-form" onSubmit={async e=>{e.preventDefault();try{const p=await liveRequest<Preview>("post","imports/preview",payload);setPreview(p);setSelected(p.rows.filter(r=>!r.duplicate).map(r=>r.index));setError("");}catch(e){setError(errorText(e));}}}>
 <label>Compte destinataire<select required value={accountId} onChange={e=>{setAccount(e.target.value);setPreview(null);}}>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>Format<select value={format} onChange={e=>{setFormat(e.target.value);setPreview(null);}}><option>csv</option><option>ofx</option><option>qif</option></select></label>
 <label>Fichier<input type="file" accept=".csv,.ofx,.qif" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;const text=await file.text();setContent(text);setPreview(null);const ext=file.name.split(".").pop()?.toLowerCase();if(ext&&["csv","ofx","qif"].includes(ext))setFormat(ext);try{if(ext==="csv"){const data=await liveRequest<{columns:string[]}>("post","imports/columns",{content:text});setColumns(data.columns);}}catch(e){setError(errorText(e));}}}/></label>
 {format==="csv"&&Object.keys(mapping).map(key=><label key={key}>Colonne {({date:"date",label:"libellé",amount:"montant signé",debit:"débit (si colonnes séparées)",credit:"crédit (si colonnes séparées)",externalId:"identifiant bancaire (facultatif)"} as Record<string,string>)[key]}<select value={mapping[key as keyof typeof mapping]} onChange={e=>{setMapping({...mapping,[key]:e.target.value});setPreview(null);}}><option value="">Choisir…</option>{columns.map(c=><option key={c}>{c}</option>)}</select></label>)}<button disabled={!content||!accountId}>Prévisualiser</button></form>
 {error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{preview&&<><p>{preview.invalid} ligne(s) invalide(s) · {selected.length} sélectionnée(s)</p><div className="eco-table-wrap"><table><thead><tr><th>Importer</th><th>Date</th><th>Libellé</th><th>Montant</th><th>Doublon</th></tr></thead><tbody>{preview.rows.map(r=><tr key={r.index}><td><input aria-label={"Importer "+r.label} disabled={r.duplicate==="definite"} type="checkbox" checked={selected.includes(r.index)} onChange={e=>setSelected(e.target.checked?[...selected,r.index]:selected.filter(i=>i!==r.index))}/></td><td>{r.date}</td><td>{r.label}</td><td>{money(r.cents)}</td><td>{r.duplicate==="definite"?"Déjà importé":r.duplicate==="possible"?"Possible — à comparer":""}</td></tr>)}</tbody></table></div><button className="eco-primary" onClick={()=>void command({action:"import",import:{...payload,selectedRows:selected}}).then(()=>{setNotice("Import terminé.");setPreview(null);}).catch(e=>setError(errorText(e)))}>Confirmer l’import</button></>}</div>;
}
export function LiveTransfers({spec}:{spec:ScopeTab}){
 const {data:s,command}=useLive();const rows=scopedMovements(s!,spec.scope).filter(m=>!m.pending&&!m.duplicateCandidates?.length),used=new Set(s!.transfers.flatMap(t=>[t.fromId,t.toId]));const [from,setFrom]=useState(""),[to,setTo]=useState("");
 const candidates=s!.movements.filter(m=>!m.deleted&&!m.pending&&!m.duplicateCandidates?.length&&!used.has(m.id));
 return <div className="eco-work"><h1>Virements entre comptes</h1><p>Confirmez les deux mouvements du même virement. Ils restent visibles dans leurs comptes.</p><div className="eco-toolbar"><label>Départ<select value={from} onChange={e=>setFrom(e.target.value)}><option value="">Choisir…</option>{candidates.filter(m=>m.cents<0).map(m=><option key={m.id} value={m.id}>{m.date} · {scopeName(m.accountId)} · {m.label} · {money(m.cents)}</option>)}</select></label><label>Arrivée<select value={to} onChange={e=>setTo(e.target.value)}><option value="">Contrepartie à retrouver</option>{candidates.filter(m=>m.cents>0).map(m=><option key={m.id} value={m.id}>{m.date} · {scopeName(m.accountId)} · {m.label} · {money(m.cents)}</option>)}</select></label><button disabled={!from} onClick={()=>void command({action:"transfer",fromId:from,toId:to||undefined}).then(()=>{setFrom("");setTo("");}).catch(()=>undefined)}>Confirmer le virement</button></div>
 <h2>Suggestions</h2>{candidates.filter(a=>a.cents<0&&rows.includes(a)).flatMap(a=>candidates.filter(b=>b.accountId!==a.accountId&&b.cents===-a.cents&&Math.abs(Date.parse(a.date)-Date.parse(b.date))<=7*86400000).map(b=><p key={a.id+b.id}>{scopeName(a.accountId)} → {scopeName(b.accountId)} · {money(b.cents)} <button onClick={()=>{setFrom(a.id);setTo(b.id);}}>Sélectionner</button></p>))}
 <h2>Virements confirmés</h2>{s!.transfers.filter(t=>rows.some(m=>m.id===t.fromId||m.id===t.toId)).map(t=><p key={t.id}>{s!.movements.find(m=>m.id===t.fromId)?.label} · {t.toId?"Rapproché":"Contrepartie à retrouver"} <button onClick={()=>void command({action:"unlink",id:t.id}).catch(()=>undefined)}>Dissocier</button></p>)}</div>;
}
