import {useState} from "react";
import {useLive,errorText} from "./liveStore";
import {money,ROOT,scopeName,openScope,prototypeId,type ScopeTab} from "./model";
import {AllocationFields,scopedMovements,scopedAllocations,today} from "./LiveFinance";
import {Dialog} from "./Structure";
import type {Ecosystem,Budget,Recurring} from "../../types/ecosystem";
export function totals(s:Ecosystem,scope:string,period:string){
 const transfers=new Set(s.transfers.flatMap(t=>[t.fromId,t.toId]));let income=0,expenses=0;const categories=new Map<string,number>();
 for(const m of scopedMovements(s,scope).filter(m=>!m.pending&&!m.duplicateCandidates?.length&&!transfers.has(m.id)&&(!period||m.date.startsWith(period))))for(const a of scopedAllocations(s,m,scope)){
 if(m.nature==="income"&&a.cents>=0)income+=a.cents;else{expenses-=a.cents;categories.set(a.category,(categories.get(a.category)??0)-a.cents);}}
 return {income,expenses,net:income-expenses,categories};
}
function exportCsv(s:Ecosystem,scope:string,period:string,allocationMode:boolean){
 const rows:unknown[][]=[allocationMode?["Date","Mouvement","Compte","Affectation","Catégorie","Montant EUR"]:["Date","Mouvement","Compte","Montant EUR","Vérifié"]];
 const transfers=new Set(s.transfers.flatMap(t=>[t.fromId,t.toId]));
 for(const m of scopedMovements(s,scope).filter(m=>!m.pending&&!m.duplicateCandidates?.length&&(!period||m.date.startsWith(period)))){
 if(allocationMode){if(!transfers.has(m.id))for(const a of scopedAllocations(s,m,scope))rows.push([m.date,m.label,scopeName(m.accountId),a.target===ROOT?"Vie commune":scopeName(a.target),a.category,(a.cents/100).toFixed(2)]);}
 else rows.push([m.date,m.label,scopeName(m.accountId),(m.cents/100).toFixed(2),m.reviewed]);}
 const csv="\uFEFF"+rows.map(row=>row.map(v=>'"'+String(v).replace(/^[=+@\t\r]/,"'$&").replace(/"/g,'""')+'"').join(';')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));const a=document.createElement('a');a.href=url;a.download=allocationMode?"affectations.csv":"mouvements.csv";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
export function LiveOverview({spec}:{spec:ScopeTab}){
 const s=useLive(x=>x.data)!;const [period,setPeriod]=useState(spec.period??today().slice(0,7)),[selected,setSelected]=useState(""),[list,setList]=useState(false);
 const summary=totals(s,spec.scope,period),visible=scopedMovements(s,spec.scope).filter(m=>!m.pending&&!m.duplicateCandidates?.length&&(!period||m.date.startsWith(period)));
 type Flow={id:string;from:string;to:string;cents:number;ids:string[];transfer:boolean};const grouped=new Map<string,Flow>();
 for(const m of visible){
 const transfer=s.transfers.find(t=>t.fromId===m.id||t.toId===m.id);const other=transfer?s.movements.find(x=>x.id===(transfer.fromId===m.id?transfer.toId:transfer.fromId)):undefined;
 if(transfer&&other&&m.cents>0&&visible.some(v=>v.id===other.id))continue;
 const from=m.cents<0?m.accountId:other?.accountId??(transfer?"unmatched":"income"),to=m.cents>0?m.accountId:other?.accountId??(transfer?"unmatched":"expenses");const id=from+":"+to;const entry=grouped.get(id)??{id,from,to,cents:0,ids:[],transfer:!!transfer};entry.cents+=Math.abs(m.cents);entry.ids.push(m.id);grouped.set(id,entry);
 }
 const flows=[...grouped.values()],nodeIds=[...new Set(flows.flatMap(f=>[f.from,f.to]))];const label=(id:string)=>id==="income"?"Entrées externes":id==="expenses"?"Sorties externes":id==="unmatched"?"Contrepartie à retrouver":scopeName(id);
 const positions=new Map(nodeIds.map((id,i)=>[id,{x:35+(i%3)*280,y:50+Math.floor(i/3)*170}]));const height=Math.max(380,Math.ceil(nodeIds.length/3)*170+60);const chosen=flows.find(f=>f.id===selected);
 const accountIds=new Set(visible.map(m=>m.accountId));if(s.entities.some(e=>e.id===spec.scope&&e.kind==="account"))accountIds.add(spec.scope);if(spec.scope===ROOT)for(const e of s.entities.filter(e=>e.kind==="account"))accountIds.add(e.id);
 return <div className="eco-work"><h1>{spec.view==="flows"?"Flux financiers":"Vue d’ensemble"} · {scopeName(spec.scope)}</h1><div className="eco-toolbar"><label>Période<input type="month" value={period} onChange={e=>setPeriod(e.target.value)}/></label><button onClick={()=>setPeriod("")}>Toutes les dates</button><button onClick={()=>exportCsv(s,spec.scope,period,false)}>Exporter les mouvements</button><button onClick={()=>exportCsv(s,spec.scope,period,true)}>Exporter les affectations</button></div>
 <div className="eco-flow-summary"><span>Revenus affectés <strong>{money(summary.income)}</strong></span><span>Dépenses nettes affectées <strong>{money(summary.expenses)}</strong></span><span>Net <strong>{money(summary.net)}</strong></span></div><p className="eco-muted">Les affectations définissent les dépenses de ce périmètre. Les flux montrent les mouvements des comptes associés, y compris les comptes joints.</p>
 <div className="eco-toolbar"><button onClick={()=>setList(!list)}>{list?"Diagramme":"Liste des flux"}</button></div><div className="eco-split"><div className="eco-map-area">{list?<div className="eco-flow-list">{flows.map(f=><button key={f.id} onClick={()=>setSelected(f.id)}>{label(f.from)} → {label(f.to)} · {money(f.cents)}</button>)}</div>:<div className="eco-map-scroll"><div style={{position:"relative",width:870,height}}><svg width="870" height={height} aria-label="Diagramme des flux"><defs><marker id={"flow-arrow-"+spec.scope} viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="var(--vscode-accent)"/></marker></defs>{flows.map(f=>{const a=positions.get(f.from)!,b=positions.get(f.to)!;return <g key={f.id} role="button" tabIndex={0} aria-label={label(f.from)+" vers "+label(f.to)+" : "+money(f.cents)} onClick={()=>setSelected(f.id)} onKeyDown={e=>{if(e.key==="Enter")setSelected(f.id);}}><path d={`M ${a.x+110} ${a.y+65} C ${a.x+255} ${a.y+120},${b.x+255} ${b.y+120},${b.x+110} ${b.y+65}`} stroke="var(--vscode-accent)" strokeWidth={selected===f.id?5:3} strokeDasharray={f.transfer?"7 4":undefined} fill="none" markerEnd={`url(#flow-arrow-${spec.scope})`}/><title>{money(f.cents)}</title></g>;})}</svg>{nodeIds.map(id=>{const p=positions.get(id)!;return <button className="eco-node" key={id} style={{left:p.x,top:p.y}} onClick={()=>s.entities.some(e=>e.id===id)&&openScope({view:"transactions",scope:id,period})}><strong>{label(id)}</strong></button>;})}</div></div>}{!flows.length&&<p className="eco-empty">Aucun flux pour cette période.</p>}</div><aside className="eco-inspector"><h2>{chosen?label(chosen.from)+" → "+label(chosen.to):"Sélectionnez un flux"}</h2>{chosen&&<><strong>{money(chosen.cents)}</strong>{chosen.ids.map(id=>{const m=s.movements.find(m=>m.id===id)!;return <p key={id}><button onClick={()=>openScope({view:"movement",scope:m.accountId,record:id,period})}>{m.date} · {m.label} · {money(m.cents)} ↗</button></p>;})}</>}</aside></div>
 <h2>Comptes associés</h2><div className="eco-finance-grid">{s.entities.filter(e=>accountIds.has(e.id)).map(a=>{const balance=a.opening?a.opening.cents+s.movements.filter(m=>m.accountId===a.id&&!m.deleted&&!m.pending&&!m.duplicateCandidates?.length&&m.date>=a.opening!.date).reduce((n,m)=>n+m.cents,0):null;const feed=s.feeds.find(f=>f.accountId===a.id);return <article key={a.id}><h3>{a.name}</h3><p>Solde calculé : {balance===null?"solde initial requis":money(balance)}</p>{feed?.balance!==undefined&&<p>Solde bancaire communiqué : {money(feed.balance)}<small> · {feed.balanceAt}</small></p>}<button onClick={()=>openScope({view:"settings",scope:a.id})}>Configurer</button></article>;})}</div>
 <h2>Dépenses par catégorie</h2>{[...summary.categories].map(([category,cents])=><p key={category}>{category} · {money(cents)}</p>)}
 {spec.scope===ROOT&&<><h2>Contributions au commun</h2>{s.entities.filter(e=>e.kind==="person").map(p=>{let paid=0,returned=0;for(const t of s.transfers){const pair=s.movements.filter(m=>m.id===t.fromId||m.id===t.toId),debit=pair.find(m=>m.cents<0),credit=pair.find(m=>m.cents>0);if(!debit||!credit||period&&!credit.date.startsWith(period))continue;const owners=(account:string)=>s.relations.filter(r=>r.kind==="holder"&&r.to===account).map(r=>r.from);const from=owners(debit.accountId),to=owners(credit.accountId);if(from.length===1&&from[0]===p.id&&to.length>1)paid+=credit.cents;if(to.length===1&&to[0]===p.id&&from.length>1)returned+=credit.cents;}return <p key={p.id}>{p.name} · Versés : {money(paid)} · Retours : {money(returned)} · Net : {money(paid-returned)}</p>;})}</>}
 </div>;
}
export function LivePlanning({spec}:{spec:ScopeTab}){
 const {data:s,command}=useLive();const [month,setMonth]=useState(today().slice(0,7)),[budget,setBudget]=useState<Budget|null>(null),[recurring,setRecurring]=useState<Recurring|null>(null),[error,setError]=useState("");
 const targets=[{id:ROOT,name:"Vie commune"},...s!.entities.filter(e=>e.kind!=="account"&&!e.archived)],accounts=s!.entities.filter(e=>e.kind==="account"&&!e.archived);
 const target=targets.some(e=>e.id===spec.scope)?spec.scope:ROOT,transfers=new Set(s!.transfers.flatMap(t=>[t.fromId,t.toId]));
 return <div className="eco-work"><h1>Budgets et échéances · {scopeName(spec.scope)}</h1><p>Les échéances sont des prévisions. Elles ne créent aucun mouvement bancaire.</p><div className="eco-toolbar"><label>Mois<input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label><button onClick={()=>{setError("");setBudget({id:"",target,category:"",cents:0});}}>+ Budget</button><button disabled={!accounts.length} onClick={()=>{setError("");setRecurring({id:"",label:"",accountId:accounts[0].id,cents:0,allocations:[{id:prototypeId(),target,category:"À classer",cents:0}],frequency:"monthly",nextDate:today(),active:true});}}>+ Échéance</button></div>
 <h2>Budgets mensuels</h2><div className="eco-finance-grid">{s!.budgets.filter(b=>spec.scope===ROOT||b.target===spec.scope).map(b=>{const spent=-s!.movements.filter(m=>!m.deleted&&!m.pending&&!m.duplicateCandidates?.length&&m.date.startsWith(month)&&m.nature!=="income"&&!transfers.has(m.id)).flatMap(m=>m.allocations).filter(a=>a.target===b.target&&a.category===b.category).reduce((n,a)=>n+a.cents,0);return <article key={b.id}><h3>{b.category}</h3><p>{b.target===ROOT?"Vie commune":scopeName(b.target)} · {money(spent)} / {money(b.cents)}</p><progress max={Math.max(b.cents,1)} value={Math.max(0,spent)}/><button onClick={()=>setBudget({...b})}>Modifier</button><button onClick={()=>void command({action:"delete-budget",id:b.id}).catch(()=>undefined)}>Retirer</button></article>;})}</div>
 <h2>Échéances</h2><div className="eco-finance-grid">{s!.recurring.filter(r=>spec.scope===ROOT||r.accountId===spec.scope||r.allocations.some(a=>a.target===spec.scope)).map(r=><article key={r.id}><h3>{r.label}</h3><p>{money(r.cents)} · {scopeName(r.accountId)}</p><p>{r.frequency} · {r.active?r.nextDate:"Inactive"}</p><button onClick={()=>setRecurring(structuredClone(r))}>Modifier</button></article>)}</div>
 {(budget||recurring)&&<Dialog title={budget?"Budget mensuel":"Échéance récurrente"} onClose={()=>{setBudget(null);setRecurring(null);}}><form onSubmit={async e=>{e.preventDefault();try{await command(budget?{action:"budget",budget}:{action:"recurring",recurring});setBudget(null);setRecurring(null);}catch(e){setError(errorText(e));}}}>
 {budget&&<><label>Affectation<select value={budget.target} onChange={e=>setBudget({...budget,target:e.target.value})}>{targets.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>Catégorie<input required value={budget.category} onChange={e=>setBudget({...budget,category:e.target.value})}/></label><label>Budget EUR<input type="number" min="0" step=".01" required value={budget.cents/100} onChange={e=>setBudget({...budget,cents:Math.round(Number(e.target.value)*100)})}/></label></>}
 {recurring&&<><label>Libellé<input required value={recurring.label} onChange={e=>setRecurring({...recurring,label:e.target.value})}/></label><label>Compte<select value={recurring.accountId} onChange={e=>setRecurring({...recurring,accountId:e.target.value})}>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>Montant EUR<input type="number" min=".01" step=".01" value={recurring.cents/100} onChange={e=>{const cents=Math.round(Number(e.target.value)*100);setRecurring({...recurring,cents,allocations:recurring.allocations.length===1?[{...recurring.allocations[0],cents:-cents}]:recurring.allocations});}}/></label><AllocationFields lines={recurring.allocations} total={-recurring.cents} setLines={allocations=>setRecurring({...recurring,allocations})}/><label>Fréquence<select value={recurring.frequency} onChange={e=>setRecurring({...recurring,frequency:e.target.value as Recurring["frequency"]})}><option value="monthly">Mensuelle</option><option value="quarterly">Trimestrielle</option><option value="yearly">Annuelle</option></select></label><label>Prochaine date<input type="date" required value={recurring.nextDate} onChange={e=>setRecurring({...recurring,nextDate:e.target.value})}/></label><label><input type="checkbox" checked={recurring.active} onChange={e=>setRecurring({...recurring,active:e.target.checked})}/> Active</label></>}{error&&<p role="alert">{error}</p>}<button className="eco-primary">Enregistrer</button></form></Dialog>}</div>;
}
