import {useTabState} from "./tabContext";
import {createWorkspaceApi,type ReceiptOcrProposal} from "../../api/client";
import {useState} from "react";
import {useLive,liveRequest,liveUrl,errorText} from "./liveStore";
import {ROOT,money,scopeName,openScope,type ScopeTab} from "./model";
import {Dialog} from "./Structure";
import {documentTypes} from "./documentsModel";
import type {Ecosystem,Document} from "../../types/ecosystem";
export function documentMatch(s:Ecosystem,d:Document,scope:string):{kind:string;reasons:string[]}|null{
 if(scope===ROOT)return {kind:"direct",reasons:["Bibliothèque de l’écosystème"]};
 if(d.links.includes(scope))return {kind:"direct",reasons:["Lien direct · "+scopeName(scope)]};
 const e=s.entities.find(e=>e.id===scope);if(!e)return null;const related=new Set<string>();
 if(e.kind==="person")for(const r of s.relations.filter(r=>r.from===scope&&(r.kind==="holder"||r.kind==="activity")))related.add(r.to);
 if(e.kind==="company"){
 for(const r of s.relations){if(r.kind==="holder"&&r.from===scope)related.add(r.to);if(r.kind==="usage"&&r.to===scope)related.add(r.from);}
 const todo=[scope],seen=new Set(todo);while(todo.length){const id=todo.pop()!;for(const r of s.relations.filter(r=>r.kind==="subsidiary"&&r.from===id)){if(!seen.has(r.to)){seen.add(r.to);related.add(r.to);todo.push(r.to);}}}}
 const reasons=d.links.filter(id=>related.has(id)).map(id=>"Élément associé · "+scopeName(id));
 for(const m of s.movements.filter(m=>d.movementIds.includes(m.id)))if(m.accountId===scope||m.allocations.some(a=>a.target===scope)||related.has(m.accountId)||m.allocations.some(a=>related.has(a.target)))reasons.push("Mouvement associé · "+m.label);
 return reasons.length?{kind:"associated",reasons:[...new Set(reasons)]}:null;
}
export function LiveDocuments({spec}:{spec:ScopeTab}){
 const {data:s,command}=useLive();const [search,setSearch]=useTabState("search",""),[filter,setFilter]=useTabState("filter","all"),[selected,setSelected]=useState(spec.record??""),[editing,setEditing]=useState<Document|null>(null),[revision,setRevision]=useState(0),[adding,setAdding]=useState(false),[file,setFile]=useState<File|null>(null),[links,setLinks]=useState<string[]>(spec.scope===ROOT?[]:[spec.scope]),[kind,setKind]=useState(spec.category??"receipt"),[busy,setBusy]=useState(false),[error,setError]=useState(""),[ocr,setOcr]=useState("");
 const [proposal,setProposal]=useState<ReceiptOcrProposal|null>(null),[treatmentId,setTreatmentId]=useState("");
 const rows=s!.documents.map(d=>({d,match:documentMatch(s!,d,spec.scope)})).filter(({d,match})=>match&&(!spec.record||(d.id===spec.record||d.movementIds.includes(spec.record)))&&(!spec.category||d.kind===spec.category)&&(filter==="all"||filter==="inbox"&&!d.links.length&&!d.movementIds.length||match.kind===filter)&&d.name.toLowerCase().includes(search.toLowerCase()));const doc=rows.find(r=>r.d.id===selected)?.d;
 return <div className="eco-work"><div className="eco-heading"><h1>Documents · {scopeName(spec.scope)}</h1><button onClick={()=>{setFile(null);setError("");setLinks(spec.scope===ROOT?[]:[spec.scope]);setAdding(true);}}>+ Document</button></div>
 <div className="eco-toolbar"><label>Rechercher<input value={search} onChange={e=>setSearch(e.target.value)}/></label><label>Association<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Tous</option><option value="direct">Directement liés</option><option value="inbox">À relier</option><option value="associated">Éléments associés</option></select></label></div>
 <div className="eco-split"><div className="eco-table-wrap"><table><thead><tr><th>Document</th><th>Type</th><th>Date</th><th>Présence dans cette vue</th></tr></thead><tbody>{rows.map(({d,match})=><tr key={d.id}><td><button onClick={()=>{setSelected(d.id);setOcr("");setProposal(null);setTreatmentId("");}}>{d.name}</button></td><td>{documentTypes[d.kind as keyof typeof documentTypes]??d.kind}</td><td>{d.date}</td><td>{match!.reasons.join(" · ")}</td></tr>)}</tbody></table>{!rows.length&&<p className="eco-empty">Aucun document pour ces filtres.</p>}</div><aside className="eco-inspector">{doc?<><h2>{doc.name}</h2>{doc.amountCents!==undefined&&<p>Pièce : {money(doc.amountCents)} · Rapproché : {money((doc.settlements??[]).reduce((n,x)=>n+x.cents,0))} · Reste : {money(doc.amountCents-(doc.settlements??[]).reduce((n,x)=>n+x.cents,0))}</p>}<a href={liveUrl("documents/"+doc.id+"/file")} target="_blank" rel="noreferrer">Ouvrir / télécharger</a>{doc.mime.startsWith("image/")?<img alt={doc.name} src={liveUrl("documents/"+doc.id+"/file")}/>:<iframe title={"Aperçu "+doc.name} src={liveUrl("documents/"+doc.id+"/file")} style={{width:"100%",height:320}}/>}<button onClick={()=>{setEditing(structuredClone(doc));setRevision(s!.revision);setError("");}}>Modifier les liens</button><button onClick={()=>void liveRequest<{text:string;proposal:ReceiptOcrProposal}>("post","documents/"+doc.id+"/analyze").then(r=>{setOcr(r.text);setProposal(r.proposal);}).catch(e=>setError(errorText(e)))}>Analyser avec l’OCR local</button>{doc.movementIds.map(id=>{const m=s!.movements.find(m=>m.id===id);return m&&<p key={id}><button onClick={()=>openScope({view:"movement",scope:m.accountId,record:id})}>{m.label} ↗</button></p>;})}{proposal&&<form onSubmit={async e=>{e.preventDefault();try{
 const t=s!.treatments.find(t=>t.transaction.id===treatmentId);const c=s!.entities.find(c=>c.id===t?.companyId);if(!t||!c?.workspaceId)throw Error("Choisissez un traitement lié au document.");
 if(Math.round(Math.abs(t.transaction.amount_ttc)*100)!==Math.round(Math.abs(proposal.amountTtc)*100))throw Error("Ajustez la proposition à la part professionnelle avant application.");
 const sign=Math.sign(t.transaction.amount_ttc),splits=proposal.vatSplits.map(v=>({rate:v.rate,amount_ttc:sign*Math.abs(v.amountTtc)}));
 await createWorkspaceApi(c.workspaceId).updateTransaction(t.transaction.id,{revision:t.transaction.revision,invoiceRef:proposal.invoiceRef,vat_splits:splits,vat_rate:splits.length===1?splits[0].rate:0,status:"pending",reconciled:false});await useLive.getState().load(s!.id);setProposal(null);setError("");
 }catch(e){setError(errorText(e));}}}><h3>Proposition OCR à vérifier</h3><p>Les montants doivent correspondre à la part de l’entreprise. L’application conserve le traitement en attente.</p><label>Référence<input value={proposal.invoiceRef??""} onChange={e=>setProposal({...proposal,invoiceRef:e.target.value})}/></label><label>Total TTC de la proposition<input type="number" step=".01" value={proposal.amountTtc} onChange={e=>setProposal({...proposal,amountTtc:Number(e.target.value)})}/></label>{proposal.vatSplits.map((v,i)=><fieldset key={i}><label>Taux %<input type="number" step=".1" value={v.rate} onChange={e=>setProposal({...proposal,vatSplits:proposal.vatSplits.map((x,j)=>j===i?{...x,rate:Number(e.target.value)}:x)})}/></label><label>TTC EUR<input type="number" step=".01" value={v.amountTtc} onChange={e=>setProposal({...proposal,vatSplits:proposal.vatSplits.map((x,j)=>j===i?{...x,amountTtc:Number(e.target.value)}:x)})}/></label></fieldset>)}<label>Traitement destinataire<select required value={treatmentId} onChange={e=>setTreatmentId(e.target.value)}><option value="">Choisir…</option>{s!.treatments.filter(t=>t.movementId&&doc.movementIds.includes(t.movementId)&&t.transaction.status!=="validated").map(t=><option key={t.transaction.id} value={t.transaction.id}>{scopeName(t.companyId)} · {t.transaction.amount_ttc} EUR</option>)}</select></label><button>Appliquer la proposition vérifiée</button></form>}{ocr&&<pre style={{whiteSpace:"pre-wrap"}}>{ocr}</pre>}</>:<p>Sélectionnez un document pour l’ouvrir.</p>}</aside></div>{error&&<p role="alert">{error}</p>}
 {adding&&<Dialog title="Ajouter un document" onClose={()=>setAdding(false)}><form onSubmit={async e=>{e.preventDefault();if(!file)return;setBusy(true);try{const body=new FormData();body.append("file",file);const state=await liveRequest<Ecosystem>("post","documents?"+new URLSearchParams({revision:String(s!.revision),kind,...(links[0]?{scope:links[0]}:{}),...(spec.record?{movement:spec.record}:{})}),body);const d=state.documents[state.documents.length-1];if(links.length>1)await command({action:"document",id:d.id,document:{...d,links}});setSelected(d.id);setAdding(false);}catch(e){setError(errorText(e));}finally{setBusy(false);}}}>
 <label>Fichier<input type="file" required accept="application/pdf,image/jpeg,image/png,image/webp" capture="environment" onChange={e=>setFile(e.target.files?.[0]??null)}/></label><label>Type<select value={kind} onChange={e=>setKind(e.target.value)}>{Object.entries(documentTypes).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><fieldset><legend>Liens directs</legend>{s!.entities.map(e=><label className="eco-inline" key={e.id}><input type="checkbox" checked={links.includes(e.id)} onChange={v=>setLinks(v.target.checked?[...links,e.id]:links.filter(id=>id!==e.id))}/>{e.name}</label>)}</fieldset>{error&&<p role="alert">{error}</p>}<button disabled={busy} className="eco-primary">Enregistrer le document</button></form></Dialog>}
 {editing&&<Dialog title="Modifier le document" onClose={()=>setEditing(null)}><form onSubmit={async e=>{e.preventDefault();try{await command({action:"document",id:editing.id,document:editing,revision});setEditing(null);}catch(e){setError(errorText(e));}}}><label>Nom<input required value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})}/></label><fieldset><legend>Liens directs</legend>{s!.entities.map(e=><label className="eco-inline" key={e.id}><input type="checkbox" checked={editing.links.includes(e.id)} onChange={v=>setEditing({...editing,links:v.target.checked?[...editing.links,e.id]:editing.links.filter(id=>id!==e.id)})}/>{e.name}</label>)}</fieldset><label>Total de la pièce EUR (facultatif)<input type="number" min="0" step=".01" value={editing.amountCents===undefined?"":editing.amountCents/100} onChange={e=>setEditing({...editing,amountCents:e.target.value===""?undefined:Math.round(Number(e.target.value)*100)})}/></label><fieldset><legend>Mouvements liés</legend>{s!.movements.filter(m=>!m.deleted).map(m=><label className="eco-inline" key={m.id}><input type="checkbox" checked={editing.movementIds.includes(m.id)} onChange={e=>setEditing({...editing,movementIds:e.target.checked?[...editing.movementIds,m.id]:editing.movementIds.filter(id=>id!==m.id),settlements:e.target.checked?editing.settlements:editing.settlements?.filter(x=>x.movementId!==m.id)})}/>{m.date} · {m.label}{editing.movementIds.includes(m.id)&&<input aria-label={"Montant rapproché · "+m.label} type="number" min="0" max={Math.abs(m.cents)/100} step=".01" placeholder="Montant EUR (facultatif)" value={editing.settlements?.find(x=>x.movementId===m.id)?.cents===undefined?"":editing.settlements.find(x=>x.movementId===m.id)!.cents/100} onChange={e=>setEditing({...editing,settlements:[...(editing.settlements??[]).filter(x=>x.movementId!==m.id),...(e.target.value===""?[]:[{movementId:m.id,cents:Math.round(Number(e.target.value)*100)}])]})}/>}</label>)}</fieldset>{error&&<p role="alert">{error}</p>}<button className="eco-primary">Enregistrer les liens</button></form></Dialog>}</div>;
}
