import {useEffect,useState} from "react";
import {useLive,liveRequest,errorText} from "./liveStore";
import {scopeName,money,prototypeId} from "./model";
export function LiveBanking(){
 const s=useLive(x=>x.data)!;const [status,setStatus]=useState<{configured:boolean;connected:boolean;domain?:string;hosted:boolean}|null>(null),[config,setConfig]=useState({domain:"",clientId:"",clientSecret:""}),[accounts,setAccounts]=useState<{id:number;name:string;iban?:string;id_connection:number;currency?:{id:string}}[]>([]),[selected,setSelected]=useState<Record<number,string>>({}),[error,setError]=useState(""),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");
 const refresh=()=>liveRequest<NonNullable<typeof status>>("get","banking").then(setStatus);
 useEffect(()=>{void liveRequest<NonNullable<typeof status>>("get","banking").then(setStatus).catch(e=>setError(errorText(e)));},[]);
 async function run(work:()=>Promise<unknown>){setBusy(true);setError("");try{await work();}catch(e){setError(errorText(e));}finally{setBusy(false);}}
 return <div className="eco-work"><h1>Connexions bancaires</h1><p>Synchronisation manuelle via Powens. Les relevés CSV, OFX et QIF restent disponibles.</p>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 {!status?.configured&&<form className="eco-settings-form" onSubmit={e=>{e.preventDefault();void run(async()=>{await liveRequest("post","banking/config",config);setConfig({...config,clientSecret:""});await refresh();});}}><h2>Configurer Powens · administrateur</h2><label>Domaine<input required value={config.domain} onChange={e=>setConfig({...config,domain:e.target.value})}/></label><label>Client ID<input required value={config.clientId} onChange={e=>setConfig({...config,clientId:e.target.value})}/></label><label>Client secret<input type="password" required value={config.clientSecret} onChange={e=>setConfig({...config,clientSecret:e.target.value})}/></label><button disabled={busy}>Enregistrer</button></form>}
 {status?.configured&&<><p>Retour à enregistrer dans Powens : <code>{location.origin+import.meta.env.BASE_URL}</code></p><div className="eco-actions"><button disabled={busy} onClick={()=>void run(async()=>{const {url}=await liveRequest<{url:string}>("post","banking/connect",{redirectUrl:location.origin+import.meta.env.BASE_URL});location.assign(url);})}>Connecter une banque</button><button disabled={busy||!status.connected} onClick={()=>void run(async()=>{const result=await liveRequest<{accounts:typeof accounts}>("post","banking/discover");setAccounts(result.accounts);setSelected(Object.fromEntries(result.accounts.map(a=>[a.id,s.entities.find(e=>e.bankIdentifier&&e.bankIdentifier===a.iban?.replace(/\s/g,"").toUpperCase())?.id??""])));})}>Découvrir mes comptes connectés</button></div></>}
 {accounts.map(a=><div className="eco-toolbar" key={a.id}><span>{a.name} · {a.iban} · {a.currency?.id}</span><label>Compte dans ComptaOS<select value={selected[a.id]??""} onChange={e=>setSelected({...selected,[a.id]:e.target.value})}><option value="">Choisir un compte de la structure…</option>{s.entities.filter(e=>e.kind==="account"&&!e.archived).map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><button disabled={busy||!selected[a.id]||a.currency?.id!=="EUR"} onClick={()=>void run(async()=>{await liveRequest("post","banking/map",{revision:useLive.getState().data!.revision,providerAccountId:a.id,accountId:selected[a.id]});setNotice("Compte associé.");})}>Associer</button><button disabled={busy} onClick={()=>void run(async()=>{const id=prototypeId();await useLive.getState().command({action:"entity",entity:{id,kind:"account",name:a.name,usage:"Autre",bankIdentifier:a.iban}});setSelected({...selected,[a.id]:id});})}>Créer ce compte dans Structure</button></div>)}
 <h2>Flux associés</h2>{s.feeds.map(f=><article className="eco-bank-card" key={f.id}><h3>{scopeName(f.accountId)}</h3><p>{f.name} · Dernière récupération : {f.lastSync??"jamais"}</p>{f.balance!==undefined&&<p>Solde communiqué : {money(f.balance)}</p>}{f.error&&<p role="alert">{f.error}</p>}<button disabled={busy} onClick={()=>void run(async()=>{await liveRequest("post","banking/feeds/"+f.id+"/sync");setNotice("Récupération terminée. Consultez les mouvements à vérifier.");})}>{busy?"En cours…":"Synchroniser"}</button><button disabled={busy} onClick={()=>{if(confirm("Dissocier ce flux ? Les mouvements importés seront conservés."))void run(()=>liveRequest("delete","banking/feeds/"+f.id));}}>Dissocier le flux</button></article>)}</div>;
}
