import { useMemo, useState } from "react";
import { CartesianGrid, Legend, Line, LineChart, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import type { ManualRecurring, Transaction } from "../../types";
import { buildCashRunwayProjection } from "./cashRunwayModel";

const euros = (value: number) => value.toLocaleString("fr-FR", { minimumFractionDigits: 2, maximumFractionDigits: 2 }) + " €";

export function CashRunwaySimulator({ startBalance, recurring, transactions }: { startBalance: number; recurring: ManualRecurring[]; transactions: Transaction[] }) {
  const [horizon, setHorizon] = useState(12);
  const [investment, setInvestment] = useState(0);
  const [safetyReserve, setSafetyReserve] = useState(0);
  const projection = useMemo(() => buildCashRunwayProjection({ recurring, transactions, startBalance, monthsAhead: horizon, investment, safetyReserve }), [recurring, transactions, startBalance, horizon, investment, safetyReserve]);
  const chart = projection.months.map((month) => ({ ...month, label: new Date(`${month.month}-01T00:00:00`).toLocaleDateString("fr-FR", { month: "short", year: "2-digit" }) }));
  const final = projection.months.at(-1);
  const runway = projection.zeroRevenueRunwayMonths === null ? `> ${horizon} mois` : projection.zeroRevenueRunwayMonths === 0 ? "moins d’un mois" : `${projection.zeroRevenueRunwayMonths} mois`;

  return <section className="rounded-lg border border-purple-800 bg-purple-950/15 p-4">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="text-sm font-semibold text-purple-200">Autonomie et capacité d’investissement</h3><p className="mt-1 text-[10px] text-vscode-muted">Projection à partir du disponible après TVA et des frais récurrents confirmés.</p></div><div className="flex flex-wrap gap-2"><label className="text-[10px] text-vscode-muted">Horizon<select aria-label="Horizon de projection" value={horizon} onChange={(event) => setHorizon(Number(event.target.value))} className="ml-2 rounded border border-vscode-border bg-vscode-bg px-2 py-1 text-xs text-vscode-text">{[3, 6, 12, 18, 24].map((months) => <option key={months} value={months}>{months} mois</option>)}</select></label><label className="text-[10px] text-vscode-muted">Réserve de sécurité<input aria-label="Réserve de sécurité" type="number" min="0" step="100" value={safetyReserve} onChange={(event) => setSafetyReserve(Math.max(0, Number(event.target.value) || 0))} className="ml-2 w-28 rounded border border-vscode-border bg-vscode-bg px-2 py-1 text-xs text-vscode-text" /></label><label className="text-[10px] text-vscode-muted">Investissement simulé<input aria-label="Investissement simulé" type="number" min="0" step="100" value={investment} onChange={(event) => setInvestment(Math.max(0, Number(event.target.value) || 0))} className="ml-2 w-28 rounded border border-vscode-border bg-vscode-bg px-2 py-1 text-xs text-vscode-text" /></label></div></div>
    <div className="mt-4 grid grid-cols-2 gap-3 lg:grid-cols-5"><Metric label="Départ disponible" value={euros(startBalance)} /><Metric label="Charges engagées" value={euros(projection.totalCommittedExpenses)} /><Metric label="Autonomie sans revenu" value={runway} alert={projection.zeroRevenueRunwayMonths !== null} /><Metric label="Capacité d’investissement" value={euros(projection.investmentCapacity)} /><Metric label={`Solde sécurité à ${horizon} mois`} value={euros(final?.zeroRevenueBalance ?? startBalance)} alert={(final?.zeroRevenueBalance ?? startBalance) < safetyReserve} /></div>
    <div className="mt-4 h-72"><ResponsiveContainer width="100%" height="100%"><LineChart data={chart}><CartesianGrid strokeDasharray="3 3" stroke="#3c3c3c"/><XAxis dataKey="label" tick={{ fill: "#858585", fontSize: 10 }}/><YAxis tick={{ fill: "#858585", fontSize: 10 }}/><Tooltip contentStyle={{ background: "#252526", border: "1px solid #3c3c3c", fontSize: 12 }} formatter={(value: number) => euros(value)}/><Legend wrapperStyle={{ fontSize: 11 }}/><ReferenceLine y={safetyReserve} stroke="#f59e0b" strokeDasharray="4 4" label={{ value: "réserve", fill: "#f59e0b", fontSize: 10 }}/><Line type="monotone" dataKey="realisticBalance" name="Revenus moyens maintenus" stroke="#16a34a" strokeWidth={2} dot={false}/><Line type="monotone" dataKey="zeroRevenueBalance" name="Aucun nouvel encaissement" stroke="#a855f7" strokeWidth={2} strokeDasharray="5 4" dot={false}/></LineChart></ResponsiveContainer></div>
    <p className="mt-3 text-[10px] text-vscode-muted">Le scénario réaliste utilise la moyenne des encaissements des trois derniers mois. Le scénario de sécurité utilise zéro revenu. La capacité d’investissement conserve toutes les charges de l’horizon et la réserve choisie ; elle n’est pas un conseil financier.</p>
    {!recurring.some((item) => item.active) && <p className="mt-2 text-xs text-amber-300">Aucun frais récurrent confirmé : complète d’abord la section Frais récurrents pour obtenir une projection utile.</p>}
  </section>;
}

function Metric({ label, value, alert = false }: { label: string; value: string; alert?: boolean }) { return <div className="rounded border border-vscode-border bg-vscode-sidebar p-3"><p className="text-[10px] uppercase tracking-wide text-vscode-muted">{label}</p><p className={`mt-1 font-mono text-base font-semibold ${alert ? "text-amber-300" : "text-vscode-text"}`}>{value}</p></div>; }
