import { useEffect, useMemo, useState } from "react";
import { api } from "../../api/client";
import { LocalizedNumberInput } from "../Common/LocalizedNumberInput";
import { InventoryJournal, type InventoryEntry } from "./InventoryJournal";
import { FiscalResultPanel, type AccountBalance, type FiscalAdjustment } from "./FiscalResultPanel";
import { CorporateTaxPanel, type Statements, type TaxCalculation, type TaxConfig } from "./CorporateTaxPanel";

type Regime = "simplified" | "normal" | "unknown";
type ReviewKey = "bankBalance" | "customersAndSuppliers" | "fixedAssets" | "vat" | "accruals" | "equityLoansAndShareholders";
interface Period { id: string; startDate: string; endDate: string; label?: string }
interface BalanceLine { id: string; accountNumber: string; accountLabel: string; debit: number; credit: number }
interface Snapshot {
  availablePeriods: Period[]; period: Period;
  record: { profitTaxRegime: Regime; openingBalance: BalanceLine[]; review: Record<ReviewKey, boolean>; updatedAt: string };
  transactionSummary: { total: number; pending: number; unreconciled: number; misc: number; missingEvidence: number; missingFiles: number };
  openingBalanceSummary: { lines: number; debit: number; credit: number; balanced: boolean };
  inventoryEntries: InventoryEntry[];
  inventorySummary: { total: number; draft: number; posted: number; cancelled: number; debit: number; credit: number; balanced: boolean };
  accountingSummary: { eligibleTransactions: number; excludedTransactions: number; lines: number; debit: number; credit: number; balanced: boolean; anomalies: Array<{ severity: "blocking" | "warning"; code: string; message: string; transactionId?: string }>; balances: AccountBalance[] };
  fiscalAdjustments: FiscalAdjustment[]; fiscalReview: { confirmed: boolean; note: string; updatedAt: string };
  fiscalSummary: { charges: number; products: number; accountingResult: number; reintegrations: number; deductions: number; fiscalResult: number; taxableProfit: number; taxLoss: number; draft: number; validated: number };
  taxConfig: TaxConfig; taxCalculation: TaxCalculation; simplifiedStatements: Statements;
  deadlines: { resultDeclaration: string; corporateTaxBalance: string };
  steps: Array<{ id: string; label: string; status: "done" | "warning" | "blocked"; detail: string; count?: number }>;
  completed: number; total: number; dataReady: boolean; filingReady: boolean;
}

const euro = new Intl.NumberFormat("fr-FR", { style: "currency", currency: "EUR" });
const displayDate = (value: string) => new Intl.DateTimeFormat("fr-FR").format(new Date(`${value}T12:00:00`));
const reviewLabels: Record<ReviewKey, { title: string; detail: string }> = {
  bankBalance: { title: "Solde bancaire", detail: "Le relevé bancaire au dernier jour correspond aux comptes 512." },
  customersAndSuppliers: { title: "Clients et fournisseurs", detail: "Les factures non encaissées ou non payées sont recensées." },
  fixedAssets: { title: "Immobilisations", detail: "Les acquisitions, cessions et amortissements ont été contrôlés." },
  vat: { title: "TVA", detail: "TVA collectée, déductible, acomptes et CA12E ont été rapprochés." },
  accruals: { title: "Cut-off de l’exercice", detail: "CCA, PCA, charges à payer et produits à recevoir ont été examinés." },
  equityLoansAndShareholders: { title: "Financement", detail: "Capital, emprunts et comptes courants d’associés ont été contrôlés." },
};

function parseAmount(value: string) { const normalized = value.replace(/[ €\u00a0]/g, "").replace(",", "."); const result = Number(normalized); return Number.isFinite(result) ? result : 0; }
function splitCsvRow(row: string, separator: string) {
  const result: string[] = []; let current = ""; let quoted = false;
  for (let index = 0; index < row.length; index += 1) { const char = row[index]; if (char === '"' && row[index + 1] === '"' && quoted) { current += '"'; index += 1; } else if (char === '"') quoted = !quoted; else if (char === separator && !quoted) { result.push(current.trim()); current = ""; } else current += char; }
  result.push(current.trim()); return result;
}
function parseBalanceCsv(content: string): BalanceLine[] {
  const rows = content.replace(/^\uFEFF/, "").split(/\r?\n/).filter((row) => row.trim()); if (rows.length < 2) throw new Error("Le fichier ne contient aucune ligne de balance.");
  const separator = rows[0].includes(";") ? ";" : rows[0].includes("\t") ? "\t" : ","; const headers = splitCsvRow(rows[0], separator).map((header) => header.toLocaleLowerCase("fr-FR").normalize("NFD").replace(/[\u0300-\u036f]/g, ""));
  const find = (...names: string[]) => headers.findIndex((header) => names.some((name) => header.includes(name)));
  const accountIndex = find("compte", "account"); const labelIndex = find("libelle", "intitule", "label"); const debitIndex = find("debit"); const creditIndex = find("credit"); const balanceIndex = find("solde", "balance");
  if (accountIndex < 0 || labelIndex < 0 || (debitIndex < 0 && creditIndex < 0 && balanceIndex < 0)) throw new Error("Colonnes attendues : compte, libellé et débit/crédit (ou solde). ");
  return rows.slice(1).map((row, index) => { const values = splitCsvRow(row, separator); const balance = balanceIndex >= 0 ? parseAmount(values[balanceIndex] ?? "") : 0; return { id: crypto.randomUUID(), accountNumber: (values[accountIndex] ?? "").replace(/\s/g, ""), accountLabel: values[labelIndex] ?? "", debit: debitIndex >= 0 ? Math.abs(parseAmount(values[debitIndex] ?? "")) : Math.max(balance, 0), credit: creditIndex >= 0 ? Math.abs(parseAmount(values[creditIndex] ?? "")) : Math.max(-balance, 0) }; }).filter((line) => line.accountNumber || line.accountLabel || line.debit || line.credit).map((line, index) => ({ ...line, id: line.id || `line_${index}` }));
}

export function AnnualClosingView() {
  const [data, setData] = useState<Snapshot | null>(null); const [periodId, setPeriodId] = useState(""); const [lines, setLines] = useState<BalanceLine[]>([]);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  async function load(id = periodId) { setLoading(true); setError(""); try { const response = await api.get<Snapshot>("/annual-closing", { params: id ? { periodId: id } : {} }); setData(response.data); setPeriodId(response.data.period.id); setLines(response.data.record.openingBalance); } catch (caught) { setError(caught instanceof Error ? caught.message : "Chargement impossible."); } finally { setLoading(false); } }
  useEffect(() => { void load(""); }, []);
  const balance = useMemo(() => ({ debit: lines.reduce((sum, line) => sum + (line.debit || 0), 0), credit: lines.reduce((sum, line) => sum + (line.credit || 0), 0) }), [lines]);
  async function update(path: string, body: object, success: string) { if (!data) return; setSaving(true); setError(""); setNotice(""); try { const response = await api.put<Snapshot>(`/annual-closing/${data.period.id}/${path}`, body); setData(response.data); setLines(response.data.record.openingBalance); setNotice(success); } catch (caught) { setError(caught instanceof Error ? caught.message : "Enregistrement impossible."); } finally { setSaving(false); } }
  async function importCsv(file?: File) { if (!file) return; try { const parsed = parseBalanceCsv(await file.text()); setLines(parsed); setNotice(`${parsed.length} ligne(s) lue(s). Vérifie les totaux puis enregistre.`); setError(""); } catch (caught) { setError(caught instanceof Error ? caught.message : "Import impossible."); } }
  if (loading && !data) return <div className="flex h-full items-center justify-center text-sm text-vscode-muted">Chargement de la clôture annuelle…</div>;
  if (!data) return <div className="m-6 rounded border border-red-700 bg-red-950/30 p-4 text-sm text-red-300">{error || "Aucun exercice disponible."}</div>;
  const progress = Math.round(data.completed / Math.max(data.total, 1) * 100);
  return <div className="h-full overflow-auto bg-vscode-bg p-6"><div className="mx-auto max-w-6xl space-y-5">
    <header className="flex flex-wrap items-end justify-between gap-3"><div><div className="text-[10px] uppercase tracking-[.2em] text-vscode-muted">Comptes annuels et fiscalité</div><h1 className="mt-1 text-xl font-semibold">Clôture annuelle guidée</h1><p className="mt-1 text-xs text-vscode-muted">Période réelle, contrôles d’inventaire et préparation de la liasse — distincts des rapports par année civile.</p></div><label className="text-[10px] text-vscode-muted">Exercice<select value={periodId} onChange={(event) => { setPeriodId(event.target.value); void load(event.target.value); }} className="mt-1 block rounded border border-vscode-border bg-vscode-panel px-3 py-2 text-xs text-vscode-text">{data.availablePeriods.map((period) => <option key={period.id} value={period.id}>{period.label || "Exercice"} · {displayDate(period.startDate)} → {displayDate(period.endDate)}</option>)}</select></label></header>
    <section className="rounded border border-amber-700 bg-amber-950/20 p-4 text-xs text-amber-100"><strong>Déclaration non encore déposable.</strong><p className="mt-1 text-amber-100/75">Les états 2033-A et 2033-B affichés sont des documents de travail explicables. ComptaOS bloque volontairement la génération finale tant que les autres tableaux, la 2065 et les contrôles fiscaux ne sont pas finalisés.</p></section>
    {(error || notice) && <div aria-live="polite" className={`rounded border p-3 text-xs ${error ? "border-red-700 bg-red-950/30 text-red-300" : "border-green-700 bg-green-950/25 text-green-300"}`}>{error || notice}</div>}
    <section className="grid gap-3 md:grid-cols-4"><div className="rounded border border-vscode-border bg-vscode-panel p-4"><div className="text-[10px] text-vscode-muted">PÉRIODE</div><strong className="mt-2 block text-xs">{displayDate(data.period.startDate)}<br/>→ {displayDate(data.period.endDate)}</strong></div><div className="rounded border border-vscode-border bg-vscode-panel p-4"><div className="text-[10px] text-vscode-muted">DÉCLARATION DE RÉSULTAT</div><strong className="mt-2 block text-amber-300">{displayDate(data.deadlines.resultDeclaration)}</strong></div><div className="rounded border border-vscode-border bg-vscode-panel p-4"><div className="text-[10px] text-vscode-muted">SOLDE IS INDICATIF</div><strong className="mt-2 block text-amber-300">{displayDate(data.deadlines.corporateTaxBalance)}</strong></div><div className="rounded border border-vscode-border bg-vscode-panel p-4"><div className="flex justify-between text-[10px] text-vscode-muted"><span>AVANCEMENT</span><span>{data.completed}/{data.total}</span></div><strong className="mt-2 block text-blue-300">{progress} %</strong><div className="mt-2 h-1.5 rounded bg-vscode-bg"><div className="h-full rounded bg-vscode-accent" style={{ width: `${progress}%` }}/></div></div></section>
    <section className="rounded border border-vscode-border bg-vscode-panel p-4"><div className="flex flex-wrap items-center gap-3"><div className="mr-auto"><h2 className="text-sm font-semibold">Régime de la déclaration de résultat</h2><p className="text-[10px] text-vscode-muted">À distinguer du régime de TVA CA12.</p></div><select value={data.record.profitTaxRegime} onChange={(event) => void update("setup", { profitTaxRegime: event.target.value }, "Régime de la liasse enregistré.")} disabled={saving} className="rounded border border-vscode-border bg-vscode-bg px-3 py-2 text-xs"><option value="unknown">À confirmer…</option><option value="simplified">Réel simplifié · 2065 + 2033</option><option value="normal">Réel normal · 2065 + 2050</option></select></div></section>
    <section className="rounded border border-vscode-border bg-vscode-panel p-4"><div className="flex flex-wrap items-center gap-3"><div className="mr-auto"><h2 className="text-sm font-semibold">Balance d’ouverture</h2><p className="text-[10px] text-vscode-muted">Importe la balance définitive du premier exercice. Format CSV : compte, libellé, débit, crédit — ou solde.</p></div><label className="cursor-pointer rounded border border-blue-700 px-3 py-2 text-xs text-blue-300">Importer un CSV<input type="file" accept=".csv,.txt" className="hidden" onChange={(event) => void importCsv(event.target.files?.[0])}/></label><button onClick={() => setLines((current) => [...current, { id: crypto.randomUUID(), accountNumber: "", accountLabel: "", debit: 0, credit: 0 }])} className="rounded border border-vscode-border px-3 py-2 text-xs">+ Ligne</button><button disabled={saving || !lines.length || Math.abs(balance.debit - balance.credit) > .009} onClick={() => void update("opening-balance", { lines }, "Balance d’ouverture enregistrée.")} className="rounded bg-vscode-accent px-3 py-2 text-xs font-semibold text-white disabled:opacity-40">Enregistrer</button></div>
      <div className="mt-3 max-h-72 overflow-auto"><table className="w-full text-xs"><thead className="sticky top-0 bg-vscode-panel text-vscode-muted"><tr><th className="px-2 py-1 text-left">Compte</th><th className="px-2 py-1 text-left">Libellé</th><th className="px-2 py-1 text-right">Débit</th><th className="px-2 py-1 text-right">Crédit</th><th/></tr></thead><tbody>{lines.map((line, index) => <tr key={line.id} className="border-t border-vscode-border"><td className="p-1"><input value={line.accountNumber} onChange={(event) => setLines((current) => current.map((item, currentIndex) => currentIndex === index ? { ...item, accountNumber: event.target.value } : item))} className="w-28 rounded border border-vscode-border bg-vscode-bg p-1.5"/></td><td className="p-1"><input value={line.accountLabel} onChange={(event) => setLines((current) => current.map((item, currentIndex) => currentIndex === index ? { ...item, accountLabel: event.target.value } : item))} className="w-full rounded border border-vscode-border bg-vscode-bg p-1.5"/></td><td className="p-1"><LocalizedNumberInput value={line.debit} onValueChange={(value) => setLines((current) => current.map((item, currentIndex) => currentIndex === index ? { ...item, debit: value, credit: value ? 0 : item.credit } : item))} min={0} className="w-28 rounded border border-vscode-border bg-vscode-bg p-1.5 text-right"/></td><td className="p-1"><LocalizedNumberInput value={line.credit} onValueChange={(value) => setLines((current) => current.map((item, currentIndex) => currentIndex === index ? { ...item, credit: value, debit: value ? 0 : item.debit } : item))} min={0} className="w-28 rounded border border-vscode-border bg-vscode-bg p-1.5 text-right"/></td><td><button onClick={() => setLines((current) => current.filter((_, currentIndex) => currentIndex !== index))} className="px-2 text-red-400">×</button></td></tr>)}</tbody><tfoot><tr className="border-t border-vscode-border font-semibold"><td colSpan={2} className="p-2 text-right">Totaux</td><td className="p-2 text-right">{euro.format(balance.debit)}</td><td className="p-2 text-right">{euro.format(balance.credit)}</td><td/></tr></tfoot></table>{!lines.length && <p className="p-6 text-center text-xs text-vscode-muted">Aucune balance d’ouverture importée.</p>}</div>
    </section>
    <InventoryJournal period={data.period} entries={data.inventoryEntries} summary={data.inventorySummary} onSaved={(next, message) => { setData(next as Snapshot); setNotice(message); setError(""); }}/>
    <section className="rounded border border-vscode-border bg-vscode-panel p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-sm font-semibold">Impact sur le journal de l’exercice</h2><p className="mt-1 text-[10px] text-vscode-muted">Transactions bancaires rapprochées + balance d’ouverture + transferts comptabilisés + écritures d’inventaire validées.</p></div><div className={`text-right text-xs font-semibold ${data.accountingSummary.balanced ? "text-green-300" : "text-red-300"}`}>{data.accountingSummary.balanced ? "Journal équilibré" : "Journal déséquilibré"}<span className="mt-1 block font-normal text-vscode-muted">{data.accountingSummary.lines} lignes · D {euro.format(data.accountingSummary.debit)} · C {euro.format(data.accountingSummary.credit)}</span></div></div>{data.accountingSummary.anomalies.length > 0 && <details className="mt-3 rounded border border-amber-800 bg-amber-950/15 p-3"><summary className="cursor-pointer text-xs text-amber-300">{data.accountingSummary.anomalies.length} anomalie(s) comptable(s) à examiner</summary><div className="mt-2 space-y-1">{data.accountingSummary.anomalies.map((anomaly, index) => <p key={`${anomaly.code}-${anomaly.transactionId ?? index}`} className="text-[10px] text-amber-100/80">{anomaly.severity === "blocking" ? "⛔" : "⚠"} {anomaly.message}{anomaly.transactionId ? ` · opération ${anomaly.transactionId}` : ""}</p>)}</div></details>}</section>
    <FiscalResultPanel key={data.period.id} periodId={data.period.id} balances={data.accountingSummary.balances} adjustments={data.fiscalAdjustments} review={data.fiscalReview} summary={data.fiscalSummary} onSaved={(next, message) => { setData(next as Snapshot); setNotice(message); setError(""); }}/>
    <CorporateTaxPanel key={`tax-${data.period.id}-${data.taxConfig.updatedAt ?? ""}`} periodId={data.period.id} regime={data.record.profitTaxRegime} initialConfig={data.taxConfig} calculation={data.taxCalculation} statements={data.simplifiedStatements} onSaved={(next, message) => { setData(next as Snapshot); setNotice(message); setError(""); }}/>
    <section className="grid gap-3 lg:grid-cols-2">{(Object.keys(reviewLabels) as ReviewKey[]).map((key) => <label key={key} className={`flex cursor-pointer gap-3 rounded border p-4 ${data.record.review[key] ? "border-green-800 bg-green-950/15" : "border-vscode-border bg-vscode-panel"}`}><input type="checkbox" checked={data.record.review[key]} onChange={(event) => void update("review", { review: { [key]: event.target.checked } }, "Contrôle d’inventaire mis à jour.")} disabled={saving}/><span><strong className="text-xs">{reviewLabels[key].title}</strong><span className="mt-1 block text-[10px] text-vscode-muted">{reviewLabels[key].detail}</span></span></label>)}</section>
    <section className="rounded border border-vscode-border bg-vscode-panel"><div className="border-b border-vscode-border px-4 py-3"><h2 className="text-sm font-semibold">Contrôles de clôture</h2><p className="text-[10px] text-vscode-muted">Une alerte jaune demande une justification ; un blocage rouge empêche la génération finale.</p></div>{data.steps.map((step) => <div key={step.id} className="flex items-center gap-3 border-b border-vscode-border px-4 py-3 last:border-0"><span>{step.status === "done" ? "✓" : step.status === "warning" ? "⚠" : "⛔"}</span><div className="min-w-0 flex-1"><strong className="text-xs">{step.label}</strong><p className="text-[10px] text-vscode-muted">{step.detail}</p></div>{step.count ? <span className="rounded bg-vscode-bg px-2 py-1 font-mono text-[10px]">{step.count}</span> : null}</div>)}</section>
  </div></div>;
}
