import { useState } from "react";
import { api } from "../../api/client";
import { LocalizedNumberInput } from "../Common/LocalizedNumberInput";

type TriState = boolean | null;
export interface TaxConfig { turnoverOverride: number | null; belongsToGroup: TriState; groupTurnover: number | null; capitalFullyPaid: TriState; naturalPersonOwnershipPercent: number | null; hasSpecialTaxRegime: TriState; taxCredits: number; prepayments: number; reviewed: boolean; note: string; updatedAt?: string }
export interface TaxCalculation { months: number; reducedThreshold: number; automaticTurnover: number; turnover: number; eligibilityTurnover: number | null; conditionsComplete: boolean; reducedRateEligible: boolean; taxableBase: number; reducedBase: number; normalBase: number; reducedTax: number; normalTax: number; grossTax: number; taxCredits: number; netTax: number; prepayments: number; balance: number; reviewed: boolean; ready: boolean; warnings: string[] }
export interface StatementField { code: string; label: string; value: number; sourceAccounts?: string[] }
export interface Statements { balanceSheet: { assets: StatementField[]; fixedAssetsTotal: number; currentAssetsTotal: number; totalAssets: number; liabilities: StatementField[]; equityTotal: number; debtsTotal: number; totalLiabilities: number; difference: number }; profitAndLoss: { fields: StatementField[] }; fiscalTable: { fields: StatementField[] } }
const euro = new Intl.NumberFormat("fr-FR", { style: "currency", currency: "EUR" });
const triValue = (value: TriState) => value === null ? "" : value ? "yes" : "no";
const parseTri = (value: string): TriState => value === "yes" ? true : value === "no" ? false : null;

export function CorporateTaxPanel({ periodId, regime, initialConfig, calculation, statements, onSaved }: { periodId: string; regime: "simplified" | "normal" | "unknown"; initialConfig: TaxConfig; calculation: TaxCalculation; statements: Statements; onSaved: (data: unknown, notice: string) => void }) {
  const [config, setConfig] = useState<TaxConfig>(initialConfig); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const save = async (reviewed: boolean) => { setBusy(true); setError(""); try { const response = await api.put(`/annual-closing/${periodId}/corporate-tax`, { ...config, reviewed }); onSaved(response.data, reviewed ? "Calcul de l’IS confirmé sur les données actuelles." : "Hypothèses d’IS enregistrées."); } catch (caught) { setError(caught instanceof Error ? caught.message : "Enregistrement impossible."); } finally { setBusy(false); } };
  const selectClass = "mt-1 w-full rounded border border-vscode-border bg-vscode-bg p-2 text-xs text-vscode-text";
  return <section className="rounded border border-vscode-border bg-vscode-panel p-4"><div><h2 className="text-sm font-semibold">Impôt sur les sociétés et pré-remplissage 2033</h2><p className="mt-1 text-[10px] text-vscode-muted">Calcul de travail fondé sur les règles générales 2026. Il ne couvre pas les revenus à taux spécial, l’intégration fiscale ni la contribution sociale de 3,3 %.</p></div>
    {error && <div className="mt-3 rounded border border-red-700 bg-red-950/30 p-2 text-xs text-red-300">{error}</div>}
    <div className="mt-4 grid gap-2 md:grid-cols-3"><label className="text-[10px] text-vscode-muted">Chiffre d’affaires calculé<input readOnly value={euro.format(calculation.automaticTurnover)} className={`${selectClass} text-vscode-muted`}/></label><label className="text-[10px] text-vscode-muted">Correction manuelle du CA<LocalizedNumberInput value={config.turnoverOverride} onValueChange={(value) => setConfig((current) => ({ ...current, turnoverOverride: value }))} min={0} placeholder="Vide = montant calculé" className={selectClass}/><button type="button" onClick={() => setConfig((current) => ({ ...current, turnoverOverride: null }))} className="mt-1 text-[9px] text-blue-300">Reprendre le montant calculé</button></label><label className="text-[10px] text-vscode-muted">Société appartenant à un groupe ?<select value={triValue(config.belongsToGroup)} onChange={(event) => setConfig((current) => ({ ...current, belongsToGroup: parseTri(event.target.value) }))} className={selectClass}><option value="">À confirmer…</option><option value="no">Non</option><option value="yes">Oui</option></select></label>
      {config.belongsToGroup === true && <label className="text-[10px] text-vscode-muted">CA du groupe<LocalizedNumberInput value={config.groupTurnover} onValueChange={(value) => setConfig((current) => ({ ...current, groupTurnover: value }))} min={0} className={selectClass}/></label>}<label className="text-[10px] text-vscode-muted">Capital entièrement libéré ?<select value={triValue(config.capitalFullyPaid)} onChange={(event) => setConfig((current) => ({ ...current, capitalFullyPaid: parseTri(event.target.value) }))} className={selectClass}><option value="">À confirmer…</option><option value="yes">Oui</option><option value="no">Non</option></select></label><label className="text-[10px] text-vscode-muted">Détention par des personnes physiques<LocalizedNumberInput value={config.naturalPersonOwnershipPercent} onValueChange={(value) => setConfig((current) => ({ ...current, naturalPersonOwnershipPercent: value }))} min={0} max={100} placeholder="Pourcentage" className={selectClass}/></label><label className="text-[10px] text-vscode-muted">Revenus exonérés ou à taux spécial ?<select value={triValue(config.hasSpecialTaxRegime)} onChange={(event) => setConfig((current) => ({ ...current, hasSpecialTaxRegime: parseTri(event.target.value) }))} className={selectClass}><option value="">À confirmer…</option><option value="no">Non</option><option value="yes">Oui — calcul standard insuffisant</option></select></label><label className="text-[10px] text-vscode-muted">Crédits et réductions d’impôt<LocalizedNumberInput value={config.taxCredits} onValueChange={(value) => setConfig((current) => ({ ...current, taxCredits: value }))} min={0} className={selectClass}/></label><label className="text-[10px] text-vscode-muted">Acomptes d’IS déjà versés<LocalizedNumberInput value={config.prepayments} onValueChange={(value) => setConfig((current) => ({ ...current, prepayments: value }))} min={0} className={selectClass}/></label><label className="text-[10px] text-vscode-muted md:col-span-3">Note de contrôle<textarea value={config.note} onChange={(event) => setConfig((current) => ({ ...current, note: event.target.value }))} className={`${selectClass} min-h-16`}/></label></div>
    <div className="mt-3 flex flex-wrap justify-end gap-2"><button disabled={busy} onClick={() => void save(false)} className="rounded border border-vscode-border px-3 py-2 text-xs">Enregistrer les hypothèses</button><button disabled={busy || config.hasSpecialTaxRegime !== false || config.capitalFullyPaid === null || config.belongsToGroup === null || config.naturalPersonOwnershipPercent === null || (config.belongsToGroup === true && config.groupTurnover === null)} onClick={() => void save(true)} className="rounded bg-green-800 px-3 py-2 text-xs font-semibold text-white disabled:opacity-40">Confirmer le calcul d’IS</button></div>
    <div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-5">{[["Base imposable", calculation.taxableBase], [`Base à 15 % · plafond ${euro.format(calculation.reducedThreshold)}`, calculation.reducedBase], ["Base à 25 %", calculation.normalBase], ["IS net provisoire", calculation.netTax], [calculation.balance >= 0 ? "Solde à payer" : "Créance après acomptes", Math.abs(calculation.balance)]].map(([label, value]) => <div key={String(label)} className="rounded border border-vscode-border bg-vscode-bg/40 p-3"><span className="text-[9px] uppercase text-vscode-muted">{label}</span><strong className="mt-1 block text-sm">{euro.format(Number(value))}</strong></div>)}</div>
    <div className={`mt-3 rounded border p-3 text-xs ${calculation.ready ? "border-green-800 bg-green-950/15 text-green-200" : "border-amber-800 bg-amber-950/15 text-amber-200"}`}><strong>{calculation.ready ? "Calcul contrôlé sur les données actuelles" : "Calcul non encore validé"}</strong><p className="mt-1 text-[10px] opacity-80">{calculation.reducedRateEligible ? "Taux réduit de 15 % appliqué sur la tranche admissible, puis 25 %." : "Taux normal de 25 % appliqué ; les conditions du taux réduit ne sont pas réunies ou restent incomplètes."}</p>{calculation.warnings.map((warning) => <p key={warning} className="mt-1 text-[10px]">⚠ {warning}</p>)}</div>
    <div className="mt-5 border-t border-vscode-border pt-4"><h3 className="text-xs font-semibold">États simplifiés de travail — millésime 2026</h3><p className="mt-1 text-[10px] text-vscode-muted">Pré-remplissage explicable des tableaux 2033-A et 2033-B. Ce n’est pas encore un fichier EDI-TDFC déposable.</p>{regime !== "simplified" && <div className="mt-3 rounded border border-amber-800 p-2 text-xs text-amber-300">Le dossier n’est pas confirmé au réel simplifié : ces tableaux 2033 sont fournis uniquement comme contrôle.</div>}
      <div className="mt-3 grid gap-3 md:grid-cols-3"><div className="rounded border border-vscode-border p-3"><span className="text-[9px] text-vscode-muted">TOTAL ACTIF 2033-A</span><strong className="block">{euro.format(statements.balanceSheet.totalAssets)}</strong></div><div className="rounded border border-vscode-border p-3"><span className="text-[9px] text-vscode-muted">TOTAL PASSIF 2033-A</span><strong className="block">{euro.format(statements.balanceSheet.totalLiabilities)}</strong></div><div className={`rounded border p-3 ${Math.abs(statements.balanceSheet.difference) <= .01 ? "border-green-800" : "border-red-800"}`}><span className="text-[9px] text-vscode-muted">ÉCART À EXPLIQUER</span><strong className={Math.abs(statements.balanceSheet.difference) <= .01 ? "text-green-300" : "text-red-300"}>{euro.format(statements.balanceSheet.difference)}</strong></div></div>
      <div className="mt-3 grid gap-3 lg:grid-cols-2"><StatementTable title="2033-A · Actif" fields={statements.balanceSheet.assets}/><StatementTable title="2033-A · Passif" fields={statements.balanceSheet.liabilities}/><StatementTable title="2033-B · Compte de résultat" fields={statements.profitAndLoss.fields}/><StatementTable title="2033-B · Passage au résultat fiscal" fields={statements.fiscalTable.fields}/></div>
    </div>
  </section>;
}

function StatementTable({ title, fields }: { title: string; fields: StatementField[] }) { return <details className="rounded border border-vscode-border"><summary className="cursor-pointer px-3 py-2 text-xs font-semibold">{title}</summary><div className="max-h-96 overflow-auto border-t border-vscode-border"><table className="w-full text-[10px]"><thead className="sticky top-0 bg-vscode-panel text-vscode-muted"><tr><th className="p-2 text-left">Case</th><th className="p-2 text-left">Rubrique</th><th className="p-2 text-right">Montant</th></tr></thead><tbody>{fields.map((field) => <tr key={`${field.code}-${field.label}`} className="border-t border-vscode-border"><td className="p-2 font-mono text-blue-300">{field.code}</td><td className="p-2">{field.label}{field.sourceAccounts?.length ? <span className="mt-0.5 block text-[9px] text-vscode-muted">Comptes : {field.sourceAccounts.join(", ")}</span> : null}</td><td className="p-2 text-right font-semibold">{euro.format(field.value)}</td></tr>)}</tbody></table></div></details>; }
