import { useState } from "react";
import { api, apiUrl } from "../../api/client";
import { LocalizedNumberInput } from "../Common/LocalizedNumberInput";

type ReviewKey = "fixedAssets" | "provisionsAndLosses" | "valueAdded" | "capitalAndOwners" | "subsidiaries" | "corporateTaxReturn";
interface OwnerDetail { address: string; birthDate: string; birthPlace: string; legalForm: string; siren: string }
interface SubsidiaryDetail { address: string; postalCode: string; city: string; country: string; legalForm: string; siren: string }
export interface FilingConfig { activity: string; signatoryName: string; signatoryRole: string; signatoryCity: string; declarationDate: string; averageEmployees: number | null; accountingSoftware: string; ownerDetails: Record<string, OwnerDetail>; subsidiaryDetails: Record<string, SubsidiaryDetail>; review: Record<ReviewKey, boolean>; updatedAt: string }
export interface FilingPackage {
  millesime: number; ready: boolean; missing: string[]; unreviewed: string[];
  identity: { name: string; legalForm: string; siren: string; siret: string; address: string; activity: string; capital: string };
  form2065: { taxableAt15: number; taxableAt25: number; grossTax: number; taxCredits: number; netTax: number; prepayments: number; balance: number };
  form2033C: { fixedAssets: Array<{ label: string; openingGross: number; increases: number; decreases: number; closingGross: number; openingDepreciation: number; depreciationCharge: number; depreciationDecrease: number; closingDepreciation: number; closingNet: number }>; capitalGains: { saleProceeds: number; netBookValueDisposed: number; netGain: number } };
  form2033D: { provisions: Array<{ label: string; amount: number }>; lossCarryforwards: number };
  form2033E: { turnover: number; production: number; externalConsumption: number; valueAdded: number; taxes: number; wages: number; socialCharges: number; depreciation: number; averageEmployees: number | null };
  form2033F: { capital: number; owners: Array<{ id: string; kind: "person" | "entity"; name: string; ownershipPercent: number | null; shareCount: number | null; address: string; birthDate: string; birthPlace: string; legalForm: string; siren: string }>; ownershipTotal: number };
  form2033G: { subsidiaries: Array<{ id: string; name: string; ownershipPercent: number | null; shareCount: number | null; address: string; postalCode: string; city: string; country: string; legalForm: string; siren: string }> };
}

const euro = new Intl.NumberFormat("fr-FR", { style: "currency", currency: "EUR" });
const reviews: Record<ReviewKey, { title: string; detail: string }> = {
  fixedAssets: { title: "2033-C · Immobilisations et amortissements", detail: "Les valeurs d’ouverture, mouvements, dotations et valeurs de clôture sont exacts." },
  provisionsAndLosses: { title: "2033-D · Provisions et déficits", detail: "Les provisions et déficits reportables sont complets, y compris si le tableau est à néant." },
  valueAdded: { title: "2033-E · Valeur ajoutée et effectif", detail: "Le calcul de valeur ajoutée et l’effectif moyen ont été contrôlés." },
  capitalAndOwners: { title: "2033-F · Capital et associés", detail: "Le capital et sa répartition correspondent à la situation à la clôture." },
  subsidiaries: { title: "2033-G · Filiales et participations", detail: "Les participations sont complètes, ou l’absence de filiale est confirmée." },
  corporateTaxReturn: { title: "2065 · Déclaration de résultat", detail: "L’identité, le résultat fiscal, les taux, crédits, acomptes et le signataire ont été contrôlés." },
};

export function FilingPackagePanel({ periodId, initialConfig, pack, taxReady, onSaved }: { periodId: string; initialConfig: FilingConfig; pack: FilingPackage; taxReady: boolean; onSaved: (data: unknown, notice: string) => void }) {
  const [config, setConfig] = useState(initialConfig); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const input = "mt-1 w-full rounded border border-vscode-border bg-vscode-bg p-2 text-xs text-vscode-text";
  const ownerDetail = (id: string): OwnerDetail => config.ownerDetails[id] ?? { address: "", birthDate: "", birthPlace: "", legalForm: "", siren: "" };
  const patchOwner = (id: string, patch: Partial<OwnerDetail>) => setConfig((current) => ({ ...current, ownerDetails: { ...current.ownerDetails, [id]: { ...(current.ownerDetails[id] ?? { address: "", birthDate: "", birthPlace: "", legalForm: "", siren: "" }), ...patch } } }));
  const subsidiaryDetail = (id: string): SubsidiaryDetail => config.subsidiaryDetails[id] ?? { address: "", postalCode: "", city: "", country: "France", legalForm: "", siren: "" };
  const patchSubsidiary = (id: string, patch: Partial<SubsidiaryDetail>) => setConfig((current) => ({ ...current, subsidiaryDetails: { ...current.subsidiaryDetails, [id]: { ...(current.subsidiaryDetails[id] ?? { address: "", postalCode: "", city: "", country: "France", legalForm: "", siren: "" }), ...patch } } }));
  const save = async () => { setBusy(true); setError(""); try { const response = await api.put(`/annual-closing/${periodId}/filing`, config); onSaved(response.data, "Fiche 2065 et contrôles 2033 enregistrés."); } catch (caught) { setError(caught instanceof Error ? caught.message : "Enregistrement impossible."); } finally { setBusy(false); } };
  return <section className="rounded border border-vscode-border bg-vscode-panel p-4">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-sm font-semibold">Dossier final 2065 + 2033-A à 2033-G</h2><p className="mt-1 text-[10px] text-vscode-muted">Dossier de saisie millésime {pack.millesime}, contrôlable puis exportable. L’export ne réalise pas la télétransmission à la DGFiP.</p></div><span className={`rounded px-2 py-1 text-[10px] ${pack.ready && taxReady ? "bg-green-950 text-green-300" : "bg-amber-950 text-amber-300"}`}>{pack.ready && taxReady ? "PRÊT À TRANSMETTRE" : "À COMPLÉTER"}</span></div>
    {error && <div className="mt-3 rounded border border-red-700 p-2 text-xs text-red-300">{error}</div>}
    {(pack.missing.length > 0 || pack.unreviewed.length > 0 || !taxReady) && <div className="mt-3 rounded border border-amber-800 bg-amber-950/15 p-3 text-xs text-amber-200"><strong>Éléments restants</strong>{pack.missing.map((item) => <p key={item} className="mt-1">• {item}</p>)}{pack.unreviewed.length > 0 && <p className="mt-1">• {pack.unreviewed.length} tableau(x) à confirmer ci-dessous</p>}{!taxReady && <p className="mt-1">• Reconfirmer le calcul d’IS sur les données actuelles</p>}</div>}
    <div className="mt-4 grid gap-2 md:grid-cols-3"><label className="text-[10px] text-vscode-muted md:col-span-2">Activité exercée<input value={config.activity} onChange={(event) => setConfig((current) => ({ ...current, activity: event.target.value }))} placeholder="Ex. développement de logiciels et prestations numériques" className={input}/></label><label className="text-[10px] text-vscode-muted">Effectif moyen<LocalizedNumberInput value={config.averageEmployees} onValueChange={(value) => setConfig((current) => ({ ...current, averageEmployees: value }))} min={0} className={input}/></label><label className="text-[10px] text-vscode-muted">Nom du signataire<input value={config.signatoryName} onChange={(event) => setConfig((current) => ({ ...current, signatoryName: event.target.value }))} className={input}/></label><label className="text-[10px] text-vscode-muted">Qualité<input value={config.signatoryRole} onChange={(event) => setConfig((current) => ({ ...current, signatoryRole: event.target.value }))} placeholder="Ex. Président" className={input}/></label><label className="text-[10px] text-vscode-muted">Lieu<input value={config.signatoryCity} onChange={(event) => setConfig((current) => ({ ...current, signatoryCity: event.target.value }))} className={input}/></label><label className="text-[10px] text-vscode-muted">Date de déclaration<input type="date" value={config.declarationDate} onChange={(event) => setConfig((current) => ({ ...current, declarationDate: event.target.value }))} className={input}/></label><label className="text-[10px] text-vscode-muted md:col-span-2">Logiciel de comptabilité<input value={config.accountingSoftware} onChange={(event) => setConfig((current) => ({ ...current, accountingSoftware: event.target.value }))} className={input}/></label></div>
    <div className="mt-4 grid gap-3 md:grid-cols-2 lg:grid-cols-3">
      <Summary title="2065 · Résultat"><p>15 % : <strong>{euro.format(pack.form2065.taxableAt15)}</strong></p><p>25 % : <strong>{euro.format(pack.form2065.taxableAt25)}</strong></p><p>IS net : <strong>{euro.format(pack.form2065.netTax)}</strong></p></Summary>
      <Summary title="2033-C · Immobilisations">{pack.form2033C.fixedAssets.map((row) => <p key={row.label}>{row.label} : <strong>{euro.format(row.closingNet)}</strong><span className="block text-[9px] text-vscode-muted">Brut {euro.format(row.closingGross)} · amort. {euro.format(row.closingDepreciation)}</span></p>)}<p>Plus ou moins-value nette : <strong>{euro.format(pack.form2033C.capitalGains.netGain)}</strong></p></Summary>
      <Summary title="2033-D · Provisions">{pack.form2033D.provisions.map((row) => <p key={row.label}>{row.label} : <strong>{euro.format(row.amount)}</strong></p>)}<p>Déficits imputés : <strong>{euro.format(pack.form2033D.lossCarryforwards)}</strong></p></Summary>
      <Summary title="2033-E · Valeur ajoutée"><p>Production : <strong>{euro.format(pack.form2033E.production)}</strong></p><p>Consommations externes : <strong>{euro.format(pack.form2033E.externalConsumption)}</strong></p><p>Valeur ajoutée : <strong>{euro.format(pack.form2033E.valueAdded)}</strong></p></Summary>
      <Summary title="2033-F · Capital"><p>Capital : <strong>{euro.format(pack.form2033F.capital)}</strong></p>{pack.form2033F.owners.map((row) => <p key={row.name}>{row.name} : <strong>{row.ownershipPercent ?? "?"} %</strong>{row.shareCount !== null ? ` · ${row.shareCount} parts` : ""}</p>)}{!pack.form2033F.owners.length && <p className="text-amber-300">Aucun associé relié</p>}</Summary>
      <Summary title="2033-G · Participations">{pack.form2033G.subsidiaries.length ? pack.form2033G.subsidiaries.map((row) => <p key={row.name}>{row.name} : <strong>{row.ownershipPercent ?? "?"} %</strong></p>) : <p>Néant</p>}</Summary>
    </div>
    {pack.form2033F.owners.some((owner) => (owner.ownershipPercent ?? 0) >= 10) && <div className="mt-4 rounded border border-vscode-border p-3"><h3 className="text-xs font-semibold">Informations personnelles requises pour le 2033-F</h3><p className="mt-1 text-[9px] text-vscode-muted">Ces informations concernent uniquement les associés détenant au moins 10 % du capital et restent dans le dossier de l’entreprise.</p><div className="mt-3 space-y-2">{pack.form2033F.owners.filter((owner) => (owner.ownershipPercent ?? 0) >= 10).map((owner) => { const detail = ownerDetail(owner.id); return <details key={owner.id} className="rounded border border-vscode-border p-3"><summary className="cursor-pointer text-xs font-semibold">{owner.name} · {owner.ownershipPercent ?? "?"} % · {owner.shareCount ?? "?"} titres</summary><div className="mt-3 grid gap-2 md:grid-cols-3"><label className="text-[10px] text-vscode-muted md:col-span-3">Adresse complète<input value={detail.address} onChange={(event) => patchOwner(owner.id, { address: event.target.value })} className={input}/></label>{owner.kind === "person" ? <><label className="text-[10px] text-vscode-muted">Date de naissance<input type="date" value={detail.birthDate} onChange={(event) => patchOwner(owner.id, { birthDate: event.target.value })} className={input}/></label><label className="text-[10px] text-vscode-muted md:col-span-2">Lieu de naissance<input value={detail.birthPlace} onChange={(event) => patchOwner(owner.id, { birthPlace: event.target.value })} className={input}/></label></> : <><label className="text-[10px] text-vscode-muted">Forme juridique<input value={detail.legalForm} onChange={(event) => patchOwner(owner.id, { legalForm: event.target.value })} className={input}/></label><label className="text-[10px] text-vscode-muted">SIREN<input value={detail.siren} onChange={(event) => patchOwner(owner.id, { siren: event.target.value })} className={input}/></label></>}</div></details>; })}</div></div>}
    {pack.form2033G.subsidiaries.some((subsidiary) => (subsidiary.ownershipPercent ?? 0) >= 10) && <div className="mt-4 rounded border border-vscode-border p-3"><h3 className="text-xs font-semibold">Identification des filiales requise pour le 2033-G</h3><div className="mt-3 space-y-2">{pack.form2033G.subsidiaries.filter((subsidiary) => (subsidiary.ownershipPercent ?? 0) >= 10).map((subsidiary) => { const detail = subsidiaryDetail(subsidiary.id); return <details key={subsidiary.id} className="rounded border border-vscode-border p-3"><summary className="cursor-pointer text-xs font-semibold">{subsidiary.name} · {subsidiary.ownershipPercent ?? "?"} %</summary><div className="mt-3 grid gap-2 md:grid-cols-3"><label className="text-[10px] text-vscode-muted">Forme juridique<input value={detail.legalForm} onChange={(event) => patchSubsidiary(subsidiary.id, { legalForm: event.target.value })} className={input}/></label><label className="text-[10px] text-vscode-muted">SIREN<input value={detail.siren} onChange={(event) => patchSubsidiary(subsidiary.id, { siren: event.target.value })} className={input}/></label><label className="text-[10px] text-vscode-muted">Pays<input value={detail.country} onChange={(event) => patchSubsidiary(subsidiary.id, { country: event.target.value })} className={input}/></label><label className="text-[10px] text-vscode-muted md:col-span-3">Adresse<input value={detail.address} onChange={(event) => patchSubsidiary(subsidiary.id, { address: event.target.value })} className={input}/></label><label className="text-[10px] text-vscode-muted">Code postal<input value={detail.postalCode} onChange={(event) => patchSubsidiary(subsidiary.id, { postalCode: event.target.value })} className={input}/></label><label className="text-[10px] text-vscode-muted md:col-span-2">Ville<input value={detail.city} onChange={(event) => patchSubsidiary(subsidiary.id, { city: event.target.value })} className={input}/></label></div></details>; })}</div></div>}
    <div className="mt-4 grid gap-2 md:grid-cols-2">{(Object.keys(reviews) as ReviewKey[]).map((key) => <label key={key} className={`flex cursor-pointer gap-3 rounded border p-3 ${config.review[key] ? "border-green-800 bg-green-950/15" : "border-vscode-border"}`}><input type="checkbox" checked={config.review[key]} onChange={(event) => setConfig((current) => ({ ...current, review: { ...current.review, [key]: event.target.checked } }))}/><span><strong className="text-xs">{reviews[key].title}</strong><span className="mt-1 block text-[9px] text-vscode-muted">{reviews[key].detail}</span></span></label>)}</div>
    <div className="mt-4 flex flex-wrap justify-end gap-2"><button disabled={busy} onClick={() => void save()} className="rounded bg-vscode-accent px-3 py-2 text-xs font-semibold text-white disabled:opacity-40">Enregistrer la fiche finale</button>{pack.ready && taxReady && <><a href={apiUrl(`/annual-closing/${periodId}/filing-package?format=json`)} className="rounded border border-vscode-border px-3 py-2 text-xs">Exporter JSON contrôlé</a><a href={apiUrl(`/annual-closing/${periodId}/filing-package?format=xlsx`)} className="rounded bg-green-800 px-3 py-2 text-xs font-semibold text-white">Exporter le dossier Excel</a></>}</div>
  </section>;
}

function Summary({ title, children }: { title: string; children: React.ReactNode }) { return <details className="rounded border border-vscode-border p-3" open><summary className="cursor-pointer text-xs font-semibold">{title}</summary><div className="mt-2 space-y-1 text-[10px]">{children}</div></details>; }
