import { useMemo, useState } from "react";
import { api } from "../../api/client";
import { LocalizedNumberInput } from "../Common/LocalizedNumberInput";

type AdjustmentType = "reintegration" | "deduction";
type AdjustmentKind = "corporate_tax" | "fines_penalties" | "non_deductible_expense" | "excess_depreciation" | "vehicle_adjustment" | "loss_carryforward" | "other_reintegration" | "other_deduction";
export interface FiscalAdjustment { id: string; type: AdjustmentType; kind: AdjustmentKind; label: string; amount: number; accountNumber: string; reference: string; status: "draft" | "validated" | "cancelled"; cancellationReason?: string }
export interface AccountBalance { accountNumber: string; accountLabel: string; debit: number; credit: number; balance: number }

const euro = new Intl.NumberFormat("fr-FR", { style: "currency", currency: "EUR" });
const kinds: Record<AdjustmentKind, { label: string; type: AdjustmentType }> = {
  corporate_tax: { label: "Impôt sur les sociétés comptabilisé", type: "reintegration" },
  fines_penalties: { label: "Amendes et pénalités non déductibles", type: "reintegration" },
  non_deductible_expense: { label: "Charge non déductible", type: "reintegration" },
  excess_depreciation: { label: "Amortissement excédentaire", type: "reintegration" },
  vehicle_adjustment: { label: "Correction fiscale sur véhicule", type: "reintegration" },
  loss_carryforward: { label: "Déficit antérieur reportable", type: "deduction" },
  other_reintegration: { label: "Autre réintégration", type: "reintegration" },
  other_deduction: { label: "Autre déduction", type: "deduction" },
};

export function FiscalResultPanel({ periodId, balances, adjustments, review, summary, onSaved }: {
  periodId: string; balances: AccountBalance[]; adjustments: FiscalAdjustment[]; review: { confirmed: boolean; note: string };
  summary: { charges: number; products: number; accountingResult: number; reintegrations: number; deductions: number; fiscalResult: number; taxableProfit: number; taxLoss: number; draft: number; validated: number };
  onSaved: (data: unknown, notice: string) => void;
}) {
  const [filter, setFilter] = useState(""); const [kind, setKind] = useState<AdjustmentKind>("non_deductible_expense"); const [type, setType] = useState<AdjustmentType>("reintegration");
  const [label, setLabel] = useState(""); const [amount, setAmount] = useState(0); const [accountNumber, setAccountNumber] = useState(""); const [reference, setReference] = useState(""); const [editingId, setEditingId] = useState<string>();
  const [note, setNote] = useState(review.note); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [cancelId, setCancelId] = useState<string>(); const [cancelReason, setCancelReason] = useState("");
  const visibleBalances = useMemo(() => { const query = filter.trim().toLocaleLowerCase("fr-FR"); return query ? balances.filter((line) => `${line.accountNumber} ${line.accountLabel}`.toLocaleLowerCase("fr-FR").includes(query)) : balances; }, [balances, filter]);
  const request = async (method: "post" | "put" | "delete", path: string, body: object | undefined, notice: string) => { setBusy(true); setError(""); try { const response = method === "delete" ? await api.delete(path) : await api[method](path, body); onSaved(response.data, notice); return true; } catch (caught) { setError(caught instanceof Error ? caught.message : "Opération impossible."); return false; } finally { setBusy(false); } };
  const reset = () => { setEditingId(undefined); setKind("non_deductible_expense"); setType("reintegration"); setLabel(""); setAmount(0); setAccountNumber(""); setReference(""); };
  const save = async () => { const ok = await request(editingId ? "put" : "post", `/annual-closing/${periodId}/fiscal-adjustments${editingId ? `/${editingId}` : ""}`, { kind, type, label, amount, accountNumber, reference }, editingId ? "Correction fiscale modifiée." : "Correction fiscale enregistrée en brouillon."); if (ok) reset(); };
  const edit = (item: FiscalAdjustment) => { setEditingId(item.id); setKind(item.kind); setType(item.type); setLabel(item.label); setAmount(item.amount); setAccountNumber(item.accountNumber); setReference(item.reference); };
  const chooseKind = (value: AdjustmentKind) => { setKind(value); setType(kinds[value].type); if (!label.trim()) setLabel(kinds[value].label); };
  return <section className="rounded border border-vscode-border bg-vscode-panel p-4">
    <div><h2 className="text-sm font-semibold">Balance après inventaire et résultat fiscal</h2><p className="mt-1 text-[10px] text-vscode-muted">Le résultat fiscal est provisoire. Aucun taux d’IS n’est appliqué automatiquement tant que l’éligibilité au taux réduit et les crédits d’impôt ne sont pas contrôlés.</p></div>
    {error && <div className="mt-3 rounded border border-red-700 bg-red-950/30 p-2 text-xs text-red-300">{error}</div>}
    <div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-6">{[
      ["Produits classe 7", summary.products, "text-green-300"], ["Charges classe 6", summary.charges, "text-red-300"], ["Résultat comptable", summary.accountingResult, summary.accountingResult >= 0 ? "text-green-300" : "text-red-300"],
      ["Réintégrations", summary.reintegrations, "text-amber-300"], ["Déductions", summary.deductions, "text-blue-300"], ["Résultat fiscal", summary.fiscalResult, summary.fiscalResult >= 0 ? "text-green-300" : "text-red-300"],
    ].map(([title, value, color]) => <div key={String(title)} className="rounded border border-vscode-border bg-vscode-bg/40 p-3"><span className="text-[9px] uppercase text-vscode-muted">{title}</span><strong className={`mt-1 block text-sm ${color}`}>{euro.format(Number(value))}</strong></div>)}</div>
    <details className="mt-4 rounded border border-vscode-border"><summary className="cursor-pointer px-3 py-2 text-xs font-semibold">Voir la balance après inventaire · {balances.length} comptes</summary><div className="border-t border-vscode-border p-3"><input value={filter} onChange={(event) => setFilter(event.target.value)} placeholder="Filtrer par compte ou libellé…" className="mb-2 w-full rounded border border-vscode-border bg-vscode-bg p-2 text-xs"/><div className="max-h-80 overflow-auto"><table className="w-full text-xs"><thead className="sticky top-0 bg-vscode-panel text-vscode-muted"><tr><th className="p-1 text-left">Compte</th><th className="p-1 text-left">Libellé</th><th className="p-1 text-right">Débit</th><th className="p-1 text-right">Crédit</th><th className="p-1 text-right">Solde</th></tr></thead><tbody>{visibleBalances.map((line) => <tr key={line.accountNumber} className="border-t border-vscode-border"><td className="p-1 font-mono">{line.accountNumber}</td><td className="p-1">{line.accountLabel}</td><td className="p-1 text-right">{euro.format(line.debit)}</td><td className="p-1 text-right">{euro.format(line.credit)}</td><td className="p-1 text-right font-semibold">{euro.format(line.balance)}</td></tr>)}</tbody></table></div></div></details>
    <div className="mt-4 rounded border border-vscode-border bg-vscode-bg/40 p-3"><h3 className="text-xs font-semibold">Ajouter une correction fiscale</h3><p className="mt-1 text-[10px] text-amber-200/80">Une correction fiscale ne modifie pas le journal comptable : elle explique le passage du résultat comptable au résultat fiscal.</p><div className="mt-3 grid gap-2 md:grid-cols-3"><label className="text-[10px] text-vscode-muted">Nature<select value={kind} onChange={(event) => chooseKind(event.target.value as AdjustmentKind)} className="mt-1 w-full rounded border border-vscode-border bg-vscode-bg p-2 text-xs text-vscode-text">{Object.entries(kinds).map(([value, item]) => <option key={value} value={value}>{item.label}</option>)}</select></label><label className="text-[10px] text-vscode-muted">Sens<input readOnly value={type === "reintegration" ? "Réintégration (+)" : "Déduction (−)"} className="mt-1 w-full rounded border border-vscode-border bg-vscode-bg p-2 text-xs text-vscode-muted"/></label><label className="text-[10px] text-vscode-muted">Montant<LocalizedNumberInput value={amount} onValueChange={setAmount} min={0} className="mt-1 w-full rounded border border-vscode-border bg-vscode-bg p-2 text-xs text-right"/></label><label className="text-[10px] text-vscode-muted md:col-span-2">Libellé<input value={label} onChange={(event) => setLabel(event.target.value)} className="mt-1 w-full rounded border border-vscode-border bg-vscode-bg p-2 text-xs"/></label><label className="text-[10px] text-vscode-muted">Compte concerné<input value={accountNumber} onChange={(event) => setAccountNumber(event.target.value)} placeholder="Ex. 695000" className="mt-1 w-full rounded border border-vscode-border bg-vscode-bg p-2 text-xs"/></label><label className="text-[10px] text-vscode-muted md:col-span-3">Référence ou justification<input value={reference} onChange={(event) => setReference(event.target.value)} className="mt-1 w-full rounded border border-vscode-border bg-vscode-bg p-2 text-xs"/></label></div><div className="mt-3 flex justify-end gap-2">{editingId && <button onClick={reset} className="rounded border border-vscode-border px-3 py-2 text-xs">Annuler la modification</button>}<button disabled={busy || !label.trim() || amount <= 0} onClick={() => void save()} className="rounded bg-vscode-accent px-3 py-2 text-xs font-semibold text-white disabled:opacity-40">{editingId ? "Modifier le brouillon" : "Enregistrer en brouillon"}</button></div></div>
    <div className="mt-4 space-y-2">{adjustments.map((item) => <div key={item.id} className="rounded border border-vscode-border p-3 text-xs"><div className="flex flex-wrap items-center gap-2"><span className={`rounded px-2 py-1 text-[10px] ${item.status === "draft" ? "bg-amber-950 text-amber-300" : item.status === "cancelled" ? "bg-red-950 text-red-300" : "bg-green-950 text-green-300"}`}>{item.status === "draft" ? "Brouillon" : item.status === "cancelled" ? "Annulée" : "Validée"}</span><strong>{item.label}</strong><span className={item.type === "reintegration" ? "text-amber-300" : "text-blue-300"}>{item.type === "reintegration" ? "+" : "−"} {euro.format(item.amount)}</span>{item.accountNumber && <span className="font-mono text-vscode-muted">· {item.accountNumber}</span>}</div>{item.reference && <p className="mt-1 text-[10px] text-vscode-muted">Justification : {item.reference}</p>}
      {item.status === "draft" && <div className="mt-2 flex justify-end gap-2"><button onClick={() => edit(item)} className="rounded border border-vscode-border px-2 py-1">Modifier</button><button disabled={busy} onClick={() => void request("delete", `/annual-closing/${periodId}/fiscal-adjustments/${item.id}`, undefined, "Brouillon fiscal supprimé.")} className="rounded border border-red-800 px-2 py-1 text-red-300">Supprimer</button><button disabled={busy} onClick={() => void request("post", `/annual-closing/${periodId}/fiscal-adjustments/${item.id}/validate`, {}, "Correction fiscale validée.")} className="rounded bg-green-800 px-2 py-1 text-white">Valider</button></div>}
      {item.status === "validated" && (cancelId === item.id ? <div className="mt-2 flex flex-wrap justify-end gap-2"><input value={cancelReason} onChange={(event) => setCancelReason(event.target.value)} placeholder="Motif obligatoire" className="min-w-72 rounded border border-vscode-border bg-vscode-bg p-1.5"/><button onClick={() => { setCancelId(undefined); setCancelReason(""); }} className="rounded border border-vscode-border px-2 py-1">Retour</button><button disabled={busy || !cancelReason.trim()} onClick={async () => { const ok = await request("post", `/annual-closing/${periodId}/fiscal-adjustments/${item.id}/cancel`, { reason: cancelReason }, "Correction fiscale annulée."); if (ok) { setCancelId(undefined); setCancelReason(""); } }} className="rounded border border-red-800 px-2 py-1 text-red-300">Confirmer l’annulation</button></div> : <div className="mt-2 flex justify-end"><button onClick={() => setCancelId(item.id)} className="rounded border border-red-900 px-2 py-1 text-red-300">Annuler</button></div>)}{item.cancellationReason && <p className="mt-2 text-[10px] text-red-300">Motif : {item.cancellationReason}</p>}</div>)}{!adjustments.length && <p className="py-4 text-center text-xs text-vscode-muted">Aucune correction fiscale saisie.</p>}</div>
    <div className={`mt-4 rounded border p-3 ${review.confirmed ? "border-green-800 bg-green-950/15" : "border-amber-800 bg-amber-950/15"}`}><label className="text-[10px] text-vscode-muted">Note de revue fiscale<textarea value={note} onChange={(event) => setNote(event.target.value)} placeholder="Ex. comptes 6 examinés, aucune autre charge non déductible identifiée…" className="mt-1 min-h-16 w-full rounded border border-vscode-border bg-vscode-bg p-2 text-xs text-vscode-text"/></label><div className="mt-2 flex flex-wrap items-center justify-between gap-2"><span className="text-[10px] text-vscode-muted">{summary.taxableProfit > 0 ? `Base fiscale positive provisoire : ${euro.format(summary.taxableProfit)}` : `Déficit fiscal provisoire : ${euro.format(summary.taxLoss)}`}</span><button disabled={busy || summary.draft > 0} onClick={() => void request("put", `/annual-closing/${periodId}/fiscal-review`, { confirmed: !review.confirmed, note }, review.confirmed ? "Confirmation fiscale retirée." : "Revue fiscale confirmée.")} className={`rounded px-3 py-2 text-xs font-semibold disabled:opacity-40 ${review.confirmed ? "border border-vscode-border" : "bg-green-800 text-white"}`}>{review.confirmed ? "Rouvrir la revue" : "Confirmer la revue fiscale"}</button></div></div>
  </section>;
}
