import { useMemo, useState } from "react";
import { api } from "../../api/client";
import { LocalizedNumberInput } from "../Common/LocalizedNumberInput";

export type InventoryKind = "customer_receivable" | "supplier_payable" | "depreciation" | "prepaid_expense" | "deferred_revenue" | "accrued_expense" | "accrued_income" | "vat_adjustment" | "shareholder_current_account" | "loan" | "corporate_tax" | "other";
export interface InventoryLine { id: string; accountNumber: string; accountLabel: string; debit: number; credit: number }
export interface InventoryEntry { id: string; date: string; kind: InventoryKind; label: string; reference: string; lines: InventoryLine[]; status: "draft" | "validated" | "cancelled"; reversalOf?: string; cancellationReason?: string }

const euro = new Intl.NumberFormat("fr-FR", { style: "currency", currency: "EUR" });
const kinds: Record<InventoryKind, string> = {
  customer_receivable: "Créance client", supplier_payable: "Dette fournisseur", depreciation: "Amortissement",
  prepaid_expense: "Charge constatée d’avance", deferred_revenue: "Produit constaté d’avance", accrued_expense: "Charge à payer",
  accrued_income: "Produit à recevoir", vat_adjustment: "Régularisation de TVA", shareholder_current_account: "Compte courant d’associé",
  loan: "Emprunt", corporate_tax: "Impôt sur les sociétés", other: "Autre écriture",
};
const suggestions: Record<InventoryKind, [string, string, "debit" | "credit"][]> = {
  customer_receivable: [["411000", "Clients", "debit"], ["706000", "Prestations de services", "credit"]],
  supplier_payable: [["606000", "Achats non stockés", "debit"], ["408100", "Fournisseurs - factures non parvenues", "credit"]],
  depreciation: [["681120", "Dotations aux amortissements", "debit"], ["281800", "Amortissements des autres immobilisations", "credit"]],
  prepaid_expense: [["486000", "Charges constatées d’avance", "debit"], ["606000", "Achats non stockés", "credit"]],
  deferred_revenue: [["706000", "Prestations de services", "debit"], ["487000", "Produits constatés d’avance", "credit"]],
  accrued_expense: [["606000", "Achats non stockés", "debit"], ["408100", "Fournisseurs - factures non parvenues", "credit"]],
  accrued_income: [["418100", "Clients - factures à établir", "debit"], ["706000", "Prestations de services", "credit"]],
  vat_adjustment: [["445660", "TVA déductible", "debit"], ["445510", "TVA à décaisser", "credit"]],
  shareholder_current_account: [["512000", "Banque", "debit"], ["455100", "Associés - comptes courants", "credit"]],
  loan: [["512000", "Banque", "debit"], ["164000", "Emprunts auprès des établissements de crédit", "credit"]],
  corporate_tax: [["695000", "Impôts sur les bénéfices", "debit"], ["444000", "État - impôts sur les bénéfices", "credit"]],
  other: [["", "", "debit"], ["", "", "credit"]],
};
const emptyLines = (kind: InventoryKind): InventoryLine[] => suggestions[kind].map(([accountNumber, accountLabel, side]) => ({ id: crypto.randomUUID(), accountNumber, accountLabel, debit: side === "debit" ? 0 : 0, credit: side === "credit" ? 0 : 0 }));

export function InventoryJournal({ period, entries, summary, onSaved }: { period: { id: string; startDate: string; endDate: string }; entries: InventoryEntry[]; summary: { draft: number; posted: number; debit: number; credit: number }; onSaved: (data: unknown, notice: string) => void }) {
  const [kind, setKind] = useState<InventoryKind>("accrued_expense"); const [date, setDate] = useState(period.endDate); const [label, setLabel] = useState(""); const [reference, setReference] = useState(""); const [lines, setLines] = useState<InventoryLine[]>(emptyLines("accrued_expense"));
  const [editingId, setEditingId] = useState<string>(); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [cancelId, setCancelId] = useState<string>(); const [cancelReason, setCancelReason] = useState("");
  const totals = useMemo(() => ({ debit: lines.reduce((sum, line) => sum + line.debit, 0), credit: lines.reduce((sum, line) => sum + line.credit, 0) }), [lines]);
  const reset = (nextKind: InventoryKind = kind) => { setEditingId(undefined); setDate(period.endDate); setKind(nextKind); setLabel(""); setReference(""); setLines(emptyLines(nextKind)); };
  const request = async (method: "post" | "put" | "delete", path: string, body: object | undefined, notice: string) => { setBusy(true); setError(""); try { const response = method === "delete" ? await api.delete(path) : await api[method](path, body); onSaved(response.data, notice); return true; } catch (caught) { setError(caught instanceof Error ? caught.message : "Opération impossible."); return false; } finally { setBusy(false); } };
  const save = async () => { const ok = await request(editingId ? "put" : "post", `/annual-closing/${period.id}/inventory${editingId ? `/${editingId}` : ""}`, { date, kind, label, reference, lines }, editingId ? "Brouillon modifié." : "Écriture enregistrée en brouillon."); if (ok) reset(); };
  const edit = (entry: InventoryEntry) => { setEditingId(entry.id); setKind(entry.kind); setDate(entry.date); setLabel(entry.label); setReference(entry.reference); setLines(entry.lines); };
  const setAmount = (index: number, side: "debit" | "credit", value: number) => setLines((current) => current.map((line, lineIndex) => lineIndex === index ? { ...line, [side]: value, [side === "debit" ? "credit" : "debit"]: value ? 0 : line[side === "debit" ? "credit" : "debit"] } : line));
  return <section className="rounded border border-vscode-border bg-vscode-panel p-4">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-sm font-semibold">Journal d’inventaire</h2><p className="mt-1 text-[10px] text-vscode-muted">Les comptes suggérés sont des points de départ à vérifier. Une écriture validée est verrouillée ; son annulation crée une contrepassation.</p></div><div className="text-right text-[10px] text-vscode-muted"><strong className="block text-xs text-vscode-text">{summary.posted} comptabilisée(s) · {summary.draft} brouillon(s)</strong>Débit {euro.format(summary.debit)} · Crédit {euro.format(summary.credit)}</div></div>
    {error && <div className="mt-3 rounded border border-red-700 bg-red-950/30 p-2 text-xs text-red-300">{error}</div>}
    <div className="mt-4 rounded border border-vscode-border bg-vscode-bg/40 p-3"><div className="grid gap-2 md:grid-cols-4"><label className="text-[10px] text-vscode-muted">Type<select value={kind} onChange={(event) => { const next = event.target.value as InventoryKind; setKind(next); setLines(emptyLines(next)); }} className="mt-1 w-full rounded border border-vscode-border bg-vscode-bg p-2 text-xs text-vscode-text">{Object.entries(kinds).map(([value, text]) => <option key={value} value={value}>{text}</option>)}</select></label><label className="text-[10px] text-vscode-muted">Date<input type="date" min={period.startDate} max={period.endDate} value={date} onChange={(event) => setDate(event.target.value)} className="mt-1 w-full rounded border border-vscode-border bg-vscode-bg p-2 text-xs text-vscode-text"/></label><label className="text-[10px] text-vscode-muted md:col-span-2">Libellé<input value={label} onChange={(event) => setLabel(event.target.value)} placeholder="Ex. Facture fournisseur à recevoir" className="mt-1 w-full rounded border border-vscode-border bg-vscode-bg p-2 text-xs text-vscode-text"/></label><label className="text-[10px] text-vscode-muted md:col-span-4">Référence ou pièce<input value={reference} onChange={(event) => setReference(event.target.value)} placeholder="Facultatif" className="mt-1 w-full rounded border border-vscode-border bg-vscode-bg p-2 text-xs text-vscode-text"/></label></div>
      <div className="mt-3 overflow-auto"><table className="w-full text-xs"><thead className="text-vscode-muted"><tr><th className="p-1 text-left">Compte</th><th className="p-1 text-left">Libellé</th><th className="p-1 text-right">Débit</th><th className="p-1 text-right">Crédit</th><th/></tr></thead><tbody>{lines.map((line, index) => <tr key={line.id}><td className="p-1"><input value={line.accountNumber} onChange={(event) => setLines((current) => current.map((item, i) => i === index ? { ...item, accountNumber: event.target.value } : item))} className="w-28 rounded border border-vscode-border bg-vscode-bg p-1.5"/></td><td className="p-1"><input value={line.accountLabel} onChange={(event) => setLines((current) => current.map((item, i) => i === index ? { ...item, accountLabel: event.target.value } : item))} className="min-w-52 w-full rounded border border-vscode-border bg-vscode-bg p-1.5"/></td><td className="p-1"><LocalizedNumberInput value={line.debit} onValueChange={(value) => setAmount(index, "debit", value)} min={0} className="w-28 rounded border border-vscode-border bg-vscode-bg p-1.5 text-right"/></td><td className="p-1"><LocalizedNumberInput value={line.credit} onValueChange={(value) => setAmount(index, "credit", value)} min={0} className="w-28 rounded border border-vscode-border bg-vscode-bg p-1.5 text-right"/></td><td><button onClick={() => setLines((current) => current.filter((_, i) => i !== index))} className="px-2 text-red-400">×</button></td></tr>)}</tbody><tfoot><tr className="border-t border-vscode-border font-semibold"><td colSpan={2} className="p-2 text-right">Totaux</td><td className="p-2 text-right">{euro.format(totals.debit)}</td><td className="p-2 text-right">{euro.format(totals.credit)}</td><td/></tr></tfoot></table></div>
      <div className="mt-3 flex flex-wrap justify-end gap-2"><button onClick={() => setLines((current) => [...current, { id: crypto.randomUUID(), accountNumber: "", accountLabel: "", debit: 0, credit: 0 }])} className="rounded border border-vscode-border px-3 py-2 text-xs">+ Ligne</button>{editingId && <button onClick={() => reset()} className="rounded border border-vscode-border px-3 py-2 text-xs">Annuler la modification</button>}<button disabled={busy || !label.trim() || lines.length < 2 || totals.debit <= 0 || Math.abs(totals.debit - totals.credit) > .009} onClick={() => void save()} className="rounded bg-vscode-accent px-3 py-2 text-xs font-semibold text-white disabled:opacity-40">{editingId ? "Modifier le brouillon" : "Enregistrer en brouillon"}</button></div>
    </div>
    <div className="mt-4 space-y-2">{entries.map((entry) => <div key={entry.id} className="rounded border border-vscode-border p-3 text-xs"><div className="flex flex-wrap items-center gap-2"><span className={`rounded px-2 py-1 text-[10px] ${entry.status === "draft" ? "bg-amber-950 text-amber-300" : entry.status === "cancelled" ? "bg-red-950 text-red-300" : "bg-green-950 text-green-300"}`}>{entry.status === "draft" ? "Brouillon" : entry.status === "cancelled" ? "Annulée" : entry.reversalOf ? "Contrepassation" : "Validée"}</span><strong>{entry.date} · {entry.label}</strong><span className="ml-auto text-vscode-muted">{euro.format(entry.lines.reduce((sum, line) => sum + line.debit, 0))}</span></div><div className="mt-2 grid gap-1 text-[10px] text-vscode-muted">{entry.lines.map((line) => <div key={line.id} className="flex gap-2"><span className="w-16 font-mono">{line.accountNumber}</span><span className="flex-1">{line.accountLabel}</span><span>D {euro.format(line.debit)}</span><span>C {euro.format(line.credit)}</span></div>)}</div>
      {entry.status === "draft" && <div className="mt-2 flex justify-end gap-2"><button onClick={() => edit(entry)} className="rounded border border-vscode-border px-2 py-1">Modifier</button><button disabled={busy} onClick={() => void request("delete", `/annual-closing/${period.id}/inventory/${entry.id}`, undefined, "Brouillon supprimé.")} className="rounded border border-red-800 px-2 py-1 text-red-300">Supprimer</button><button disabled={busy} onClick={() => void request("post", `/annual-closing/${period.id}/inventory/${entry.id}/validate`, {}, "Écriture validée et intégrée au journal OD.")} className="rounded bg-green-800 px-2 py-1 text-white">Valider l’écriture</button></div>}
      {entry.status === "validated" && !entry.reversalOf && (cancelId === entry.id ? <div className="mt-2 flex flex-wrap justify-end gap-2"><input value={cancelReason} onChange={(event) => setCancelReason(event.target.value)} placeholder="Motif obligatoire" className="min-w-72 rounded border border-vscode-border bg-vscode-bg p-1.5"/><button onClick={() => { setCancelId(undefined); setCancelReason(""); }} className="rounded border border-vscode-border px-2 py-1">Retour</button><button disabled={busy || !cancelReason.trim()} onClick={async () => { const ok = await request("post", `/annual-closing/${period.id}/inventory/${entry.id}/cancel`, { reason: cancelReason }, "Écriture annulée par contrepassation."); if (ok) { setCancelId(undefined); setCancelReason(""); } }} className="rounded border border-red-800 px-2 py-1 text-red-300">Confirmer la contrepassation</button></div> : <div className="mt-2 flex justify-end"><button onClick={() => setCancelId(entry.id)} className="rounded border border-red-900 px-2 py-1 text-red-300">Annuler par contrepassation</button></div>)}
      {entry.cancellationReason && <p className="mt-2 text-[10px] text-red-300">Motif : {entry.cancellationReason}</p>}</div>)}{!entries.length && <p className="py-6 text-center text-xs text-vscode-muted">Aucune écriture d’inventaire enregistrée pour cet exercice.</p>}</div>
  </section>;
}
