import { useEffect, useState } from "react";
import { fetchHouseholdFinance } from "../../api/client";
import type { HouseholdFinanceSnapshot } from "../../types";

const euro = new Intl.NumberFormat("fr-FR", { style: "currency", currency: "EUR" });
const currentMonth = () => new Date().toISOString().slice(0, 7);

export function HouseholdFinanceView({ householdId }: { householdId: string }) {
  const [month, setMonth] = useState(currentMonth()); const [data, setData] = useState<HouseholdFinanceSnapshot | null>(null); const [error, setError] = useState("");
  useEffect(() => { fetchHouseholdFinance(householdId, month).then(setData).catch((e) => setError(e instanceof Error ? e.message : "Chargement impossible")); }, [householdId, month]);
  if (!data) return <div className="flex h-full items-center justify-center text-sm text-vscode-muted">Chargement du foyer…</div>;
  return <div className="h-full overflow-auto bg-vscode-bg p-6 text-vscode-text"><div className="flex items-end justify-between gap-4"><div><div className="text-[10px] uppercase tracking-[.2em] text-vscode-muted">Vue consolidée sans doublon</div><h1 className="mt-1 text-2xl font-semibold">{data.household.name}</h1><p className="mt-1 text-xs text-vscode-muted">Les flux du foyer et de ses membres sont consolidés, tandis que les virements internes sont neutralisés.</p></div><input type="month" value={month} onChange={(e) => setMonth(e.target.value)} className="rounded border border-vscode-border bg-vscode-panel px-3 py-2 text-xs" /></div>{error && <p className="mt-4 text-xs text-red-400">{error}</p>}
    <div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[["Solde des comptes", data.summary.balance], ["Revenus du mois", data.summary.income], ["Dépenses du mois", data.summary.expenses], ["Reste du mois", data.summary.net], ["Virements neutralisés", data.summary.internalTransfers]].map(([label, value], index) => <div key={label} className="rounded border border-vscode-border bg-vscode-panel p-4"><div className="text-[10px] uppercase text-vscode-muted">{label}</div><div className={`mt-1 text-xl font-semibold ${index === 2 ? "text-red-400" : index === 1 || index === 3 ? "text-green-400" : ""}`}>{index === 4 ? value : euro.format(Number(value))}</div></div>)}</div>
    <div className="mt-5 grid gap-5 xl:grid-cols-[1fr_2fr]"><section className="rounded border border-vscode-border bg-vscode-panel p-4"><h2 className="text-sm font-semibold">Membres</h2><div className="mt-3 space-y-2">{data.members.map((member) => <div key={member.id} className="rounded border border-vscode-border p-3"><div className="font-semibold">{member.name}</div><div className="mt-1 grid grid-cols-3 gap-2 text-[10px]"><span className="text-green-400">+ {euro.format(member.income)}</span><span className="text-red-400">− {euro.format(member.expenses)}</span><span>{euro.format(member.net)}</span></div></div>)}{!data.members.length && <p className="text-xs text-vscode-muted">Ajoute des liens « Membre du foyer » dans la structure.</p>}</div><h2 className="mt-5 text-sm font-semibold">Comptes visibles</h2><div className="mt-2 space-y-1">{data.accounts.map((account) => <div key={account.id} className="flex justify-between rounded border border-vscode-border px-3 py-2 text-xs"><span>{account.name}</span><span>{euro.format(account.balance ?? 0)}</span></div>)}</div></section>
      <section className="rounded border border-vscode-border bg-vscode-panel"><div className="border-b border-vscode-border p-4"><h2 className="text-sm font-semibold">Flux consolidés</h2></div><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="text-[10px] uppercase text-vscode-muted"><tr><th className="p-3">Date / libellé</th><th>Compte</th><th>Affectation</th><th className="p-3 text-right">Part du foyer</th></tr></thead><tbody>{data.transactions.map((transaction) => <tr key={transaction.key} className={`border-t border-vscode-border ${transaction.internalTransfer ? "opacity-50" : ""}`}><td className="p-3"><div className="font-semibold">{transaction.label}</div><div className="text-[10px] text-vscode-muted">{transaction.date}{transaction.internalTransfer ? " · virement interne neutralisé" : ""}</div></td><td>{transaction.accountName}</td><td>{transaction.allocatedScopes.map((scope) => <span key={scope.scopeId} className="mr-1 rounded bg-purple-950/40 px-2 py-1 text-[10px] text-purple-300">{scope.name}</span>)}</td><td className={`p-3 text-right font-semibold ${transaction.allocatedAmount >= 0 ? "text-green-400" : "text-red-400"}`}>{euro.format(transaction.allocatedAmount)}</td></tr>)}</tbody></table></div></section></div>
  </div>;
}
