import { useEffect, useMemo, useState } from "react";
import { ensureAccountingDossier, fetchActiveCompany, fetchHouseholdFinance, saveHouseholdFinanceBudgets, setActiveCompanyApi } from "../../api/client";
import { useAppStore } from "../../stores/appStore";
import type { HouseholdFinanceSnapshot, PersonalBudget, PersonalCategory, TabType } from "../../types";
import { LocalizedNumberInput } from "../Common/LocalizedNumberInput";

const euro = new Intl.NumberFormat("fr-FR", { style: "currency", currency: "EUR" });
const currentMonth = () => new Date().toISOString().slice(0, 7);
function householdCategory(label: string, category: string): PersonalCategory { const source = `${label} ${category}`.toLowerCase(); if (/restaurant|repas/.test(source)) return "dining"; if (/aliment|boulanger|course/.test(source)) return "groceries"; if (/loyer|logement|rent/.test(source)) return "housing"; if (/engie|edf|énergie|electric|gaz|eau/.test(source)) return "utilities"; if (/assurance|mutuelle/.test(source)) return "insurance"; if (/transport|sncf|ratp|uber|carbur/.test(source)) return "transport"; if (/abonnement|subscription/.test(source)) return "subscriptions"; return "personal_misc"; }

export function HouseholdFinanceView({ householdId }: { householdId: string }) {
  const openTab = useAppStore((store) => store.openTab);
  const [month, setMonth] = useState(currentMonth()); const [data, setData] = useState<HouseholdFinanceSnapshot | null>(null); const [error, setError] = useState("");
  const [section, setSection] = useState<"overview" | "transactions" | "budgets">("overview"); const [budgets, setBudgets] = useState<PersonalBudget[]>([]); const [notice, setNotice] = useState("");
  useEffect(() => { fetchHouseholdFinance(householdId, month).then((snapshot) => { setData(snapshot); setBudgets(snapshot.budgets); }).catch((e) => setError(e instanceof Error ? e.message : "Chargement impossible")); }, [householdId, month]);
  const spending = useMemo(() => { const result: Record<string, number> = {}; for (const transaction of data?.transactions ?? []) if (!transaction.internalTransfer && transaction.allocatedAmount < 0) { const category = householdCategory(transaction.label, transaction.category); result[category] = (result[category] ?? 0) + Math.abs(transaction.allocatedAmount); } return result; }, [data]);
  const expenseCategories = data?.categories.filter((category) => category.kind !== "income") ?? [];
  function setBudget(category: PersonalCategory, monthlyLimit: number) { setBudgets((current) => current.some((item) => item.category === category) ? current.map((item) => item.category === category ? { ...item, monthlyLimit } : item) : [...current, { category, monthlyLimit }]); }
  async function saveBudgets() { try { setBudgets(await saveHouseholdFinanceBudgets(householdId, budgets.filter((item) => item.monthlyLimit > 0))); setNotice("Budgets du foyer enregistrés."); } catch (e) { setError(e instanceof Error ? e.message : "Enregistrement impossible"); } }
  async function openDossierModule(type: TabType, title: string) { setError(""); try { const dossier = await ensureAccountingDossier(householdId); if (!dossier.workspaceId) throw new Error("Espace de données indisponible."); const businessWorkspace = await fetchActiveCompany(); if (businessWorkspace) sessionStorage.setItem("comptaos:last-business-workspace", businessWorkspace.id); await setActiveCompanyApi(dossier.workspaceId); openTab({ id: `dossier:household:${householdId}:${type}`, title, type, path: `workspace=${encodeURIComponent(dossier.workspaceId)}` }); } catch (e) { setError(e instanceof Error ? e.message : "Ouverture du dossier impossible."); } }
  if (!data) return <div className="flex h-full items-center justify-center text-sm text-vscode-muted">Chargement du foyer…</div>;
  return <div className="h-full overflow-auto bg-vscode-bg text-vscode-text">
    <header className="border-b border-vscode-border px-7 py-5"><div className="text-[10px] uppercase tracking-[.2em] text-vscode-muted">Comptabilité du foyer</div><div className="mt-2 flex flex-wrap items-end gap-4"><div className="min-w-0 flex-1"><h1 className="text-2xl font-semibold">{data.household.name}</h1><p className="mt-1 text-xs text-vscode-muted">Dossier commun alimenté par les transactions affectées au foyer et à ses membres, sans double comptage.</p></div><div className="flex flex-wrap items-center gap-2"><button onClick={() => void openDossierModule("banking", "Banque du foyer")} className="rounded border border-purple-700 px-3 py-2 text-xs text-purple-300 hover:bg-purple-950/30">Connecter une banque</button><button onClick={() => void openDossierModule("transactions", "Transactions du foyer")} className="rounded border border-vscode-border px-3 py-2 text-xs hover:border-purple-600">Saisir / justifier</button><button onClick={() => void openDossierModule("recurring", "Frais récurrents du foyer")} className="rounded border border-vscode-border px-3 py-2 text-xs hover:border-purple-600">Récurrents</button><input type="month" value={month} onChange={(e) => setMonth(e.target.value)} className="rounded border border-vscode-border bg-vscode-panel px-3 py-2 text-xs" /></div></div></header>
    <nav className="flex gap-1 border-b border-vscode-border px-7 py-2">{([['overview','Vue d’ensemble'],['transactions',`Mouvements (${data.transactions.length})`],['budgets','Budgets communs']] as const).map(([id,label]) => <button key={id} onClick={() => setSection(id)} className={`rounded px-3 py-1.5 text-xs ${section === id ? "bg-purple-700 text-white" : "text-vscode-muted hover:bg-vscode-panel"}`}>{label}</button>)}</nav>
    {(error || notice) && <div className={`mx-7 mt-4 rounded border px-4 py-2 text-xs ${error ? "border-red-700 text-red-300" : "border-green-700 text-green-300"}`}>{error || notice}</div>}
    {section === "overview" && <main className="p-7"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[["Solde des comptes", data.summary.balance], ["Revenus du mois", data.summary.income], ["Dépenses du mois", -data.summary.expenses], ["Reste du mois", data.summary.net], ["Virements neutralisés", data.summary.internalTransfers]].map(([label, value], index) => <div key={label} className="rounded border border-vscode-border bg-vscode-panel p-4"><div className="text-[10px] uppercase text-vscode-muted">{label}</div><div className={`mt-1 text-xl font-semibold ${index === 2 ? "text-red-400" : index === 1 || index === 3 ? "text-green-400" : ""}`}>{index === 4 ? value : euro.format(Number(value))}</div></div>)}</div><div className="mt-5 grid gap-5 xl:grid-cols-2"><section className="rounded border border-vscode-border bg-vscode-panel p-4"><h2 className="text-sm font-semibold">Membres du dossier</h2><div className="mt-3 space-y-2">{data.members.map((member) => <div key={member.id} className="rounded border border-vscode-border p-3"><strong>{member.name}</strong><div className="mt-1 grid grid-cols-3 text-[10px]"><span className="text-green-400">+ {euro.format(member.income)}</span><span className="text-red-400">− {euro.format(member.expenses)}</span><span>{euro.format(member.net)}</span></div></div>)}{!data.members.length && <p className="text-xs text-vscode-muted">Ajoute des liens « Membre du foyer » dans la structure.</p>}</div></section><section className="rounded border border-vscode-border bg-vscode-panel p-4"><h2 className="text-sm font-semibold">Comptes du foyer</h2><div className="mt-3 space-y-2">{data.accounts.map((account) => <div key={account.id} className="flex justify-between rounded border border-vscode-border px-3 py-2 text-xs"><span>{account.name}</span><strong>{euro.format(account.balance ?? 0)}</strong></div>)}{!data.accounts.length && <p className="text-xs text-vscode-muted">Aucun compte ou mouvement encore affecté au foyer.</p>}</div></section></div></main>}
    {section === "transactions" && <main className="p-7"><div className="overflow-x-auto rounded border border-vscode-border"><table className="w-full min-w-[820px] text-left text-xs"><thead className="bg-vscode-panel text-[10px] uppercase text-vscode-muted"><tr><th className="p-3">Date / libellé</th><th>Compte</th><th>Affectation</th><th className="p-3 text-right">Part du foyer</th></tr></thead><tbody>{data.transactions.map((transaction) => <tr key={transaction.key} className={`border-t border-vscode-border ${transaction.internalTransfer ? "opacity-50" : ""}`}><td className="p-3"><strong>{transaction.label}</strong><div className="text-[10px] text-vscode-muted">{transaction.date}{transaction.internalTransfer ? " · virement interne neutralisé" : ""}</div></td><td>{transaction.accountName}</td><td>{transaction.allocatedScopes.map((scope) => <span key={scope.scopeId} className="mr-1 rounded bg-purple-950/40 px-2 py-1 text-[10px] text-purple-300">{scope.name}</span>)}</td><td className={`p-3 text-right font-semibold ${transaction.allocatedAmount >= 0 ? "text-green-400" : "text-red-400"}`}>{euro.format(transaction.allocatedAmount)}</td></tr>)}</tbody></table></div></main>}
    {section === "budgets" && <main className="p-7"><div className="flex items-center justify-between"><div><h2 className="text-sm font-semibold">Budgets mensuels communs</h2><p className="mt-1 text-[11px] text-vscode-muted">Ces limites concernent uniquement les flux affectés au foyer.</p></div><button onClick={() => void saveBudgets()} className="rounded bg-purple-700 px-4 py-2 text-xs font-semibold text-white">Enregistrer</button></div><div className="mt-5 grid gap-3 lg:grid-cols-2">{expenseCategories.map((category) => { const budget = budgets.find((item) => item.category === category.id)?.monthlyLimit ?? 0; const spent = spending[category.id] ?? 0; return <div key={category.id} className="rounded border border-vscode-border bg-vscode-panel p-3"><div className="flex items-center gap-3"><span className="flex-1 text-xs">{category.label}</span><span className="text-[10px] text-vscode-muted">{euro.format(spent)} dépensés</span><LocalizedNumberInput value={budget} onValueChange={(value) => setBudget(category.id, value)} min={0} className="w-24 rounded border border-vscode-border bg-vscode-bg px-2 py-1 text-right text-xs"/></div></div>; })}</div></main>}
  </div>;
}
