import { useEffect, useMemo, useState } from "react";
import { fetchFinanceAllocations, saveFinanceAccountAssignment, saveFinanceBatchAllocation, saveFinanceTransactionAllocations } from "../../api/client";
import type { AccountUsage, AllocatedTransaction, FinanceAllocation, FinanceAllocationSnapshot } from "../../types";

const euro = new Intl.NumberFormat("fr-FR", { style: "currency", currency: "EUR" });
const sourceLabels = { manual: "Répartition manuelle", rule: "Règle automatique", account: "Règle du compte", relation: "Lien de structure", unassigned: "À arbitrer" } as const;
const currentMonth = () => new Date().toISOString().slice(0, 7);
const parseAmount = (value: string) => Number(value.replace(",", "."));

export function AllocationView() {
  const [month, setMonth] = useState(currentMonth());
  const [data, setData] = useState<FinanceAllocationSnapshot | null>(null);
  const [onlyUnassigned, setOnlyUnassigned] = useState(false);
  const [query, setQuery] = useState("");
  const [selected, setSelected] = useState<Set<string>>(new Set());
  const [batchScope, setBatchScope] = useState("");
  const [editing, setEditing] = useState<AllocatedTransaction | null>(null);
  const [parts, setParts] = useState<Array<{ scopeId: string; amount: string }>>([]);
  const [rememberRule, setRememberRule] = useState(false);
  const [error, setError] = useState("");
  const [busy, setBusy] = useState(false);
  const reload = () => fetchFinanceAllocations(month).then(setData).catch((e) => setError(e instanceof Error ? e.message : "Chargement impossible"));
  useEffect(() => { setSelected(new Set()); void reload(); }, [month]);
  const rows = useMemo(() => (data?.transactions ?? []).filter((transaction) => (!onlyUnassigned || !transaction.allocations.length) && (!query || `${transaction.label} ${transaction.amount_ttc} ${transaction.accountName}`.toLowerCase().includes(query.toLowerCase()))), [data, onlyUnassigned, query]);
  const scopeName = (id: string) => data?.scopes.find((scope) => scope.id === id)?.name ?? "Périmètre inconnu";
  const openEditor = (transaction: AllocatedTransaction) => { setEditing(transaction); setParts((transaction.allocations.length ? transaction.allocations : [{ scopeId: data?.scopes[0]?.id ?? "", amount: transaction.amount_ttc }]).map((part) => ({ scopeId: part.scopeId, amount: String(part.amount).replace(".", ",") }))); setRememberRule(false); setError(""); };
  async function saveSplit() {
    if (!editing) return;
    const allocations: FinanceAllocation[] = parts.map((part) => ({ scopeId: part.scopeId, amount: parseAmount(part.amount) }));
    setBusy(true); setError("");
    try { await saveFinanceTransactionAllocations(month, editing.key, allocations, rememberRule); setEditing(null); await reload(); }
    catch (e) { setError(e instanceof Error ? e.message : "Répartition impossible"); }
    finally { setBusy(false); }
  }
  async function applyBatch() { setBusy(true); setError(""); try { await saveFinanceBatchAllocation(month, [...selected], batchScope); setSelected(new Set()); await reload(); } catch (e) { setError(e instanceof Error ? e.message : "Affectation impossible"); } finally { setBusy(false); } }
  if (!data) return <div className="flex h-full items-center justify-center text-sm text-vscode-muted">Chargement de la répartition…</div>;
  return <div className="h-full overflow-auto bg-vscode-bg p-6 text-vscode-text">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><div className="text-[10px] uppercase tracking-[.2em] text-vscode-muted">Big picture / affectation exceptionnelle</div><h1 className="mt-1 text-2xl font-semibold">Affectation des flux aux dossiers</h1><p className="mt-1 max-w-3xl text-xs text-vscode-muted">Un compte dédié à une personne ou une entreprise affecte normalement ses opérations automatiquement. Utilise cet écran seulement pour un compte partagé ou mixte, une transaction importée dans le mauvais dossier, ou une dépense à répartir entre plusieurs périmètres. La transaction bancaire reste unique.</p></div><input type="month" value={month} onChange={(e) => setMonth(e.target.value)} className="rounded border border-vscode-border bg-vscode-panel px-3 py-2 text-xs" /></div>
    {error && <div className="mt-4 rounded border border-red-700 bg-red-950/30 px-4 py-2 text-xs text-red-300">{error}</div>}
    <div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["Transactions", data.transactions.length], ["À arbitrer", data.unassignedCount], ["Comptes mixtes", data.accounts.filter((a) => a.usage === "mixed").length], ["Répartitions explicites", data.transactions.filter((t) => t.allocationSource === "manual").length]].map(([label, value]) => <div key={label} className="rounded border border-vscode-border bg-vscode-panel p-4"><div className="text-[10px] uppercase text-vscode-muted">{label}</div><div className="mt-1 text-2xl font-semibold">{value}</div></div>)}</div>
    <section className="mt-5 rounded border border-vscode-border bg-vscode-panel p-4"><h2 className="text-sm font-semibold">Usage par défaut des comptes</h2><p className="mt-1 text-[11px] text-vscode-muted">Un compte mixte sans périmètre par défaut force un arbitrage transaction par transaction.</p><div className="mt-3 grid gap-3 lg:grid-cols-2">{data.accounts.map((account) => <div key={account.id} className="grid gap-2 rounded border border-vscode-border p-3 sm:grid-cols-[1fr_150px_1fr]"><div><div className="text-xs font-semibold">{account.name}</div><div className="text-[10px] text-vscode-muted">{account.provider ?? "Compte"} · {account.maskedIdentifier ?? "identifiant masqué"}</div></div><select value={account.usage} onChange={async (e) => { await saveFinanceAccountAssignment(account.id, e.target.value as AccountUsage, account.defaultScopeId); await reload(); }} className="rounded border border-vscode-border bg-vscode-bg px-2 text-xs"><option value="personal">Personnel</option><option value="business">Professionnel</option><option value="shared">Partagé</option><option value="mixed">Mixte</option></select><select value={account.defaultScopeId ?? ""} onChange={async (e) => { await saveFinanceAccountAssignment(account.id, account.usage, e.target.value || undefined); await reload(); }} className="rounded border border-vscode-border bg-vscode-bg px-2 text-xs"><option value="">Aucun périmètre par défaut</option>{data.scopes.map((scope) => <option key={scope.id} value={scope.id}>{scope.name}</option>)}</select></div>)}</div></section>
    <section className="mt-5 rounded border border-vscode-border bg-vscode-panel"><div className="flex flex-wrap items-center gap-2 border-b border-vscode-border p-3"><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Rechercher libellé, montant, compte…" className="min-w-56 flex-1 rounded border border-vscode-border bg-vscode-bg px-3 py-2 text-xs"/><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={onlyUnassigned} onChange={(e) => setOnlyUnassigned(e.target.checked)} /> À arbitrer seulement</label><select value={batchScope} onChange={(e) => setBatchScope(e.target.value)} className="rounded border border-vscode-border bg-vscode-bg px-2 py-2 text-xs"><option value="">Affecter la sélection à…</option>{data.scopes.map((scope) => <option key={scope.id} value={scope.id}>{scope.name}</option>)}</select><button disabled={busy || !batchScope || !selected.size} onClick={() => void applyBatch()} className="rounded bg-vscode-accent px-3 py-2 text-xs font-semibold text-white disabled:opacity-40">Affecter ({selected.size})</button></div>
      <div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="text-[10px] uppercase text-vscode-muted"><tr><th className="p-3"></th><th>Date / libellé</th><th>Compte</th><th className="text-right">Montant</th><th>Répartition</th><th></th></tr></thead><tbody>{rows.map((transaction) => <tr key={transaction.key} className="border-t border-vscode-border"><td className="p-3"><input type="checkbox" checked={selected.has(transaction.key)} onChange={(e) => setSelected((previous) => { const next = new Set(previous); e.target.checked ? next.add(transaction.key) : next.delete(transaction.key); return next; })}/></td><td className="py-3"><div className="font-semibold">{transaction.label}</div><div className="text-[10px] text-vscode-muted">{transaction.date} · {sourceLabels[transaction.allocationSource]}</div></td><td>{transaction.accountName}</td><td className={`text-right font-semibold ${transaction.amount_ttc >= 0 ? "text-green-400" : "text-red-400"}`}>{euro.format(transaction.amount_ttc)}</td><td className="px-3">{transaction.allocations.length ? transaction.allocations.map((part) => <span key={part.scopeId} className="mr-1 inline-block rounded bg-blue-950/50 px-2 py-1 text-[10px] text-blue-300">{scopeName(part.scopeId)} · {euro.format(part.amount)}</span>) : <span className="rounded bg-amber-950/40 px-2 py-1 text-[10px] text-amber-300">À arbitrer</span>}</td><td className="p-3"><button onClick={() => openEditor(transaction)} className="rounded border border-vscode-accent px-2 py-1 text-vscode-accent">Répartir</button></td></tr>)}</tbody></table></div>
    </section>
    {editing && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4"><div className="w-full max-w-xl rounded border border-vscode-border bg-vscode-panel p-5 shadow-xl"><h2 className="text-lg font-semibold">Répartir {euro.format(editing.amount_ttc)}</h2><p className="mt-1 text-xs text-vscode-muted">{editing.label}</p><div className="mt-4 space-y-2">{parts.map((part, index) => <div key={index} className="grid grid-cols-[1fr_130px_30px] gap-2"><select value={part.scopeId} onChange={(e) => setParts((all) => all.map((item, i) => i === index ? { ...item, scopeId: e.target.value } : item))} className="rounded border border-vscode-border bg-vscode-bg px-2 py-2 text-xs">{data.scopes.map((scope) => <option key={scope.id} value={scope.id}>{scope.name} · {scope.kind === "person" ? "personne" : scope.kind === "household" ? "foyer" : "entreprise"}</option>)}</select><input inputMode="decimal" value={part.amount} onChange={(e) => setParts((all) => all.map((item, i) => i === index ? { ...item, amount: e.target.value } : item))} className="rounded border border-vscode-border bg-vscode-bg px-2 text-right text-xs"/><button onClick={() => setParts((all) => all.filter((_, i) => i !== index))} className="text-red-400">×</button></div>)}</div><button onClick={() => setParts((all) => [...all, { scopeId: data.scopes[0]?.id ?? "", amount: "0" }])} className="mt-3 text-xs text-vscode-accent">+ Ajouter une part</button><div className="mt-4 flex flex-wrap items-center justify-between gap-3"><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={rememberRule} onChange={(e) => setRememberRule(e.target.checked)}/> Mémoriser pour les libellés similaires (si une seule part)</label><div className="flex gap-2"><button onClick={() => setEditing(null)} className="rounded border border-vscode-border px-3 py-2 text-xs">Annuler</button><button disabled={busy || !parts.length} onClick={() => void saveSplit()} className="rounded bg-vscode-accent px-3 py-2 text-xs font-semibold text-white disabled:opacity-40">Valider la répartition</button></div></div></div></div>}
  </div>;
}
